Repository chapel-lang/chapel, pull requests merged in 2018-08, with the labels that each got.

#10641 Deinitialize modules in code compiled using --library
  modules/internal/ChapelUtil.chpl
  modules/minimal/internal/ChapelUtil.chpl
  runtime/src/chpl-init.c
  test/compflags/lydia/library/deinit/.gitignore
  test/compflags/lydia/library/deinit/callMyLib.cleanfiles
  test/compflags/lydia/library/deinit/callMyLib.good
  test/compflags/lydia/library/deinit/callMyLib.lastcompopts
  test/compflags/lydia/library/deinit/callMyLib.precomp
  test/compflags/lydia/library/deinit/callMyLib.test.c
  test/compflags/lydia/library/deinit/myLib.chpl
  test/compflags/lydia/library/deinit/myLib.notest
Labels: area: Modules, area: Runtime, area: Tools

#10643 Prototype support for "always RVF" types
  compiler/include/flags_list.h
  compiler/optimizations/remoteValueForwarding.cpp
  test/optimizations/remoteValueForwarding/alwaysRVFpragma.chpl
  test/optimizations/remoteValueForwarding/alwaysRVFpragma.comm-none.good
  test/optimizations/remoteValueForwarding/alwaysRVFpragma.good
  test/optimizations/remoteValueForwarding/alwaysRVFpragma.numlocales
Labels: stat: Needs Design Review

#10642 Fix throwing loop expressions
  compiler/AST/foralls.cpp
  compiler/include/errorHandling.h
  compiler/include/expr.h
  compiler/passes/errorHandling.cpp
  compiler/resolution/implementForallIntents.cpp
  compiler/resolution/lowerForalls.cpp
  compiler/resolution/lowerIterators.cpp
  compiler/resolution/preFold.cpp
  test/errhandling/ferguson/ifexpr-array-literal.chpl
  test/errhandling/ferguson/ifexpr-array-literal.future
  test/errhandling/ferguson/ifexpr-array-literal.good
  test/errhandling/ferguson/ifexpr-array-literal.skipif
  test/errhandling/ferguson/loopexprs-caught.00.good
  test/errhandling/ferguson/loopexprs-caught.10.good
  test/errhandling/ferguson/loopexprs-caught.11.good
  test/errhandling/ferguson/loopexprs-caught.12.good
  test/errhandling/ferguson/loopexprs-caught.13.good
  test/errhandling/ferguson/loopexprs-caught.20.good
  test/errhandling/ferguson/loopexprs-caught.21.good
  test/errhandling/ferguson/loopexprs-caught.22.good
  test/errhandling/ferguson/loopexprs-caught.23.good
  test/errhandling/ferguson/loopexprs-caught.chpl
  test/errhandling/ferguson/loopexprs-caught.execopts
  test/errhandling/ferguson/loopexprs-uncaught.chpl
  test/errhandling/ferguson/loopexprs-uncaught.good
Labels: stat: Ready to Merge

#10657 Changes to support --library-makefile compilation with ./configure set up
  compiler/codegen/library.cpp
  util/buildRelease/install.sh
Labels: area: Compiler, area: Tools, stat: Needs Code Review

#10448 Add join() that takes iterator expressions
  modules/internal/String.chpl
  test/types/string/methods/join-loop-expr.chpl
  test/types/string/methods/join-loop-expr.good
Labels: stat: Needs Code Review, stat: Needs Design Review, stat: Needs Testing

#10698 Generate pxd file when compiling with --library-python
  compiler/codegen/codegen.cpp
  compiler/codegen/library.cpp
  compiler/codegen/symbol.cpp
  compiler/include/FnSymbol.h
  compiler/include/driver.h
  compiler/include/library.h
  compiler/include/symbol.h
  compiler/main/driver.cpp
  test/compflags/lydia/library/python/.gitignore
  test/compflags/lydia/library/python/CLEANFILES
  test/compflags/lydia/library/python/COMPOPTS
  test/compflags/lydia/library/python/boolFunctions.catfiles
  test/compflags/lydia/library/python/boolFunctions.chpl
  test/compflags/lydia/library/python/boolFunctions.good
  test/compflags/lydia/library/python/boolFunctions.noexec
  test/compflags/lydia/library/python/complexFunctions.catfiles
  test/compflags/lydia/library/python/complexFunctions.chpl
  test/compflags/lydia/library/python/complexFunctions.good
  test/compflags/lydia/library/python/complexFunctions.noexec
  test/compflags/lydia/library/python/realFunctions.catfiles
  test/compflags/lydia/library/python/realFunctions.chpl
  test/compflags/lydia/library/python/realFunctions.good
  test/compflags/lydia/library/python/realFunctions.noexec
  test/compflags/lydia/library/python/stringFunctions.catfiles
  test/compflags/lydia/library/python/stringFunctions.chpl
  test/compflags/lydia/library/python/stringFunctions.good
  test/compflags/lydia/library/python/stringFunctions.noexec
  test/compflags/lydia/library/python/sub_test
  test/compflags/lydia/library/python/testing.catfiles
  test/compflags/lydia/library/python/testing.chpl
  test/compflags/lydia/library/python/testing.good
  test/compflags/lydia/library/python/testing.noexec
  test/compflags/lydia/library/python/uintFunctions.catfiles
  test/compflags/lydia/library/python/uintFunctions.chpl
  test/compflags/lydia/library/python/uintFunctions.good
  test/compflags/lydia/library/python/uintFunctions.noexec
  util/chpl-completion.bash
Labels: area: Compiler, area: Tools, stat: Needs Code Review

#10716 Makefile implementation cleanup suggested by Michael
  compiler/codegen/library.cpp
Labels: area: Compiler, area: Tools, stat: Needs Testing

#10663 build_configs: add setenv-example-3.bash (#9551)
  util/build_configs/.gitignore
  util/build_configs/README.md
  util/build_configs/build_configs.py
  util/build_configs/functions.bash
  util/build_configs/module-functions.bash
  util/build_configs/setenv-example-1.bash
  util/build_configs/setenv-example-2.bash
  util/build_configs/setenv-example-3.bash
Labels: area: BTR

#10611 Fix problem with throwing nested call var init
  compiler/passes/normalize.cpp
  compiler/resolution/callDestructors.cpp
  compiler/resolution/preFold.cpp
  modules/internal/ChapelBase.chpl
  modules/internal/SharedObject.chpl
  modules/standard/Regexp.chpl
  test/errhandling/ferguson/ifexpr-array-literal.future
  test/errhandling/ferguson/nested-call-expr-var-init-throws.chpl
  test/errhandling/ferguson/nested-call-expr-var-init-throws.good
  test/types/string/ferguson/string-useless-cast.chpl
  test/types/string/ferguson/string-useless-cast.good
Labels: stat: Ready to Merge

#10738 Fix override checking for generic children of concrete
  compiler/resolution/virtualDispatch.cpp
  test/classes/ferguson/override/override-generic-concrete-missing.chpl
  test/classes/ferguson/override/override-generic-concrete-missing.good
  test/classes/ferguson/override/override-generic-concrete-spurious.chpl
  test/classes/ferguson/override/override-generic-concrete-spurious.good
  test/classes/ferguson/override/override-generic-concrete.chpl
  test/classes/ferguson/override/override-generic-concrete.good
  test/functions/resolution/overload-in-generic.bad
  test/functions/resolution/overload-in-generic.compopts
  test/functions/resolution/overload-in-generic.future
  test/functions/resolution/overload-in-generic.good
Labels: stat: Ready to Merge

#10737 Replace the main module error message in library compilation
  compiler/AST/ModuleSymbol.cpp
  test/compflags/lydia/library/errorMessage/multiMod/.gitignore
  test/compflags/lydia/library/errorMessage/multiMod/callMultiModLib.cleanfiles
  test/compflags/lydia/library/errorMessage/multiMod/callMultiModLib.good
  test/compflags/lydia/library/errorMessage/multiMod/callMultiModLib.lastcompopts
  test/compflags/lydia/library/errorMessage/multiMod/callMultiModLib.precomp
  test/compflags/lydia/library/errorMessage/multiMod/callMultiModLib.test.c
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.bad
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.chpl
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.cleanfiles
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.compopts
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.error.good
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.future
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.good
  test/compflags/lydia/library/errorMessage/multiMod/multipleModules.noexec
Labels: area: Compiler, area: Tests, area: Tools, stat: Ready to Merge

#10727 Added polly_array_index call to the DefaultRectangularArr class
  modules/internal/DefaultRectangular.chpl
Labels: stat: Ready to Merge

#10726 AST dumps indicate varargs
  compiler/AST/AstDump.cpp
Labels: stat: Ready to Merge

#10808 Improve override errors for inherited iterators
  compiler/AST/FnSymbol.cpp
  compiler/include/FnSymbol.h
  compiler/resolution/virtualDispatch.cpp
  test/classes/dinan/dyndispatch_these.chpl
  test/classes/ferguson/override/override-combined.good
  test/classes/ferguson/override/override-iter-missing.chpl
  test/classes/ferguson/override/override-iter-missing.good
  test/classes/ferguson/override/override-iter-ok.chpl
  test/classes/ferguson/override/override-iter-ok.good
  test/classes/ferguson/override/override-iter-spurious.chpl
  test/classes/ferguson/override/override-iter-spurious.good
  test/functions/deitz/iterators/test_override1.chpl
  test/functions/deitz/iterators/test_override2.chpl
  test/functions/deitz/iterators/test_override3.chpl
  test/functions/deitz/iterators/test_override4.chpl
  test/functions/deitz/iterators/test_override5_error.chpl
  test/functions/iterators/bradc/override.chpl
  test/functions/iterators/bradc/override2.chpl
  test/functions/iterators/diten/dynamicDispatchIterator3Levels.chpl
  test/functions/iterators/vass/dynamic-dispatch-iterators.chpl
  test/trivial/jturner/iter_overload_simple-blc.chpl
  test/trivial/jturner/iter_overload_simple.chpl
  test/users/thom/itoverride.chpl
Labels: stat: Ready to Merge

#10812 Remove skipifs now the top-level one checks openssl version
  test/library/packages/Crypto/saru/aes/aesTest1.skipif
  test/library/packages/Crypto/saru/blowfish/bfTest2.skipif
  test/library/packages/Crypto/saru/kdf/pbkdf2-1.skipif
  test/library/packages/Crypto/saru/kdf/pbkdf2-2.skipif
Labels: stat: Ready to Merge

#10811 Fix memory leak in list.pop_front
  modules/standard/List.chpl
Labels: stat: Ready to Merge

#10668 Mason: external package manager integration
  doc/rst/tools/mason/mason.rst
  test/library/packages/LinearAlgebra/correctness/TestUtils.chpl
  test/mason/add-remove-tests/addExternal.good
  test/mason/filterDigits
  test/mason/spack-integration/.gitignore
  test/mason/spack-integration/.mason.notest
  test/mason/spack-integration/CLEANFILES
  test/mason/spack-integration/COMPOPTS
  test/mason/spack-integration/EXECENV
  test/mason/spack-integration/Mason.lock
  test/mason/spack-integration/Mason.toml
  test/mason/spack-integration/SKIPIF
  test/mason/spack-integration/mason-external.chpl
  test/mason/spack-integration/mason-external.good
  test/mason/spack-integration/mason-external.prediff
  test/mason/spack-integration/mason-external.skipif
  test/mason/spack-integration/mason-external.timeout
  test/mason/spack-integration/src/NOTEST
  test/mason/spack-integration/src/masonLA.chpl
  test/mason/spec-parser/COMPOPTS
  test/mason/spec-parser/EXECENV
  test/mason/spec-parser/SKIPIF
  test/mason/spec-parser/test-spec-parser.chpl
  test/mason/spec-parser/test-spec-parser.good
  test/mason/spec-parser/test-spec-parser.prediff
  test/mason/spec-parser/test-spec-parser.skipif
  tools/mason/MasonBuild.chpl
  tools/mason/MasonExample.chpl
  tools/mason/MasonExternal.chpl
  tools/mason/MasonHelp.chpl
  tools/mason/MasonModify.chpl
  tools/mason/MasonTest.chpl
  tools/mason/MasonUpdate.chpl
  tools/mason/MasonUtils.chpl
  tools/mason/SpecParser.chpl
  tools/mason/mason.chpl
Labels: area: Third-Party, area: Tools

#10795 Documentation for Mason Packages
  doc/util/gen-package-list.py
Labels: area: Docs

#10869 Generate last file needed for compiling a Python module using Cython
  compiler/codegen/library.cpp
  test/compflags/lydia/library/noLibFlag/pythonCompile.catfiles
  test/compflags/lydia/library/noLibFlag/pythonCompile.good
  test/compflags/lydia/library/noLibFlag/pythonCompile.prediff
  test/compflags/lydia/library/python/PREDIFF
  test/compflags/lydia/library/python/boolFunctions.catfiles
  test/compflags/lydia/library/python/boolFunctions.good
  test/compflags/lydia/library/python/checkExplicitLibname.catfiles
  test/compflags/lydia/library/python/checkExplicitLibname.good
  test/compflags/lydia/library/python/complexFunctions.catfiles
  test/compflags/lydia/library/python/complexFunctions.good
  test/compflags/lydia/library/python/realFunctions.catfiles
  test/compflags/lydia/library/python/realFunctions.good
  test/compflags/lydia/library/python/stringFunctions.catfiles
  test/compflags/lydia/library/python/stringFunctions.good
  test/compflags/lydia/library/python/testing.catfiles
  test/compflags/lydia/library/python/testing.good
  test/compflags/lydia/library/python/uintFunctions.catfiles
  test/compflags/lydia/library/python/uintFunctions.good
Labels: area: Compiler, area: Tests, area: Tools, stat: Needs Code Review

#10881 Fix valgrind issue with python library compilation
  compiler/codegen/library.cpp
Labels: area: Compiler, area: Tests

#10861 Expand generated Python files to appropriately handle wrapped array types
  compiler/codegen/library.cpp
  compiler/codegen/symbol.cpp
  compiler/include/FnSymbol.h
  compiler/include/library.h
  compiler/passes/normalize.cpp
  runtime/include/python/chplrt.pxd
  test/compflags/lydia/library/noLibFlag/pythonCompile.good
  test/compflags/lydia/library/python/arrayAndExternArrayType.catfiles
  test/compflags/lydia/library/python/arrayAndExternArrayType.chpl
  test/compflags/lydia/library/python/arrayAndExternArrayType.future
  test/compflags/lydia/library/python/arrayAndExternArrayType.good
  test/compflags/lydia/library/python/arrayAndExternArrayType.noexec
  test/compflags/lydia/library/python/boolFunctions.good
  test/compflags/lydia/library/python/checkExplicitLibname.good
  test/compflags/lydia/library/python/complexFunctions.good
  test/compflags/lydia/library/python/intArrays.catfiles
  test/compflags/lydia/library/python/intArrays.chpl
  test/compflags/lydia/library/python/intArrays.good
  test/compflags/lydia/library/python/intArrays.noexec
  test/compflags/lydia/library/python/realArrays.catfiles
  test/compflags/lydia/library/python/realArrays.chpl
  test/compflags/lydia/library/python/realArrays.good
  test/compflags/lydia/library/python/realArrays.noexec
  test/compflags/lydia/library/python/realFunctions.good
  test/compflags/lydia/library/python/stringFunctions.good
  test/compflags/lydia/library/python/testing.good
  test/compflags/lydia/library/python/uintFunctions.good
Labels: area: Compiler, area: Tests, area: Tools, stat: Ready to Merge

#10924 Get compiler to actually build the Python module from the library when possible
  compiler/codegen/codegen.cpp
  compiler/codegen/library.cpp
  compiler/codegen/symbol.cpp
  compiler/include/library.h
  test/compflags/lydia/library/noLibFlag/pythonCompile.catfiles
  test/compflags/lydia/library/noLibFlag/pythonCompile.chpl
  test/compflags/lydia/library/noLibFlag/pythonCompile.good
  test/compflags/lydia/library/noLibFlag/pythonCompile.prediff
  test/compflags/lydia/library/noLibFlag/pythonCompile.skipif
  test/compflags/lydia/library/noLibFlag/use_pythonCompile.py
  test/compflags/lydia/library/python/PREDIFF
  test/compflags/lydia/library/python/SKIPIF
  test/compflags/lydia/library/python/boolFunctions.catfiles
  test/compflags/lydia/library/python/boolFunctions.good
  test/compflags/lydia/library/python/boolFunctions.prediff
  test/compflags/lydia/library/python/checkExplicitLibname.catfiles
  test/compflags/lydia/library/python/checkExplicitLibname.chpl
  test/compflags/lydia/library/python/checkExplicitLibname.future
  test/compflags/lydia/library/python/checkExplicitLibname.good
  test/compflags/lydia/library/python/checkExplicitLibname.prediff
  test/compflags/lydia/library/python/complexFunctions.catfiles
  test/compflags/lydia/library/python/complexFunctions.good
  test/compflags/lydia/library/python/complexFunctions.prediff
  test/compflags/lydia/library/python/intArrays.catfiles
  test/compflags/lydia/library/python/intArrays.chpl
  test/compflags/lydia/library/python/intArrays.good
  test/compflags/lydia/library/python/intArrays.prediff
  test/compflags/lydia/library/python/lib.notest
  test/compflags/lydia/library/python/realArrays.catfiles
  test/compflags/lydia/library/python/realArrays.chpl
  test/compflags/lydia/library/python/realArrays.good
  test/compflags/lydia/library/python/realArrays.prediff
  test/compflags/lydia/library/python/realFunctions.catfiles
  test/compflags/lydia/library/python/realFunctions.good
  test/compflags/lydia/library/python/realFunctions.prediff
  test/compflags/lydia/library/python/skipif_helper.py
  test/compflags/lydia/library/python/stringFunctions.catfiles
  test/compflags/lydia/library/python/stringFunctions.good
  test/compflags/lydia/library/python/stringFunctions.prediff
  test/compflags/lydia/library/python/testing.catfiles
  test/compflags/lydia/library/python/testing.chpl
  test/compflags/lydia/library/python/testing.good
  test/compflags/lydia/library/python/testing.prediff
  test/compflags/lydia/library/python/uintFunctions.catfiles
  test/compflags/lydia/library/python/uintFunctions.good
  test/compflags/lydia/library/python/uintFunctions.prediff
  test/compflags/lydia/library/python/use_boolFunctions.py
  test/compflags/lydia/library/python/use_checkExplicitLibname.py
  test/compflags/lydia/library/python/use_complexFunctions.py
  test/compflags/lydia/library/python/use_intArrays.py
  test/compflags/lydia/library/python/use_realArrays.py
  test/compflags/lydia/library/python/use_realFunctions.py
  test/compflags/lydia/library/python/use_stringFunctions.py
  test/compflags/lydia/library/python/use_testing.py
  test/compflags/lydia/library/python/use_uintFunctions.py
Labels: area: Compiler, area: Tests, area: Tools, stat: Needs Code Review

#10925 Add a cron script for running the tests of built python modules
  util/cron/test-python-modules.bash
Labels: area: BTR, stat: Needs Code Review

#10930 Add support for setting the name of the generated Python module via a flag
  compiler/codegen/codegen.cpp
  compiler/main/driver.cpp
  test/compflags/lydia/library/noLibFlag/checkDiffPythonModname.chpl
  test/compflags/lydia/library/noLibFlag/checkDiffPythonModname.compopts
  test/compflags/lydia/library/noLibFlag/checkDiffPythonModname.good
  test/compflags/lydia/library/noLibFlag/checkDiffPythonModname.noexec
  test/compflags/lydia/library/noLibFlag/checkDiffPythonModname.prediff
  test/compflags/lydia/library/noLibFlag/checkDiffPythonModname.skipif
  test/compflags/lydia/library/noLibFlag/use_bar.py
  test/compflags/lydia/library/python/checkDiffModname.chpl
  test/compflags/lydia/library/python/checkDiffModname.compopts
  test/compflags/lydia/library/python/checkDiffModname.good
  test/compflags/lydia/library/python/checkDiffModname.noexec
  test/compflags/lydia/library/python/checkDiffModname.prediff
  test/compflags/lydia/library/python/makeNewTest.sh
  test/compflags/lydia/library/python/use_bar.py
  util/chpl-completion.bash
Labels: area: Compiler, area: Tests, area: Tools, stat: Needs Code Review

#10915 Fix typos
  compiler/resolution/implementForallIntents.cpp
  compiler/resolution/lowerForalls.cpp
  doc/rst/tools/mason/mason.rst
Labels: area: Compiler, area: Docs, stat: Ready to Merge
