Repository chapel-lang/chapel, pull requests merged in 2018-10, with the labels that each got.

#11255 Avoid handling overrides where parent has 'where false'
  compiler/resolution/virtualDispatch.cpp
Labels: stat: Ready to Merge

#11226 Error if use statement lists the used module (or any parent) in its limitation clause
  compiler/AST/UseStmt.cpp
  compiler/passes/ResolveScope.cpp
  test/visibility/except/exceptModuleItself.chpl
  test/visibility/except/exceptModuleItself.good
  test/visibility/except/exceptWrongSymbol.good
  test/visibility/only/badName.good
  test/visibility/only/exceptOnlyPrevents2.good
  test/visibility/only/innerModuleSharesName-topLevel.bad
  test/visibility/only/innerModuleSharesName-topLevel.chpl
  test/visibility/only/innerModuleSharesName-topLevel.future
  test/visibility/only/innerModuleSharesName-topLevel.good
  test/visibility/only/innerModuleSharesName.chpl
  test/visibility/only/innerModuleSharesName.good
  test/visibility/only/onlyModuleItself.chpl
  test/visibility/only/onlyModuleItself.good
  test/visibility/only/onlyOuterModule.chpl
  test/visibility/only/onlyOuterModule.good
  test/visibility/rename/renameModuleViaOnly.chpl
  test/visibility/rename/renameModuleViaOnly.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#11211 Minor external array cleanups, suggested by Michael
  modules/internal/ExternalArray.chpl
  test/compflags/lydia/library/exportArray/callCheckIfEmpty.cleanfiles
  test/compflags/lydia/library/exportArray/callCheckIfEmpty.good
  test/compflags/lydia/library/exportArray/callCheckIfEmpty.lastcompopts
  test/compflags/lydia/library/exportArray/callCheckIfEmpty.precomp
  test/compflags/lydia/library/exportArray/callCheckIfEmpty.test.c
  test/compflags/lydia/library/exportArray/checkIfEmpty.chpl
  test/compflags/lydia/library/exportArray/checkIfEmpty.notest
Labels: area: Libraries, area: Tools, stat: Needs Code Review

#11281 Various new --library tests and an error message improvement
  compiler/passes/normalize.cpp
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl.cleanfiles
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl.good
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl.lastcompopts
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl.precomp
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl.test.c
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl2.cleanfiles
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl2.good
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl2.lastcompopts
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl2.precomp
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayGenericDecl2.test.c
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayTakesArrayArg4.cleanfiles
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayTakesArrayArg4.good
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayTakesArrayArg4.lastcompopts
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayTakesArrayArg4.precomp
  test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayTakesArrayArg4.test.c
  test/compflags/lydia/library/exportArray/returningArr/returnArrayGenericDecl.chpl
  test/compflags/lydia/library/exportArray/returningArr/returnArrayGenericDecl.notest
  test/compflags/lydia/library/exportArray/returningArr/returnArrayGenericDecl2.chpl
  test/compflags/lydia/library/exportArray/returningArr/returnArrayGenericDecl2.notest
  test/compflags/lydia/library/exportArray/returningArr/returnArrayTakesArrayArg4.chpl
  test/compflags/lydia/library/exportArray/returningArr/returnArrayTakesArrayArg4.notest
  test/compflags/lydia/library/makefiles/.gitignore
  test/compflags/lydia/library/makefiles/Makefile
  test/compflags/lydia/library/makefiles/checkCommandLineLib.c
  test/compflags/lydia/library/makefiles/commandLineLib.chpl
  test/compflags/lydia/library/makefiles/commandLineLib.cleanfiles
  test/compflags/lydia/library/makefiles/commandLineLib.compenv
  test/compflags/lydia/library/makefiles/commandLineLib.compopts
  test/compflags/lydia/library/makefiles/commandLineLib.good
  test/compflags/lydia/library/makefiles/commandLineLib.noexec
  test/compflags/lydia/library/makefiles/commandLineLib.precomp
  test/compflags/lydia/library/makefiles/commandLineLib.prediff
  test/compflags/lydia/library/makefiles/commandLineLib.skipif
  test/compflags/lydia/library/python/returnArrayGenericDecl.bad
  test/compflags/lydia/library/python/returnArrayGenericDecl.chpl
  test/compflags/lydia/library/python/returnArrayGenericDecl.future
  test/compflags/lydia/library/python/returnArrayGenericDecl.good
  test/compflags/lydia/library/python/returnArrayGenericDecl.noexec
  test/compflags/lydia/library/python/returnArrayGenericDecl.prediff
  test/compflags/lydia/library/python/returnArrayGenericDecl2.bad
  test/compflags/lydia/library/python/returnArrayGenericDecl2.chpl
  test/compflags/lydia/library/python/returnArrayGenericDecl2.future
  test/compflags/lydia/library/python/returnArrayGenericDecl2.good
  test/compflags/lydia/library/python/returnArrayGenericDecl2.noexec
  test/compflags/lydia/library/python/returnArrayGenericDecl2.prediff
  test/compflags/lydia/library/python/use_returnArrayGenericDecl.py
  test/compflags/lydia/library/python/use_returnArrayGenericDecl2.py
Labels: area: Compiler, area: Tests, area: Tools

#11210 Adjust llvm-global-to-wide to pass in Debug mode
  compiler/include/llvmGlobalToWide.h
  compiler/llvm/clangUtil.cpp
  compiler/llvm/llvm-global-to-wide/RUN_CONFIG
  compiler/llvm/llvmGlobalToWide.cpp
Labels: stat: Ready to Merge

#11359 Add a tuples primer
  doc/rst/meta/primers/index.rst
  test/release/examples/primers/tuples.chpl
  test/release/examples/primers/tuples.good
Labels: stat: Ready to Merge

#11362 Records primer
  doc/rst/meta/primers/index.rst
  test/release/examples/primers/classes.chpl
  test/release/examples/primers/genericClasses.chpl
  test/release/examples/primers/genericClasses.good
  test/release/examples/primers/records.chpl
  test/release/examples/primers/records.good
Labels: stat: Ready to Merge

#11327 Adjust runtime library and third party directories to include CHPL_LIBMODE
  make/Makefile.base
  runtime/make/Makefile.runtime.include
  third-party/gasnet/Makefile
  third-party/gasnet/Makefile.include
  third-party/gmp/Makefile
  third-party/hwloc/Makefile
  third-party/jemalloc/Makefile
  third-party/libunwind/Makefile
  third-party/massivethreads/Makefile
  third-party/qthread/Makefile
  third-party/re2/Makefile
  util/chplenv/__init__.py
  util/chplenv/chpl_lib_pic.py
  util/chplenv/overrides.py
  util/chplenv/third_party_utils.py
  util/cron/test-python-modules.bash
  util/printchplenv
Labels: area: BTR, area: Makefiles, area: Runtime, stat: Needs Code Review

#11383 Fix typos
  compiler/AST/primitive.cpp
  compiler/passes/initializerRules.cpp
  runtime/src/comm/ugni/comm-ugni.c
  spec/TODO
  test/classes/initializers/postInit/invalidSuperPostinit.good
  test/release/examples/primers/records.chpl
  test/release/examples/primers/tuples.chpl
Labels: stat: Needs Testing

#11379 Add some documentation about CHPL_LIB_PIC.
  doc/rst/technotes/libraries.rst
  doc/rst/usingchapel/chplenv.rst
Labels: area: Docs, stat: Needs Code Review

#11389 Fix issue with rethrowing specific errors that were just caught
  compiler/passes/errorHandling.cpp
  test/errhandling/lydia/notAnErrorSubtype-caught.chpl
  test/errhandling/lydia/notAnErrorSubtype-caught.good
  test/errhandling/lydia/notAnErrorSubtype-caught2.bad
  test/errhandling/lydia/notAnErrorSubtype-caught2.chpl
  test/errhandling/lydia/notAnErrorSubtype-caught2.future
  test/errhandling/lydia/notAnErrorSubtype-caught2.good
  test/errhandling/lydia/notAnErrorSubtype-rethrown.bad
  test/errhandling/lydia/notAnErrorSubtype-rethrown.chpl
  test/errhandling/lydia/notAnErrorSubtype-rethrown.future
  test/errhandling/lydia/notAnErrorSubtype-rethrown.good
  test/errhandling/lydia/notAnErrorSubtype-rethrown2.bad
  test/errhandling/lydia/notAnErrorSubtype-rethrown2.chpl
  test/errhandling/lydia/notAnErrorSubtype-rethrown2.future
  test/errhandling/lydia/notAnErrorSubtype-rethrown2.good
  test/errhandling/lydia/notAnErrorSubtype-thrown.bad
  test/errhandling/lydia/notAnErrorSubtype-thrown.chpl
  test/errhandling/lydia/notAnErrorSubtype-thrown.future
  test/errhandling/lydia/notAnErrorSubtype-thrown.good
  test/errhandling/lydia/rethrownGenerally-nested.chpl
  test/errhandling/lydia/rethrownGenerally-nested.good
  test/errhandling/lydia/rethrownGenerally.chpl
  test/errhandling/lydia/rethrownGenerally.good
Labels: area: Compiler, area: Tests, stat: Ready to Merge

#11104 Improves internal error output
  compiler/include/misc.h
  compiler/make/Makefile.compiler.foot
  compiler/parser/bison-chapel.cpp
  compiler/parser/chapel.ypp
  compiler/util/misc.cpp
  test/classes/ferguson/class-alias-generic-arg.bad
  test/classes/vass/no-instance-for-arg-type.bad
  test/expressions/loop-expr/forall-over-zip-over-arrays.bad
  test/functions/bradc/paramThis/funParamThis3.bad
  test/functions/diten/formalArrayWithQueriedEltSize.bad
  test/functions/lydia/infinite-recursion-arg.bad
  test/parallel/forall/vass/reduce-with-for-in-par-iter.reduce2.bad
  test/types/enum/lydia/declaredInClass-initializer.bad
  test/types/enum/scope-param-offset-type.bad
  test/types/records/init/nested-empty-record.bad
  test/types/records/tupleFields/detupleFieldDecl.bad
  test/users/engin/retInnerFunction.bad
  test/users/vass/tuple-crash-1.bad
  test/users/vass/uniquify/u1-local-user-extern.bad
  test/users/vass/uniquify/u2-local-extern-extern.bad
  util/test/diff-ignoring-module-line-numbers
Labels: stat: Ready to Merge

#11446 Change error when calling throwing task function to calling function within it
  compiler/passes/errorHandling.cpp
  test/errhandling/parallel/begin-calls-throwing-fn.chpl
  test/errhandling/parallel/begin-calls-throwing-fn.good
  test/errhandling/parallel/begin-on-calls-throwing-fn.chpl
  test/errhandling/parallel/begin-on-calls-throwing-fn.good
  test/errhandling/parallel/cobegin-calls-throwing-fn.chpl
  test/errhandling/parallel/cobegin-calls-throwing-fn.good
  test/errhandling/parallel/cobegin-on-calls-throwing-fn.chpl
  test/errhandling/parallel/cobegin-on-calls-throwing-fn.good
  test/errhandling/parallel/coforall-calls-throwing-fn.chpl
  test/errhandling/parallel/coforall-calls-throwing-fn.good
  test/errhandling/parallel/coforall-on-calls-throwing-fn.chpl
  test/errhandling/parallel/coforall-on-calls-throwing-fn.good
  test/errhandling/parallel/for-calls-throwing-fn.chpl
  test/errhandling/parallel/for-calls-throwing-fn.good
  test/errhandling/parallel/forall-calls-throwing-fn.chpl
  test/errhandling/parallel/forall-calls-throwing-fn.good
  test/errhandling/parallel/strict/coforall-throws-strict-error.good
  test/errhandling/psahabu/coforall-try-bang.good
Labels: area: Compiler, area: Tests

#11471 Improve error message when throwing something that is not an Error subtype
  modules/internal/ChapelError.chpl
  test/errhandling/lydia/notAnErrorSubtype-caught2.bad
  test/errhandling/lydia/notAnErrorSubtype-caught2.future
  test/errhandling/lydia/notAnErrorSubtype-caught2.good
  test/errhandling/lydia/notAnErrorSubtype-rethrown.bad
  test/errhandling/lydia/notAnErrorSubtype-rethrown.future
  test/errhandling/lydia/notAnErrorSubtype-rethrown.good
  test/errhandling/lydia/notAnErrorSubtype-rethrown2.bad
  test/errhandling/lydia/notAnErrorSubtype-rethrown2.future
  test/errhandling/lydia/notAnErrorSubtype-rethrown2.good
  test/errhandling/lydia/notAnErrorSubtype-thrown-int.chpl
  test/errhandling/lydia/notAnErrorSubtype-thrown-int.good
  test/errhandling/lydia/notAnErrorSubtype-thrown-owned.chpl
  test/errhandling/lydia/notAnErrorSubtype-thrown-owned.good
  test/errhandling/lydia/notAnErrorSubtype-thrown-record.chpl
  test/errhandling/lydia/notAnErrorSubtype-thrown-record.good
  test/errhandling/lydia/notAnErrorSubtype-thrown.bad
  test/errhandling/lydia/notAnErrorSubtype-thrown.future
  test/errhandling/lydia/notAnErrorSubtype-thrown.good
Labels: area: Libraries, area: Tests, stat: Needs Code Review

#11416 Add implementation of c_offsetof, based strongly on Nikhil's implementation
  modules/internal/CPtr.chpl
  test/modules/bradc/printModStuff/foo.good
  test/types/records/lydia/offsetNotRecord-array.chpl
  test/types/records/lydia/offsetNotRecord-array.good
  test/types/records/lydia/offsetNotRecord-class.chpl
  test/types/records/lydia/offsetNotRecord-class.good
  test/types/records/lydia/offsetNotRecord-int.chpl
  test/types/records/lydia/offsetNotRecord-int.good
  test/types/records/lydia/offsetNotRecord-sync.chpl
  test/types/records/lydia/offsetNotRecord-sync.good
  test/types/records/lydia/recordOffset-badField.chpl
  test/types/records/lydia/recordOffset-badField.good
  test/types/records/lydia/recordOffset-classField.chpl
  test/types/records/lydia/recordOffset-classField.good
  test/types/records/lydia/recordOffset-cstringField.chpl
  test/types/records/lydia/recordOffset-cstringField.good
  test/types/records/lydia/recordOffset-generic.chpl
  test/types/records/lydia/recordOffset-generic.good
  test/types/records/lydia/recordOffset-recordField.chpl
  test/types/records/lydia/recordOffset-recordField.good
  test/types/records/lydia/recordOffset-stringField.chpl
  test/types/records/lydia/recordOffset-stringField.good
  test/types/records/lydia/recordOffset.chpl
  test/types/records/lydia/recordOffset.good
Labels: area: Libraries, area: Tests, stat: Needs Code Review

#11481 Clean files mentioned in directory-wide CLEANFILES for individual test run
  util/test/sub_clean
Labels: area: BTR, area: Tests

#11482 Update CHIP 20 based on changes from last release
  doc/rst/developer/chips/20.rst
Labels: area: Docs

#11491 Add linux32.good files for recordOffset tests
  test/types/records/lydia/recordOffset-classField.linux32.good
  test/types/records/lydia/recordOffset-classField.skipif
  test/types/records/lydia/recordOffset-cstringField.linux32.good
  test/types/records/lydia/recordOffset-cstringField.skipif
  test/types/records/lydia/recordOffset-generic.linux32.good
  test/types/records/lydia/recordOffset-generic.skipif
  test/types/records/lydia/recordOffset-stringField.linux32.good
  test/types/records/lydia/recordOffset-stringField.skipif
  test/types/records/lydia/recordOffset.linux32.good
  test/types/records/lydia/recordOffset.skipif
Labels: area: Tests, stat: Ready to Merge

#11086 Move programs directory out of release
  doc/rst/technotes/localeModels.rst
  doc/rst/tools/chplvis/chplvis.rst
  test/release/examples/Makefile
  test/release/examples/README
  test/studies/programs/Makefile
  test/studies/programs/README
  test/studies/programs/beer.chpl
  test/studies/programs/beer.good
  test/studies/programs/genericStack.chpl
  test/studies/programs/genericStack.good
  test/studies/programs/jacobi.chpl
  test/studies/programs/jacobi.good
  test/studies/programs/linkedList.chpl
  test/studies/programs/linkedList.good
  test/studies/programs/norm.chpl
  test/studies/programs/norm.good
  test/studies/programs/prodCons.chpl
  test/studies/programs/prodCons.good
  test/studies/programs/quicksort.chpl
  test/studies/programs/quicksort.execopts
  test/studies/programs/quicksort.good
  test/studies/programs/tree.chpl
  test/studies/programs/tree.good
Labels: post-release

#11041 Report message size under verbose communication
  modules/standard/CommDiagnostics.chpl
  runtime/src/chpl-cache.c
  runtime/src/comm/gasnet/comm-gasnet.c
  runtime/src/comm/ugni/comm-ugni.c
  test/multilocale/engin/NUMLOCALES
  test/multilocale/engin/SKIPIF
  test/multilocale/engin/verboseComm.chpl
  test/multilocale/engin/verboseComm.good
Labels: post-release, stat: Work in Progress

#11048 Add support for using urxvt with CHPL_COMM_USE_(G|LL)DB
  runtime/src/launch/amudprun/launch-amudprun.c
Labels: post-release

#11531 Add future to track array argument default value issue
  test/arrays/lydia/defaultValue.bad
  test/arrays/lydia/defaultValue.chpl
  test/arrays/lydia/defaultValue.future
  test/arrays/lydia/defaultValue.good
Labels: area: Tests
