Repository chapel-lang/chapel, pull requests merged in 2018-05, with the labels that each got.

#9476 Remove a bad `assert(0)` from qio's setup_actions
  runtime/src/qio/qio_popen.c
Labels: area: Runtime

#9477 Update compiler to add export to user module's init functions in --library mode
  compiler/passes/normalize.cpp
  test/compflags/lydia/library/globals/CLEANFILES
  test/compflags/lydia/library/globals/PRECOMP
  test/compflags/lydia/library/globals/reliesOnGlobal.chpl
  test/compflags/lydia/library/globals/reliesOnGlobal.h
  test/compflags/lydia/library/globals/reliesOnGlobal.notest
  test/compflags/lydia/library/globals/use_reliesOnGlobal-library-init.good
  test/compflags/lydia/library/globals/use_reliesOnGlobal-library-init.lastcompopts
  test/compflags/lydia/library/globals/use_reliesOnGlobal-library-init.test.c
  test/compflags/lydia/library/globals/use_reliesOnGlobal.good
  test/compflags/lydia/library/globals/use_reliesOnGlobal.lastcompopts
  test/compflags/lydia/library/globals/use_reliesOnGlobal.test.c
Labels: area: Compiler, area: Tools, stat: Needs Code Review

#9504 Suppress pip 10 warnings for venv builds
  third-party/chpl-venv/Makefile
  third-party/chpl-venv/Makefile.include
Labels: stat: Ready to Merge

#9489 Enable fields with generic declared type
  compiler/AST/AggregateType.cpp
  compiler/AST/primitive.cpp
  compiler/include/AggregateType.h
  compiler/include/scopeResolve.h
  compiler/passes/InitNormalize.cpp
  compiler/passes/scopeResolve.cpp
  compiler/resolution/ResolutionCandidate.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/generics.cpp
  compiler/resolution/preFold.cpp
  test/classes/bradc/paramInClass/weirdParamInit3.good
  test/classes/bradc/paramInClass/weirdParamInit4.good
  test/classes/ferguson/class-alias-generic-arg.bad
  test/classes/ferguson/default-type-ctor-bug.chpl
  test/classes/ferguson/default-type-ctor-bug.good
  test/classes/ferguson/generic-field/generic-field-default-init.chpl
  test/classes/ferguson/generic-field/generic-field-default-init.good
  test/classes/ferguson/generic-field/generic-field-integral.chpl
  test/classes/ferguson/generic-field/generic-field-integral.good
  test/classes/ferguson/generic-field/generic-field-new-owned.chpl
  test/classes/ferguson/generic-field/generic-field-new-owned.good
  test/classes/ferguson/generic-field/generic-field-record.chpl
  test/classes/ferguson/generic-field/generic-field-record.good
  test/classes/ferguson/generic-field/generic-field-unmanaged-borrowed.chpl
  test/classes/ferguson/generic-field/generic-field-unmanaged-borrowed.good
  test/classes/ferguson/generic-field/generic-field.chpl
  test/classes/ferguson/generic-field/generic-field.good
  test/classes/initializers/phase1/syncFieldTypeAndInitSyncArg.skipif
  test/classes/initializers/phase1/syncFieldTypeOnlySyncArg.skipif
  test/classes/initializers/records/generics/copyInitInstantiation.good
  test/classes/initializers/records/init-with-call.chpl
  test/classes/initializers/records/init-with-call.good
  test/classes/initializers/records/init-with-new.chpl
  test/classes/initializers/records/init-with-new.good
  test/release/examples/benchmarks/miniMD/helpers/forces.chpl
  test/types/records/const-checking/initRecFieldWithConstField.bad
  test/types/records/const-checking/initRecFieldWithConstField.chpl
  test/types/records/const-checking/initRecFieldWithConstField.future
  test/types/sync/ferguson/sync-copy-init-other-sync.chpl
  test/types/sync/ferguson/sync-copy-init-other-sync.future
  test/types/sync/ferguson/sync-copy-init-other-sync.good
  test/types/sync/ferguson/sync-copy-init-other-sync.skipif
  test/users/thom/returnGeneric.good
  test/users/thom/returnGenericLineno/strassen.chpl
  test/users/thom/returnGenericLineno/util.good
  test/users/thom/returnGenericLineno/util.noexec
Labels: stat: Ready to Merge

#9581 Add a future for an error case with unmanaged classes
  test/classes/delete-free/unmanaged/unmanaged-generic2.bad
  test/classes/delete-free/unmanaged/unmanaged-generic2.chpl
  test/classes/delete-free/unmanaged/unmanaged-generic2.future
  test/classes/delete-free/unmanaged/unmanaged-generic2.good
Labels: area: Tests

#9583 Add future demonstrating issue with queries when unmanaged is involved
  test/classes/delete-free/unmanaged/queryGenericComponents.bad
  test/classes/delete-free/unmanaged/queryGenericComponents.chpl
  test/classes/delete-free/unmanaged/queryGenericComponents.future
  test/classes/delete-free/unmanaged/queryGenericComponents.good
Labels: area: Tests

#9595 Add a future tracking library compilation's failure to handle file name hyphens
  test/compflags/lydia/library/hyphenated-name.chpl
  test/compflags/lydia/library/hyphenated-name.cleanfiles
  test/compflags/lydia/library/hyphenated-name.compopts
  test/compflags/lydia/library/hyphenated-name.future
  test/compflags/lydia/library/hyphenated-name.good
  test/compflags/lydia/library/hyphenated-name.noexec
Labels: area: Tests

#9566 Fix for createRandomBuffer duplicate names
  modules/packages/Crypto.chpl
Labels: stat: Waiting on Contributor

#9608 Update skipif to enforce fifo tasking, at Nikhil's recommendation
  test/users/npadmana/mpi/test_mpi.skipif
Labels: area: Tests
