Repository chapel-lang/chapel, pull requests merged in 2018-02, with the labels that each got.

#8476 Make it easier to run valgrind testing
  util/start_test
  util/test/paratest.server
Labels: stat: Ready to Merge

#8473 Enable default initializers on records
  compiler/AST/AggregateType.cpp
  compiler/AST/build.cpp
  compiler/passes/buildDefaultFunctions.cpp
  test/classes/initializers/compilerGenerated/basic_check_record.chpl
  test/classes/initializers/compilerGenerated/basic_check_record.good
  test/classes/initializers/compilerGenerated/generics_check_record.chpl
  test/classes/initializers/compilerGenerated/generics_check_record.good
  test/classes/initializers/compilerGenerated/namedArgs.chpl
  test/classes/initializers/compilerGenerated/namedArgs.good
  test/classes/initializers/compilerGenerated/pragmaOnly/basic_check_record.bad
  test/classes/initializers/compilerGenerated/pragmaOnly/basic_check_record.future
  test/classes/initializers/compilerGenerated/pragmaOnly/noOtherSyms.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review, stat: Needs Testing

#8432 Link in libmvec.a when necessary
  compiler/util/files.cpp
  make/compiler/Makefile.cray-prgenv-gnu
  make/compiler/Makefile.gnu
  runtime/etc/Makefile.exe
  runtime/etc/Makefile.include
  runtime/etc/Makefile.shared
Labels: area: Makefiles

#8528 Ignore default initializers for iterator records and classes
  compiler/AST/AggregateType.cpp
Labels: area: Compiler, stat: Needs Code Review, stat: Needs Testing

#8551 Fix failure with default initializers with record fields that utilize initializers
  compiler/AST/AggregateType.cpp
  compiler/passes/initializerRules.cpp
  test/classes/initializers/compilerGenerated/classHoldsRecordDefaultArg.chpl
  test/classes/initializers/compilerGenerated/classHoldsRecordDefaultArg.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#8560 Improve core counting for ARM systems
  runtime/src/chplsys.c
  util/chplenv/chpl_platform.py
Labels: area: Runtime

#8563 Fix error with enum casts for enums w/ nontrivial int expressions
  compiler/passes/buildDefaultFunctions.cpp
  test/types/enum/typed-offset.bad
  test/types/enum/typed-offset.future
  test/types/enum/typed-offset2.chpl
  test/types/enum/typed-offset2.good
Labels: stat: Needs Code Review, stat: Needs Testing

#8573 Improve error normalization
  compiler/AST/wellknown.cpp
  compiler/include/errorHandling.h
  compiler/include/lowerTryExprs.h
  compiler/include/wellknown.h
  compiler/passes/Makefile.share
  compiler/passes/errorHandling.cpp
  compiler/passes/normalize.cpp
  compiler/passes/normalizeErrors.cpp
Labels: stat: Ready to Merge

#8579 Fix think-o in testArgMapping
  compiler/resolution/functionResolution.cpp
Labels: stat: Needs Code Review

#8598 Fix handling of default value of argument with record type (with initializers)
  compiler/resolution/functionResolution.cpp
  test/classes/initializers/compilerGenerated/defaultValueClassArg.chpl
  test/classes/initializers/compilerGenerated/defaultValueClassArg.good
  test/classes/initializers/compilerGenerated/innerClassField.chpl
  test/classes/initializers/compilerGenerated/innerClassField.good
  test/classes/initializers/compilerGenerated/innerRecord.chpl
  test/classes/initializers/compilerGenerated/innerRecord.good
  test/classes/initializers/generics/defaultValueClassArg-regularProc.chpl
  test/classes/initializers/generics/defaultValueClassArg-regularProc.good
  test/classes/initializers/generics/defaultValueClassArg.chpl
  test/classes/initializers/generics/defaultValueClassArg.good
  test/classes/initializers/records/defaultValueRecordArg-regularProc.chpl
  test/classes/initializers/records/defaultValueRecordArg-regularProc.good
  test/classes/initializers/records/defaultValueRecordArg.chpl
  test/classes/initializers/records/defaultValueRecordArg.good
  test/classes/initializers/records/generics/defaultValueRecordArg-explicitInstance.chpl
  test/classes/initializers/records/generics/defaultValueRecordArg-explicitInstance.good
  test/classes/initializers/records/generics/defaultValueRecordArg-regularProc.chpl
  test/classes/initializers/records/generics/defaultValueRecordArg-regularProc.good
  test/classes/initializers/records/generics/defaultValueRecordArg.chpl
  test/classes/initializers/records/generics/defaultValueRecordArg.good
Labels: area: Compiler, area: Tests

#8605 More verbose core counting documentation
  runtime/src/chplsys.c
Labels: area: Runtime

#8581 Add comparison operators for astloc
  compiler/include/baseAST.h
Labels: stat: Needs Code Review

#8616 Implement error messages for bad config file entries
  runtime/src/config.c
  test/execflags/configFile/configFileAmbiguousVar.cfg
  test/execflags/configFile/configFileAmbiguousVar.chpl
  test/execflags/configFile/configFileAmbiguousVar.execopts
  test/execflags/configFile/configFileAmbiguousVar.good
  test/execflags/configFile/configFileBadName.2.cfg
  test/execflags/configFile/configFileBadName.2.good
  test/execflags/configFile/configFileBadName.cfg
  test/execflags/configFile/configFileBadName.chpl
  test/execflags/configFile/configFileBadName.execopts
  test/execflags/configFile/configFileBadName.good
  test/execflags/configFile/configFileErrorLineno.bad
  test/execflags/configFile/configFileErrorLineno.cfg
  test/execflags/configFile/configFileErrorLineno.chpl
  test/execflags/configFile/configFileErrorLineno.execopts
  test/execflags/configFile/configFileErrorLineno.future
  test/execflags/configFile/configFileErrorLineno.good
Labels: stat: Needs Code Review
