Repository chapel-lang/chapel, pull requests merged in 2018-03, with the labels that each got.

#8731 Add a future covering the bad error message for recursion and arguments
  test/functions/lydia/infinite-recursion-arg.bad
  test/functions/lydia/infinite-recursion-arg.chpl
  test/functions/lydia/infinite-recursion-arg.future
  test/functions/lydia/infinite-recursion-arg.good
Labels: area: Tests

#8747 Make gsl_demo compopts conditional on GSL_DIR
  test/users/npadmana/gsl_demonstration/gsl_demo.compopts
Labels: area: Tests

#8595 add commonPath to Path.chpl
  modules/standard/Path.chpl
  test/library/standard/Path/prithvi-unnati/commonPath/testCommonPathArray.chpl
  test/library/standard/Path/prithvi-unnati/commonPath/testCommonPathArray.good
  test/library/standard/Path/prithvi-unnati/commonPath/testCommonPathStringArguments.chpl
  test/library/standard/Path/prithvi-unnati/commonPath/testCommonPathStringArguments.good
Labels: area: Modules, area: Tests

#8762 Add six tests of records and initializers with arrays
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs-allDefault.chpl
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs-allDefault.future
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs-allDefault.good
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs-defaultStored.chpl
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs-defaultStored.good
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs.chpl
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs.good
  test/classes/initializers/records/arrayArgOrdinaryFunction.chpl
  test/classes/initializers/records/arrayArgOrdinaryFunction.good
  test/classes/initializers/records/arrayOfOtherRecs-explicitAll.chpl
  test/classes/initializers/records/arrayOfOtherRecs-explicitAll.good
  test/classes/initializers/records/arrayOfOtherRecs-implicitType.chpl
  test/classes/initializers/records/arrayOfOtherRecs-implicitType.future
  test/classes/initializers/records/arrayOfOtherRecs-implicitType.good
Labels: area: Tests, stat: Needs Testing

#8789 Warn only if compopts file is empty, not if executable compopts ouput empty
  util/test/sub_test
Labels: area: BTR

#8800 Extend checking of JIRA 329 (fatal MPP reservation) to handle more
  util/test/sub_test
Labels: area: BTR, stat: Needs Code Review

#8576 Let push_back/push_front use in intent
  modules/internal/ChapelArray.chpl
  test/classes/delete-free/push-back-owned.chpl
  test/classes/delete-free/push-back-owned.good
Labels: stat: Ready to Merge

#8696 Port Chapel to LLVM 6
  compiler/include/codegen.h
  compiler/include/misc.h
  compiler/util/clangUtil.cpp
  compiler/util/llvmExtractIR.cpp
  runtime/src/comm/ugni/comm-ugni.c
  test/llvmDebug/llvmDebug_test.py
  third-party/llvm/Makefile
  third-party/llvm/unpack-llvm.sh
Labels: area: Compiler, area: Third-Party

#8816 Add skipif for time-write performance test with launcher
  test/io/vass/time-write.skipif
Labels: area: Tests, stat: Needs Code Review

#8818 Allow Phase 1 of initialization to contain if statements with field init and no else branch
  compiler/include/InitNormalize.h
  compiler/passes/InitNormalize.cpp
  compiler/passes/initializerRules.cpp
  test/classes/initializers/cond-only-then-2.good
  test/classes/initializers/generics/phase1/hasIfImplicit.chpl
  test/classes/initializers/generics/phase1/hasIfImplicit.future
  test/classes/initializers/generics/phase1/hasIfImplicit.good
  test/classes/initializers/generics/phase1/hasLoopBad.good
  test/classes/initializers/parentCall/inLoop.good
  test/classes/initializers/phase1/hasIfImplicit.chpl
  test/classes/initializers/phase1/hasIfImplicit.good
  test/classes/initializers/phase1/hasLoopBad.good
  test/classes/initializers/siblingCall/loopSiblingCall.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review, stat: Needs Testing

#8828 Add support for if/else branches ending with different field inits
  compiler/passes/initializerRules.cpp
  test/classes/initializers/cond-only-else-2.chpl
  test/classes/initializers/cond-only-else-2.good
  test/classes/initializers/cond-only-then-3.chpl
  test/classes/initializers/cond-only-then-3.good
  test/classes/initializers/phase1/hasIfDiffEndField-notLast.chpl
  test/classes/initializers/phase1/hasIfDiffEndField-notLast.good
  test/classes/initializers/phase1/hasIfDiffEndField.chpl
  test/classes/initializers/phase1/hasIfDiffEndField.good
  test/classes/initializers/phase1/hasIfDiffEndField2-notLast.chpl
  test/classes/initializers/phase1/hasIfDiffEndField2-notLast.good
  test/classes/initializers/phase1/hasIfDiffEndField2.chpl
  test/classes/initializers/phase1/hasIfDiffEndField2.good
  test/classes/initializers/phase1/hasIfSameFieldDiffPrior.chpl
  test/classes/initializers/phase1/hasIfSameFieldDiffPrior.good
Labels: area: Compiler, area: Tests

#8791 Add support for Owned,Shared -> class coercions
  compiler/AST/type.cpp
  compiler/include/flags_list.h
  compiler/include/type.h
  compiler/passes/buildDefaultFunctions.cpp
  compiler/passes/normalize.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/wrappers.cpp
  modules/internal/ChapelBase.chpl
  modules/packages/OwnedObject.chpl
  modules/packages/SharedObject.chpl
  test/classes/delete-free/coercions-covariant.bad
  test/classes/delete-free/coercions-covariant.chpl
  test/classes/delete-free/coercions-covariant.future
  test/classes/delete-free/coercions-covariant.good
  test/classes/delete-free/coercions-generic.chpl
  test/classes/delete-free/coercions-generic.good
  test/classes/delete-free/coercions.chpl
  test/classes/delete-free/coercions.good
  test/classes/delete-free/owned-ref-borrow-explicit.chpl
  test/classes/delete-free/owned-ref-borrow-explicit.good
  test/classes/delete-free/owned-ref-borrow-implicit.chpl
  test/classes/delete-free/owned-ref-borrow-implicit.good
  test/types/integral/int-coerce-arg.chpl
  test/types/integral/int-coerce-arg.good
  test/types/integral/int-coerce-var.chpl
  test/types/integral/int-coerce-var.good
  test/types/sync/ferguson/sync-coerce-to-ref.chpl
  test/types/sync/ferguson/sync-coerce-to-ref.good
Labels: stat: Needs Code Review

#8858 Add a ton of inheritance tests on interaction with default and constructors/init
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_constructor.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_constructor.good
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_default1.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_default1.good
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_default2.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_default2.good
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_default3.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_default3.good
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_initializer.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_initializer.good
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_initializer_bad.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_initializer_bad.good
  test/classes/initializers/compilerGenerated/pragmaOnly/inherits_initializer_bad.prediff
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_constructor1.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_constructor1.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_constructor2.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_constructor2.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_constructor3.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_constructor3.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default1.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default1.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default2.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default2.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default3.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default3.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default4.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default4.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default4.prediff
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default5.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default5.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default6.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default6.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default7.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_default7.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_initializer.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_initializer.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_initializer_bad.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_initializer_bad.good
  test/classes/initializers/compilerGenerated/pragmaOnly/parent_inherits_initializer_bad.prediff
  test/classes/initializers/inheritance/constructorParent.chpl
  test/classes/initializers/inheritance/constructorParent.good
  test/classes/initializers/inheritance/constructorParent.prediff
Labels: area: Tests

#8859 Add --warn-unstable developer flag, require it for return iterator error
  compiler/include/driver.h
  compiler/main/driver.cpp
  compiler/resolution/resolveFunction.cpp
  test/arrays/ferguson/semantic-examples/1-return-promoted-expr.good
  test/deprecated/returned-iterator-becomes-array-warning.compopts
  test/functions/deitz/iterators/temps/test_iterator_temp4.compopts
  test/functions/deitz/iterators/test_misc.compopts
  test/functions/iterators/ferguson/returns-for-expr.good
  test/functions/vass/passing-iterator-as-argument.compopts
  test/studies/shootout/submitted/meteor.good
  util/chpl-completion.bash
Labels: stat: Ready to Merge

#8812 Support coercion from Owned(Child) to Owned(Parent)
  compiler/passes/buildDefaultFunctions.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/wrappers.cpp
  modules/internal/ChapelBase.chpl
  modules/packages/OwnedObject.chpl
  test/classes/delete-free/coercions-covariant-const-ref.chpl
  test/classes/delete-free/coercions-covariant-const-ref.good
  test/classes/delete-free/coercions-covariant-in-const-in.chpl
  test/classes/delete-free/coercions-covariant-in-const-in.good
  test/classes/delete-free/coercions-covariant-ref.chpl
  test/classes/delete-free/coercions-covariant-ref.good
  test/classes/delete-free/coercions-covariant-varinit.chpl
  test/classes/delete-free/coercions-covariant-varinit.good
  test/classes/delete-free/coercions-covariant.bad
  test/classes/delete-free/coercions-covariant.chpl
  test/classes/delete-free/coercions-covariant.future
  test/classes/delete-free/coercions-covariant.good
  test/classes/diten/passSubClassByRef.bad
  test/classes/diten/passSubClassByRef.compopts
  test/classes/diten/passSubClassByRef.future
  test/classes/diten/passSubClassByRef.good
  test/classes/ferguson/coerce-const-ref.chpl
  test/classes/ferguson/coerce-const-ref.good
  test/classes/vass/ref-like-intents/COMPOPTS
  test/classes/vass/ref-like-intents/PREDIFF
  test/classes/vass/ref-like-intents/inout-subclass.bad
  test/classes/vass/ref-like-intents/inout-subclass.future
  test/classes/vass/ref-like-intents/inout-subclass.good
  test/classes/vass/ref-like-intents/out-subclass.bad
  test/classes/vass/ref-like-intents/out-subclass.future
  test/classes/vass/ref-like-intents/out-subclass.good
  test/classes/vass/ref-like-intents/ref-subclass.bad
  test/classes/vass/ref-like-intents/ref-subclass.future
  test/classes/vass/ref-like-intents/ref-subclass.good
  test/functions/vass/subclass-to-ref-formal.bad
  test/functions/vass/subclass-to-ref-formal.compopts
  test/functions/vass/subclass-to-ref-formal.future
  test/functions/vass/subclass-to-ref-formal.good
  test/users/ferguson/aa/class-ref-one.bad
  test/users/ferguson/aa/class-ref-one.compopts
  test/users/ferguson/aa/class-ref-one.future
  test/users/ferguson/aa/class-ref-one.good
Labels: stat: Needs Code Review

#8862 Fix segfault with inheritance and initializers/constructors, attempt 2
  compiler/AST/AggregateType.cpp
  test/classes/initializers/compilerGenerated/constructor_inherits_default.chpl
  test/classes/initializers/compilerGenerated/constructor_inherits_default.good
  test/classes/initializers/compilerGenerated/pragmaOnly/constructor_inherits_default.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/constructor_inherits_default.good
  test/classes/initializers/compilerGenerated/pragmaOnly/constructor_inherits_default_parent.chpl
  test/classes/initializers/compilerGenerated/pragmaOnly/constructor_inherits_default_parent.good
Labels: area: Compiler, area: Tests, stat: Ready to Merge

#8886 Remove comment about resolved future
  modules/internal/String.chpl
  test/types/records/ferguson/assert-locale-record/myrecord.chpl
  test/types/records/ferguson/expiring-value-alias.chpl
  test/types/records/ferguson/must-init-record/myrecord.chpl
  test/types/records/ferguson/self-pointer-record/myrecord.chpl
  test/types/records/ferguson/tracking-record/myrecord.chpl
Labels: area: Modules, area: Tests

#8894 Clean up Path documentation
  modules/standard/Path.chpl
Labels: area: Docs, area: Modules, stat: Needs Code Review

#8903 Fix typos in lifetime.cpp
  compiler/resolution/lifetime.cpp
Labels: area: Compiler

#8936 Update documentation for LLVM version and for ARM-based Cray systems
  doc/rst/platforms/cray.rst
  doc/rst/technotes/llvm.rst
  doc/rst/usingchapel/chplenv.rst
Labels: area: Docs

#8984 Fix incorrect documentation of postinit for the initializers technote
  doc/rst/technotes/initializers.rst
Labels: area: Docs, stat: Needs Design Review

#9005 Pre-release prep. Chapel 1.17.0: post-release version markings
  compiler/main/version.cpp
  compiler/main/version_num.h
  doc/rst/conf.py
  doc/util/versionButton.php
  man/confchpl.rst
  man/confchpldoc.rst
  test/compflags/bradc/printstuff/version.goodstart
  test/compflags/bradc/printstuff/versionhelp.sh
Labels: area: BTR, stat: Needs Testing, stat: Work in Progress

#9031 Update the Vagrant boxes used for portability tests
  util/devel/test/vagrant/README-distro-timelines.txt
  util/devel/test/vagrant/bento-centos-6/Vagrantfile
  util/devel/test/vagrant/bento-centos-7/Vagrantfile
  util/devel/test/vagrant/bento-debian-7/Vagrantfile
  util/devel/test/vagrant/bento-debian-8/Vagrantfile
  util/devel/test/vagrant/bento-debian-9/Vagrantfile
  util/devel/test/vagrant/bento-freebsd-11/Vagrantfile
  util/devel/test/vagrant/x_eol/bento-fedora-25/Vagrantfile
  util/devel/test/vagrant/x_eol/bento-opensuse-leap-42.2/Vagrantfile
Labels: area: BTR

#8970 Fix typo in sub_test comment on chapel testing valgrind environment variables
  util/test/sub_test
Labels: area: Tools, post-release, stat: Ready to Merge
