Repository chapel-lang/chapel, pull requests merged in 2018-04, with the labels that each got.

#8617 expandVars function added to Path library
  modules/standard/Path.chpl
  test/library/standard/Path/verma-varsha/test_expandVars.chpl
  test/library/standard/Path/verma-varsha/test_expandVars.execenv
  test/library/standard/Path/verma-varsha/test_expandVars.good
Labels: area: Modules, area: Tests, post-release, stat: Ready to Merge

#9033 Add a future for the enum array default initializer bug, and a test that works
  test/classes/initializers/compilerGenerated/enumArray.chpl
  test/classes/initializers/compilerGenerated/enumArray.future
  test/classes/initializers/compilerGenerated/enumArray.good
  test/classes/initializers/compilerGenerated/enumArray.skipif
  test/classes/initializers/records/enumArrayCopied.chpl
  test/classes/initializers/records/enumArrayCopied.good
Labels: area: Tests, post-release, stat: Ready to Merge

#8971 Add a sample performance test
  test/GRAPHFILES
  test/Samples/Performance/cleanCopy/foobar.chpl
  test/Samples/Performance/cleanCopy/foobar.execopts
  test/Samples/Performance/cleanCopy/foobar.good
  test/Samples/Performance/cleanCopy/foobar.graph
  test/Samples/Performance/cleanCopy/foobar.perfkeys
Labels: stat: Ready to Merge

#8962 Make chpl tab completion pay attention to CHPL_DEVELOPER and --[no-]devel
  util/chpl-completion.bash
  util/devel/chpl-bash-completion-template
  util/devel/gen-chpl-bash-completion
Labels: post-release

#8898 Locale model cleanup
  modules/internal/localeModels/knl/LocaleModel.chpl
  modules/internal/localeModels/numa/LocaleModel.chpl
  test/localeModels/numa/basics/bad_children.chpl
  test/localeModels/numa/basics/bad_children.good
Labels: area: Modules, post-release

#8992 Allow specifying a node list to aprun
  runtime/src/launch/aprun/aprun-utils.c
  runtime/src/launch/aprun/aprun-utils.h
  runtime/src/launch/pbs-aprun/aprun-utils.c
Labels: area: Runtime, post-release

#9004 Prevent candidate filtering from resolving signatures of incompatible initializers
  compiler/include/ResolutionCandidate.h
  compiler/resolution/ResolutionCandidate.cpp
  test/classes/initializers/compilerGenerated/arrayOfOtherRecs-allDefault.future
  test/classes/initializers/records/arrayOfOtherRecs-implicitType.future
Labels: post-release

#9018 Support dynamic dispatch on vararg methods
  compiler/AST/FnSymbol.cpp
  compiler/AST/astutil.cpp
  compiler/include/astutil.h
  compiler/resolution/virtualDispatch.cpp
  test/functions/varargs/varargOverride.chpl
  test/functions/varargs/varargOverride.good
  test/functions/varargs/varargOverrideForwarding.chpl
  test/functions/varargs/varargOverrideForwarding.good
  test/functions/varargs/varargOverrideGeneric.chpl
  test/functions/varargs/varargOverrideGeneric.good
Labels: post-release

#8926 call resolveSpecifiedReturnType only for candidates
  compiler/include/resolveFunction.h
  compiler/resolution/ResolutionCandidate.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/resolveFunction.cpp
  test/types/tuple/stonea/returnArrayTuple.future
  test/users/ferguson/resolution-bug-this-nodomain.chpl
  test/users/ferguson/resolution-bug-this-nodomain.good
  test/users/ferguson/resolution-bug-this.chpl
  test/users/ferguson/resolution-bug-this.good
  test/users/ferguson/where-filter-invalid-real.chpl
  test/users/ferguson/where-filter-invalid-real.good
  test/users/ibertolacc/specified-return-type-tuple-array.chpl
  test/users/ibertolacc/specified-return-type-tuple-array.good
  test/users/thom/returnGenericLineno/strassen.chpl
  test/users/thom/returnGenericLineno/util.good
Labels: post-release

#8958 Remove runtime type from 'this' type argument of chpl__deserialize
  compiler/optimizations/remoteValueForwarding.cpp
  compiler/resolution/functionResolution.cpp
  modules/internal/ChapelArray.chpl
Labels: post-release

#8988 Update a slew of tests with initialize() methods to use postinit() instead
  test/arrays/marybeth/CMO_array.chpl
  test/associative/bradc/localeDom/assocLocales3.chpl
  test/classes/bradc/overloadMethods/v2NoReturnValueButType.chpl
  test/classes/bradc/overloadMethods/v3aoneClassReturnMatch.chpl
  test/classes/bradc/overloadMethods/v3oneClassReturnMatch.chpl
  test/classes/bradc/overloadMethods/v4oneClassReturnNoMatch.chpl
  test/classes/bradc/overloadMethods/v5bothReturnTypes.chpl
  test/classes/deitz/class-constructor/class_construct1.chpl
  test/distributions/diten/Dimensional.chpl
  test/expressions/bradc/condExprInClassInit.chpl
  test/multilocale/bradc/needMultiLocales/writeThisUsingOn.chpl
  test/multilocale/diten/oneOrMoreLocales/1DBlockDistributedJacobi.chpl
  test/param/nelson/coercion.chpl
  test/studies/amr/lib/level/LevelVariable_def.chpl
  test/studies/hpcc/common/bradc/BradsBlock1D.chpl
  test/studies/hpcc/common/bradc/BradsBlock1DPar-deitzditen.chpl
  test/studies/hpcc/common/bradc/BradsBlock1DPar-ideal.chpl
  test/studies/hpcc/common/bradc/BradsBlock1DPar.chpl
  test/studies/madness/aniruddha/madchap/mytests/par-compress/MRA.chpl
  test/studies/madness/aniruddha/madchap/mytests/par-reconstruct/MRA.chpl
  test/studies/madness/aniruddha/madchap/mytests/par-refine/MRA.chpl
  test/studies/madness/aniruddha/madchap/recordBug/FTree.chpl
  test/studies/madness/aniruddha/madchap/recordBug/MRA.chpl
  test/studies/madness/common/FTree.chpl
  test/studies/madness/common/MRA.chpl
  test/studies/madness/dinan/mad_chapel/FTree.chpl
  test/studies/madness/dinan/mad_chapel/MRA.chpl
  test/studies/shootout/nbody/bradc/nbody-blc-ref.chpl
  test/studies/shootout/nbody/bradc/nbody-blc-slice.chpl
  test/studies/shootout/nbody/bradc/nbody-blc-zip.chpl
  test/studies/shootout/nbody/bradc/nbody-blc.chpl
  test/types/type_variables/deitz/part3/test_instantiate_construct1.chpl
  test/types/type_variables/deitz/test_call_with_type_side_effects.chpl
Labels: area: Tests, post-release, stat: Ready to Merge

#8966 Fix Shared output format, add casts for coercions
  modules/packages/SharedObject.chpl
  test/classes/delete-free/coercions-covariant-in-const-in-shared.chpl
  test/classes/delete-free/coercions-covariant-in-const-in-shared.good
Labels: post-release

#8978 Revamp the TestSystem helper document
  doc/rst/developer/bestPractices/TestSystem.rst
Labels: area: Docs, stat: Ready to Merge

#8902 chplspell dictionary updates
  util/devel/chplspell-dictionary
  util/devel/chplspell-dictionary.fileids.json
Labels: post-release

#8785 move lowering of ForallStmts to lowerIterators
  compiler/AST/ForallStmt.cpp
  compiler/AST/baseAST.cpp
  compiler/AST/foralls.cpp
  compiler/AST/iterator.cpp
  compiler/AST/symbol.cpp
  compiler/AST/view.cpp
  compiler/include/ForallStmt.h
  compiler/include/baseAST.h
  compiler/include/foralls.h
  compiler/include/implementForallIntents.h
  compiler/include/passes.h
  compiler/include/resolution.h
  compiler/include/symbol.h
  compiler/optimizations/removeUnnecessaryGotos.cpp
  compiler/passes/InitNormalize.cpp
  compiler/passes/checkResolved.cpp
  compiler/passes/createTaskFunctions.cpp
  compiler/passes/errorHandling.cpp
  compiler/passes/scopeResolve.cpp
  compiler/resolution/Makefile.share
  compiler/resolution/addAutoDestroyCalls.cpp
  compiler/resolution/callDestructors.cpp
  compiler/resolution/cullOverReferences.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/implementForallIntents.cpp
  compiler/resolution/implementForallIntents2.cpp
  compiler/resolution/loopDetails.cpp
  compiler/resolution/loopDetails.h
  compiler/resolution/lowerForalls.cpp
  compiler/resolution/lowerIterators.cpp
  compiler/resolution/preFold.cpp
  modules/standard/FileSystem.chpl
  test/functions/iterators/vass/forall-in-standalone-iterator.bad
  test/functions/iterators/vass/forall-in-standalone-iterator.chpl
  test/functions/iterators/vass/forall-in-standalone-iterator.future
  test/functions/iterators/vass/forall-in-standalone-iterator.skipif
  test/functions/iterators/vass/recursive-iterator-twice-local.chpl
  test/functions/iterators/vass/recursive-iterator-twice-local.good
  test/functions/iterators/vass/recursive-iterator-twice-local.notest
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-1.good
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-1.skipif
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-2.good
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-2.skipif
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-3.good
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-3.skipif
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-4.good
  test/parallel/forall/vass/par-loops/2-enclosing-par-loops-error-4.skipif
  test/parallel/forall/vass/reciter/forall-reciter-todo.bad
  test/parallel/forall/vass/reciter/forall-reciter-todo.chpl
  test/parallel/forall/vass/reciter/forall-reciter-todo.good
  test/parallel/forall/vass/reciter/forall-reciter-works.chpl
  test/parallel/forall/vass/reciter/forall-reciter-works.good
Labels: area: Compiler, post-release, stat: Ready to Merge

#9030 Add CHPL_INCLUDE_PATH and colon paths to CHPL_LIB_PATH, -L, and -I flags
  compiler/AST/build.cpp
  compiler/include/files.h
  compiler/main/driver.cpp
  compiler/util/files.cpp
  man/chpl.rst
  test/compflags/library/libpath.skipif
  test/compflags/library/libpath/.gitignore
  test/compflags/library/libpath/PRECOMP
  test/compflags/library/libpath/allLs.chpl
  test/compflags/library/libpath/allLs.compopts
  test/compflags/library/libpath/allLs.good
  test/compflags/library/libpath/allVar.chpl
  test/compflags/library/libpath/allVar.compenv
  test/compflags/library/libpath/allVar.good
  test/compflags/library/libpath/bar/NOTEST
  test/compflags/library/libpath/bar/bar.c
  test/compflags/library/libpath/bar/bar.h
  test/compflags/library/libpath/baz/NOTEST
  test/compflags/library/libpath/baz/baz.c
  test/compflags/library/libpath/baz/baz.h
  test/compflags/library/libpath/foo/NOTEST
  test/compflags/library/libpath/foo/foo.c
  test/compflags/library/libpath/foo/foo.h
  test/compflags/library/libpath/varsAndLs.chpl
  test/compflags/library/libpath/varsAndLs.compenv
  test/compflags/library/libpath/varsAndLs.compopts
  test/compflags/library/libpath/varsAndLs.good
  test/compflags/library/libpath/varsAndLs2.chpl
  test/compflags/library/libpath/varsAndLs2.compenv
  test/compflags/library/libpath/varsAndLs2.compopts
  test/compflags/library/libpath/varsAndLs2.good
Labels: post-release

#9078 Prevent path splitting when fixing path on fish (#9049)
  util/config/fixpath.py
Labels: stat: Ready to Merge

#9176 Fix an incorrect usage of sys_getenv()
  .gitignore
  modules/internal/LocaleModelHelpSetup.chpl
  test/localeModels/dmk/locale_name.chpl
  test/localeModels/dmk/locale_name.cleanfiles
  test/localeModels/dmk/locale_name.prediff
Labels: area: Modules, type: Bug

#9036 new owned MyClass
  compiler/AST/UnmanagedClassType.cpp
  compiler/resolution/functionResolution.cpp
  modules/Makefile
  modules/internal/ChapelStandard.chpl
  modules/internal/OwnedObject.chpl
  modules/internal/SharedObject.chpl
  test/classes/delete-free/coercions-covariant-const-ref.good
  test/classes/delete-free/coercions-covariant-ref.good
  test/classes/delete-free/owned-keyword-generic.chpl
  test/classes/delete-free/owned-keyword-generic.good
  test/classes/delete-free/owned-keyword.chpl
  test/classes/delete-free/owned-keyword.good
  test/classes/delete-free/owned-raw-ingored-record.chpl
  test/classes/delete-free/owned-raw-ingored-record.good
  test/optimizations/deadCodeElimination/elliot/countDeadModules.good
Labels: area: Compiler, post-release

#9013 Update chpl_arch.py to handle 64-bit ARM, KNL, and Skylake
  compiler/include/driver.h
  compiler/main/driver.cpp
  compiler/util/clangUtil.cpp
  make/compiler/Makefile.clang
  make/compiler/Makefile.gnu
  make/compiler/Makefile.intel
  runtime/Makefile.help
  test/compflags/link/sungeun/static_dynamic.prediff
  test/execflags/sungeun/about.prediff
  test/runtime/sungeun/chpl-env-gen.precomp
  util/chplenv/chpl_arch.py
  util/chplenv/chpl_comm_substrate.py
  util/chplenv/overrides.py
  util/chplenv/third_party_utils.py
  util/printchplenv
  util/test/chpl_launchcmd.py
  util/test/sub_test
Labels: area: Tools, post-release

#9296 Update miniMD problem size and allow performance tests to have only a .perfcompopts file
  test/release/examples/benchmarks/miniMD/miniMD.perfexecopts
  util/test/sub_test
Labels: area: BTR, area: Tests, stat: Ready to Merge

#9206 Add '--ignore-user-errors' and '--stop-after-pass' compiler flags
  compiler/include/driver.h
  compiler/main/driver.cpp
  compiler/main/runpasses.cpp
  compiler/util/misc.cpp
  util/chpl-completion.bash
Labels: stat: Ready to Merge

#9359 Fix a typo in the ZMQ documentation
  modules/packages/ZMQ.chpl
Labels: area: Docs, area: Modules, stat: Needs Code Review

#9385 Improve in intent, default arguments
  compiler/resolution/addAutoDestroyCalls.cpp
  compiler/resolution/callDestructors.cpp
  compiler/resolution/wrappers.cpp
  test/errhandling/ferguson/throws-destroys.6.good
  test/functions/ferguson/in-default-int.chpl
  test/functions/ferguson/in-default-int.good
  test/functions/ferguson/in-default-record.chpl
  test/functions/ferguson/in-default-record.good
Labels: stat: Ready to Merge

#9165 Add futures for ref and inout arguments with default values (issue #7924)
  test/functions/default-arguments/default-argument-inout.bad
  test/functions/default-arguments/default-argument-inout.chpl
  test/functions/default-arguments/default-argument-inout.future
  test/functions/default-arguments/default-argument-inout.good
  test/functions/default-arguments/default-argument-ref.bad
  test/functions/default-arguments/default-argument-ref.chpl
  test/functions/default-arguments/default-argument-ref.future
  test/functions/default-arguments/default-argument-ref.good
Labels: area: Tests, stat: Ready to Merge

#9366 Improved performance of LinearAlgebra.Sparse _array.plus()
  modules/packages/LinearAlgebra.chpl
Labels: stat: Ready to Merge

#9358 Update prereq.rst for #9102 changes
  doc/rst/usingchapel/prereqs.rst
Labels: stat: Needs Design Review

#8944 Move chplgmp.c out of runtime
  compiler/util/clangUtil.cpp
  modules/standard/GMP.chpl
  modules/standard/GMPHelper/chplgmp.h
  runtime/etc/Makefile.include
  runtime/include/chplgmp.h
  runtime/include/stdchpl.h
  runtime/include/stdchplrt.h
  runtime/make/Makefile.runtime.include
  runtime/src/Makefile.share
  runtime/src/chplgmp.c
  test/library/standard/GMP/ferguson/gmp_test.chpl
  test/library/standard/GMP/ferguson/gmp_test.execopts
  test/library/standard/GMP/ferguson/gmp_test.neg.good
  test/library/standard/GMP/ferguson/gmp_test.pos.good
  test/library/standard/GMP/ldelaney/gmp_random_2.chpl
  test/runtime/thomasvandoren/rerun_compiler_with_opposite_hwloc.bash
  test/runtime/thomasvandoren/rtLibDirWarnings.prediff
  test/runtime/thomasvandoren/rtLibDirWarningsWithDeveloper.prediff
  test/runtime/thomasvandoren/rtLibDirWarningsWithModule.prediff
  test/runtime/thomasvandoren/rtLibDirWarningsWithModuleAndDeveloper.prediff
  util/printchplenv
Labels: post-release

#9392 Fix typos
  compiler/include/UnmanagedClassType.h
  compiler/optimizations/remoteValueForwarding.cpp
  compiler/resolution/loopDetails.cpp
  compiler/resolution/lowerForalls.cpp
Labels: stat: Needs Testing
