Repository chapel-lang/chapel, pull requests merged in 2019-04, with the labels that each got.

#12804 Add suppressif for this test due to running as a windows service nightly
  test/library/standard/FileSystem/chmod/chmod_noprivilege.suppressif
Labels: area: Tests

#12835 Adjust Python scripts in Path module tests to use print() for compatibility
  test/library/standard/Path/dlongnecke/absPath/absPath.preexec
  test/library/standard/Path/dlongnecke/absPath/fileAbsPath.preexec
  test/library/standard/Path/dlongnecke/normPath/normPath.preexec
  test/library/standard/Path/relPath/fileRelPath.preexec
  test/library/standard/Path/relPath/relPath.preexec
Labels: area: Tests, easy / straightforward

#12450 Print Chapel instead of clang for llvm.ident metadata value
  compiler/llvm/clangUtil.cpp
  test/llvm/version-in-llvm-ident-ir/PREDIFF
  test/llvm/version-in-llvm-ident-ir/SKIPIF
  test/llvm/version-in-llvm-ident-ir/version-in-llvm-ir.chpl
  test/llvm/version-in-llvm-ident-ir/version-in-llvm-ir.compopts
  test/llvm/version-in-llvm-ident-ir/version-in-llvm-ir.good
Labels: stat: Needs Testing

#12852 Adjust --library-makefile to respond to overriding environment variables at compilation
  compiler/codegen/library.cpp
  test/interop/C/makefiles/Makefile
  test/interop/C/makefiles/checkEnvOverrides.chpl
  test/interop/C/makefiles/checkEnvOverrides.cleanfiles
  test/interop/C/makefiles/checkEnvOverrides.compenv
  test/interop/C/makefiles/checkEnvOverrides.compopts
  test/interop/C/makefiles/checkEnvOverrides.good
  test/interop/C/makefiles/checkEnvOverrides.noexec
  test/interop/C/makefiles/checkEnvOverrides.prediff
  test/interop/C/makefiles/checkEnvOverrides.skipif
  test/interop/C/makefiles/envOverrides.c
Labels: area: Compiler, area: Tests, area: Tools, stat: Ready to Merge

#12702 Added "Itertools" module with repeat itertool
  test/library/packages/Itertools/Itertools.chpl
  test/library/packages/Itertools/Itertools.notest
  test/library/packages/Itertools/check_Parallel_Standalone.chpl
  test/library/packages/Itertools/check_Parallel_Standalone.good
  test/library/packages/Itertools/check_Parallel_zippered.chpl
  test/library/packages/Itertools/check_Parallel_zippered.good
  test/library/packages/Itertools/check_Serial.chpl
  test/library/packages/Itertools/check_Serial.good
  test/library/packages/Itertools/check_infinite_halt.chpl
  test/library/packages/Itertools/check_infinite_halt.good
Labels: stat: Ready to Merge

#12747 Make the --dynamic flag create a shared library when CHPL_LLVM=llvm
  compiler/llvm/clangUtil.cpp
  test/interop/C/llvm/makefiles/dynamicLinking/.gitignore
  test/interop/C/llvm/makefiles/dynamicLinking/CLEANFILES
  test/interop/C/llvm/makefiles/dynamicLinking/EXECENV
  test/interop/C/llvm/makefiles/dynamicLinking/FooLibrary.chpl
  test/interop/C/llvm/makefiles/dynamicLinking/FooLibrary.notest
  test/interop/C/llvm/makefiles/dynamicLinking/PRECOMP
  test/interop/C/llvm/makefiles/dynamicLinking/SKIPIF
  test/interop/C/llvm/makefiles/dynamicLinking/useSharedLibFromC.compopts
  test/interop/C/llvm/makefiles/dynamicLinking/useSharedLibFromC.good
  test/interop/C/llvm/makefiles/dynamicLinking/useSharedLibFromC.test.c
Labels: area: Compiler, type: Unimplemented Feature

#12430 Fix INT_ASSERTs that should be INT_FATAL
  compiler/passes/normalize.cpp
  compiler/resolution/cullOverReferences.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/preFold.cpp
Labels: stat: Ready to Merge

#12701 Update getCurInstantiation to compare param values when types do not match
  compiler/AST/AggregateType.cpp
  test/types/records/bharshbarger/coercedImmediate.chpl
  test/types/records/bharshbarger/coercedImmediate.good
Labels: stat: cla signed

#12862 File a bug future showing that opaque arrays are lossy when resized
  test/arrays/opaque/resizeLossy.bad
  test/arrays/opaque/resizeLossy.chpl
  test/arrays/opaque/resizeLossy.future
  test/arrays/opaque/resizeLossy.good
Labels: area: Libraries / Modules, type: Bug

#12606 added signbit in chpl
  modules/standard/Math.chpl
  runtime/include/chplmath.h
  test/library/standard/Math/signbit.chpl
  test/library/standard/Math/signbit.good
Labels: stat: Ready to Merge

#12591 Fix issue when file.check() succeeds when file is closed.
  modules/standard/IO.chpl
  runtime/include/qio/qio.h
  test/io/dtjong/file-close-check.chpl
  test/io/dtjong/file-close-check.good
Labels: stat: Waiting on Contributor

#12893 Draft version of multi-locale library support
  compiler/codegen/Makefile.share
  compiler/codegen/codegen.cpp
  compiler/codegen/mli.cpp
  compiler/include/driver.h
  compiler/include/files.h
  compiler/include/mli.h
  compiler/main/driver.cpp
  compiler/passes/buildDefaultFunctions.cpp
  compiler/util/files.cpp
  runtime/etc/Makefile.mli-static
  runtime/etc/mli/mli_client_runtime.c
  runtime/etc/mli/mli_common_code.c
  runtime/etc/mli/mli_server_runtime.c
Labels: stat: Needs Code Review
