Repository chapel-lang/chapel, pull requests merged in 2019-02, with the labels that each got.

#12283 Copy directory-wide skipif for parent directory to this new one
  test/extern/ferguson/externblock/multi-module/SKIPIF
Labels: area: Tests

#12243 Add a new subclass between BaseArr and most of its children to resolve a leak
  modules/dists/HashedDist.chpl
  modules/dists/ReplicatedDist.chpl
  modules/internal/ArrayViewRankChange.chpl
  modules/internal/ArrayViewReindex.chpl
  modules/internal/ArrayViewSlice.chpl
  modules/internal/ChapelDistribution.chpl
  modules/internal/DefaultAssociative.chpl
  modules/internal/DefaultOpaque.chpl
  test/interop/C/exportArray/wrapArrayOfArrayAsOpaque.good
  test/interop/C/exportArray/wrapArrayOfArrayAsOpaque.skipif
Labels: area: Libraries / Modules, area: Tests, stat: Needs Code Review, stat: Needs Design Review

#12334 Add a future to track 12333, can't use modules with hyphens
  test/statements/lydia/hyphenated-module.chpl
  test/statements/lydia/hyphenated-module.notest
  test/statements/lydia/use-hyphenated.bad
  test/statements/lydia/use-hyphenated.chpl
  test/statements/lydia/use-hyphenated.future
  test/statements/lydia/use-hyphenated.good
Labels: area: Tests

#12332 Convert internal compiler error with partially queried domain into a user error
  compiler/passes/normalize.cpp
  test/domains/compilerErrors/partialQueriedDomain-inIntent.chpl
  test/domains/compilerErrors/partialQueriedDomain-inIntent.good
  test/domains/compilerErrors/partialQueriedDomain-multiple.chpl
  test/domains/compilerErrors/partialQueriedDomain-multiple.good
  test/domains/compilerErrors/partialQueriedDomain.chpl
  test/domains/compilerErrors/partialQueriedDomain.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#12374 Add Path.normPath and associated tests
  .gitignore
  modules/standard/Path.chpl
  test/library/standard/Path/dlongnecke/normPath/normPath.chpl
  test/library/standard/Path/dlongnecke/normPath/normPath.preexec
Labels: area: Libraries / Modules, area: Tests, easy / straightforward, stat: Needs Code Review

#12367 Add bounds check to Random getNext
  modules/standard/Random.chpl
  test/library/standard/Random/RandomStreamInterface/choiceTest.chpl
  test/library/standard/Random/RandomStreamInterface/choiceTest.compopts
  test/library/standard/Random/RandomStreamInterface/choiceTest.good
  test/library/standard/Random/RandomStreamInterface/choiceTestErrors.chpl
  test/library/standard/Random/RandomStreamInterface/choiceTestErrors.compopts
  test/library/standard/Random/RandomStreamInterface/choiceTestErrors.good
  test/library/standard/Random/RandomStreamInterface/getNextTestHalts.chpl
  test/library/standard/Random/RandomStreamInterface/getNextTestHalts.good
  test/library/standard/Random/RandomStreamInterface/getNextTestHalts.suppressif
Labels: stat: Ready to Merge

#12386 Enable param real operations
  compiler/AST/symbol.cpp
  compiler/AST/type.cpp
  compiler/codegen/codegen.cpp
  compiler/codegen/expr.cpp
  compiler/codegen/symbol.cpp
  compiler/ifa/cast_code.cpp
  compiler/ifa/num.cpp
  compiler/ifa/num.h
  compiler/include/codegen.h
  compiler/include/symbol.h
  compiler/include/type.h
  compiler/passes/ResolveScope.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/preFold.cpp
  modules/internal/ChapelBase.chpl
  modules/standard/Math.chpl
  runtime/include/chpltypes.h
  test/arrays/promotion/complex_downcast.bad
  test/arrays/promotion/complex_downcast.future
  test/functions/diten/param_int_to_complex.good
  test/functions/diten/param_int_to_real.good
  test/functions/diten/param_real_to_string.good
  test/param/errors/checkParamTypes-nofloat32.good
  test/param/errors/checkParamTypes.compopts
  test/param/ferguson/param-complex-ops.chpl
  test/param/ferguson/param-complex-ops.good
  test/param/ferguson/param-complex.chpl
  test/param/ferguson/param-complex.good
  test/param/ferguson/param-imag-mult-divide.chpl
  test/param/ferguson/param-imag-mult-divide.good
  test/param/ferguson/param-inf.chpl
  test/param/ferguson/param-inf.good
  test/param/ferguson/param-r32-three-ways.chpl
  test/param/ferguson/param-r32-three-ways.good
  test/param/ferguson/param-real-imag-ops.chpl
  test/param/ferguson/param-real-imag-ops.compopts
  test/param/ferguson/param-real-imag-ops.good
  test/param/ferguson/params-to-string.chpl
  test/param/ferguson/params-to-string.good
  test/param/ferguson/real-64-32-value-type-methods.chpl
  test/param/ferguson/real-64-32-value-type-methods.good
  test/param/ferguson/signed-zeros.chpl
  test/param/ferguson/signed-zeros.good
  test/trivial/deitz/coerce-assign/coerce_param.good
Labels: stat: Ready to Merge
