Repository chapel-lang/chapel, pull requests merged in 2019-06, with the labels that each got.

#13170 Performance Tests of `owned` and `shared` overheads over `unmanaged`
  test/GRAPHFILES
  test/memory/lifetime/allocation.chpl
  test/memory/lifetime/allocation.execopts
  test/memory/lifetime/allocation.good
  test/memory/lifetime/allocation.graph
  test/memory/lifetime/allocation.perfkeys
Labels: stat: cla signed

#13079 Implement reading of associative domains
  modules/internal/DefaultAssociative.chpl
  test/io/ferguson/assoc-domains.chpl
  test/io/ferguson/assoc-domains.good
Labels: stat: Ready to Merge

#13187 Add isNilableClass / isNonNilableClass
  compiler/AST/primitive.cpp
  compiler/include/primitive_list.h
  compiler/optimizations/optimizeOnClauses.cpp
  compiler/resolution/preFold.cpp
  modules/internal/ChapelBase.chpl
  modules/internal/OwnedObject.chpl
  modules/internal/SharedObject.chpl
  modules/standard/Types.chpl
  test/classes/nilability/is-nilable.chpl
  test/classes/nilability/is-nilable.good
Labels: stat: Ready to Merge

#13194 Tidy log2/logBasePow2 for int/uint
  modules/standard/Math.chpl
  test/library/standard/Math/log-ints.chpl
  test/library/standard/Math/log-ints.good
Labels: stat: Ready to Merge

#12869 TOML Parser: Added 'time' support
  modules/packages/TOML.chpl
  test/library/packages/TOML/test/time.chpl
  test/library/packages/TOML/test/time.good
Labels: stat: Ready to Merge, stat: cla signed

#13173 Implementation of list as a replacement for "array-as-vec" operations
  modules/Makefile
  modules/standard/Lists.chpl
  test/library/standard/Lists/append/COMPOPTS
  test/library/standard/Lists/append/listAppend.chpl
  test/library/standard/Lists/append/listAppend.good
  test/library/standard/Lists/assignment/listAssignment.chpl
  test/library/standard/Lists/assignment/listAssignment.good
  test/library/standard/Lists/clear/listClear.chpl
  test/library/standard/Lists/clear/listClear.good
  test/library/standard/Lists/count/listCount.chpl
  test/library/standard/Lists/count/listCount.good
  test/library/standard/Lists/destructors/listDestructors.chpl
  test/library/standard/Lists/destructors/listDestructors.notest
  test/library/standard/Lists/embedLists/listEmbedLists.chpl
  test/library/standard/Lists/embedLists/listEmbedLists.good
  test/library/standard/Lists/equality/listEquality.chpl
  test/library/standard/Lists/equality/listEquality.good
  test/library/standard/Lists/extend/COMPOPTS
  test/library/standard/Lists/extend/listExtendArray.chpl
  test/library/standard/Lists/extend/listExtendArray.good
  test/library/standard/Lists/extend/listExtendList.chpl
  test/library/standard/Lists/extend/listExtendList.good
  test/library/standard/Lists/indexOf/listIndexOf.chpl
  test/library/standard/Lists/indexOf/listIndexOf.good
  test/library/standard/Lists/init/COMPOPTS
  test/library/standard/Lists/init/listInit.chpl
  test/library/standard/Lists/init/listInit.good
  test/library/standard/Lists/insert/listInsert.chpl
  test/library/standard/Lists/insert/listInsert.good
  test/library/standard/Lists/isEmpty/listIsEmpty.chpl
  test/library/standard/Lists/isEmpty/listIsEmpty.good
  test/library/standard/Lists/pop/listPop.chpl
  test/library/standard/Lists/pop/listPop.good
  test/library/standard/Lists/remove/listRemove.chpl
  test/library/standard/Lists/remove/listRemove.good
  test/library/standard/Lists/sort/listSort.chpl
  test/library/standard/Lists/sort/listSort.good
  test/library/standard/Lists/this/listThis.chpl
  test/library/standard/Lists/this/listThis.good
  test/library/standard/Lists/toArray/listToArray.chpl
  test/library/standard/Lists/toArray/listToArray.good
Labels: area: Libraries / Modules, stat: Needs Code Review, stat: Work in Progress

#13244 Syntax error fixes in `chpldoc` Documentation
  doc/rst/tools/chpldoc/chpldoc.rst
Labels: stat: cla signed

#13240 Resolve barrier mismatch error for multilocale libraries run with more than one locale
  compiler/passes/buildDefaultFunctions.cpp
  modules/internal/ChapelUtil.chpl
  runtime/Makefile.help
  runtime/etc/Makefile.mli-shared
  runtime/etc/Makefile.mli-static
  runtime/etc/src/mli/server_runtime.c
  runtime/src/Makefile.share
  runtime/src/arg.c
  runtime/src/main.c
  runtime/src/main_mli.c
  test/interop/python/multilocale/checkMultipleLocales.chpl
  test/interop/python/multilocale/checkMultipleLocales.good
  test/interop/python/multilocale/checkMultipleLocales.noexec
  test/interop/python/multilocale/checkMultipleLocales.prediff
  test/interop/python/multilocale/use_checkMultipleLocales.py
Labels: area: Compiler, area: Makefiles, area: Runtime, area: Tools

#13298 GSoC 2019: Update in .bad files of Unit Test Framework
  test/library/packages/UnitTest/AssertEqual/EqualLinkedList.bad
  test/library/packages/UnitTest/AssertEqual/EqualLinkedList.chpl
  test/library/packages/UnitTest/AssertEqual/EqualLinkedList.future
  test/library/packages/UnitTest/AssertGreater/UnEqualRangeGreater.bad
  test/library/packages/UnitTest/EqualLinkedList.bad
Labels: stat: cla signed

#12919 Added the cycle itertool to Itertools.chpl
  test/library/packages/Itertools/Itertools.chpl
  test/library/packages/Itertools/cycle/COMPOPTS
  test/library/packages/Itertools/cycle/check_indexable.chpl
  test/library/packages/Itertools/cycle/check_indexable.good
  test/library/packages/Itertools/cycle/check_non_indexable.chpl
  test/library/packages/Itertools/cycle/check_non_indexable.good
  test/library/packages/Itertools/cycle/check_non_zippered.chpl
  test/library/packages/Itertools/cycle/check_non_zippered.good
  test/library/packages/Itertools/repeat/COMPOPTS
  test/library/packages/Itertools/repeat/check_Parallel_Standalone.chpl
  test/library/packages/Itertools/repeat/check_Parallel_Standalone.good
  test/library/packages/Itertools/repeat/check_Parallel_zippered.chpl
  test/library/packages/Itertools/repeat/check_Parallel_zippered.good
  test/library/packages/Itertools/repeat/check_Serial.chpl
  test/library/packages/Itertools/repeat/check_Serial.good
  test/library/packages/Itertools/repeat/check_infinite_halt.chpl
  test/library/packages/Itertools/repeat/check_infinite_halt.good
Labels: stat: cla signed
