Repository chapel-lang/chapel, pull requests merged in 2019-09, with the labels that each got.

#13944 Tackles additional intents error messages for library compilation
  compiler/codegen/library.cpp
  compiler/codegen/mli.cpp
  compiler/include/library.h
  compiler/resolution/fixupExports.cpp
  test/interop/C/exportString/badFormalIntent.good
  test/interop/C/multilocale/arrays/exportFuncWithArrayArg.chpl
  test/interop/C/multilocale/cstringArgAndReturn.chpl
  test/interop/C/multilocale/exportString/badFormalIntent.good
  test/interop/C/multilocale/multipleArgs.chpl
  test/interop/python/chapelStrings/stringArgAndReturn.chpl
  test/interop/python/defaultValues.chpl
  test/interop/python/errorMessages/badFormalIntent-array.chpl
  test/interop/python/errorMessages/badFormalIntent-array.good
  test/interop/python/errorMessages/badFormalIntent-array.skipif
  test/interop/python/errorMessages/badFormalIntent-cstring.chpl
  test/interop/python/errorMessages/badFormalIntent-cstring.comm-none.good
  test/interop/python/errorMessages/badFormalIntent-cstring.good
  test/interop/python/errorMessages/badFormalIntent.chpl
  test/interop/python/errorMessages/badFormalIntent.comm-none.good
  test/interop/python/errorMessages/badFormalIntent.good
  test/interop/python/intArrays.chpl
  test/interop/python/multilocale/defaultValues.chpl
  test/interop/python/multilocale/stringFunctions.chpl
  test/interop/python/realArrays.chpl
  test/interop/python/stringAllocated.chpl
  test/interop/python/stringFunctions.chpl
Labels: area: Compiler, area: Tests

#14024 Add two new tests to check behavior of using globals in multilocale libraries
  test/interop/C/multilocale/globals/.gitignore
  test/interop/C/multilocale/globals/CLEANFILES
  test/interop/C/multilocale/globals/PRECOMP
  test/interop/C/multilocale/globals/reliesOnGlobal.chpl
  test/interop/C/multilocale/globals/reliesOnGlobal.notest
  test/interop/C/multilocale/globals/use_reliesOnGlobal-library-init.good
  test/interop/C/multilocale/globals/use_reliesOnGlobal-library-init.lastcompopts
  test/interop/C/multilocale/globals/use_reliesOnGlobal-library-init.ml-test.c
  test/interop/C/multilocale/globals/use_reliesOnGlobal.good
  test/interop/C/multilocale/globals/use_reliesOnGlobal.lastcompopts
  test/interop/C/multilocale/globals/use_reliesOnGlobal.ml-test.c
Labels: area: Tests

#14020 Fix mason test to handle UnitTest- and exitcode-based tests
  test/library/packages/UnitTest/Launcher_Test.prediff
  test/library/packages/UnitTest/launcher_Test.WithModule.good
  test/library/packages/UnitTest/launcher_Test.dependency.good
  test/library/packages/UnitTest/launcher_Test.fail.good
  test/library/packages/UnitTest/launcher_Test.folder.good
  test/library/packages/UnitTest/launcher_Test.folderok.good
  test/library/packages/UnitTest/launcher_Test.halt.good
  test/library/packages/UnitTest/launcher_Test.numLocales.comm-none.good
  test/library/packages/UnitTest/launcher_Test.numLocales.good
  test/library/packages/UnitTest/launcher_Test.skipfile.good
  test/mason/mason-test/mason-test.good
  test/mason/mason-test/mason-test.prediff
  tools/mason/MasonTest.chpl
  tools/mason/TestResult.chpl
Labels: stat: cla signed

#14035 Update spec for private/public use statements
  spec/Statements.tex
Labels: area: Docs, stat: Needs Code Review

#14044 Add suppressif for tests that fail with gasnet+quickstart testing on linux
  test/interop/C/multilocale/globals/use_reliesOnGlobal-library-init.suppressif
  test/interop/C/multilocale/globals/use_reliesOnGlobal.suppressif
Labels: area: Tests, stat: Needs Testing

#14023 Update --library documentation for changes with this release
  doc/rst/technotes/libraries.rst
Labels: area: Docs, stat: Needs Code Review

#14054 Update TestSystem.rst for multilocale C tests
  doc/rst/developer/bestPractices/TestSystem.rst
Labels: area: Docs, stat: Needs Code Review

#14051 Handles multiple files having same name but in different directories in `mason test`
  modules/packages/UnitTest.chpl
  test/library/packages/UnitTest/launcher_Test.WithModule.good
  test/library/packages/UnitTest/launcher_Test.dependency.good
  test/library/packages/UnitTest/launcher_Test.fail.good
  test/library/packages/UnitTest/launcher_Test.folder.good
  test/library/packages/UnitTest/launcher_Test.folderok.good
  test/library/packages/UnitTest/launcher_Test.halt.good
  test/library/packages/UnitTest/launcher_Test.numLocales.comm-none.good
  test/library/packages/UnitTest/launcher_Test.numLocales.good
  test/library/packages/UnitTest/launcher_Test.skipfile.good
  test/mason/mason-test/mason-test.good
  tools/mason/MasonTest.chpl
  tools/mason/MasonUtils.chpl
  tools/mason/TestResult.chpl
Labels: stat: cla signed

#14074 Update modules primer for private use statements
  test/release/examples/primers/modules.chpl
Labels: area: Docs, area: Tests, stat: Needs Code Review

#14079 Add more deletes in tests
  test/chplvis/benchmarks-hpcc/hpl-vdb.chpl
  test/distributions/dm/s9.chpl
  test/distributions/dm/t1.chpl
  test/distributions/dm/t2.chpl
  test/distributions/dm/t5a.chpl
  test/studies/hpcc/HPL/vass/bc.dim.chpl
  test/studies/hpcc/HPL/vass/bc.md.chpl
  test/studies/hpcc/HPL/vass/bl.dim.chpl
  test/studies/hpcc/HPL/vass/bl.md.chpl
  test/studies/hpcc/HPL/vass/hpl.chpl
Labels: post-release

#14135 Update Dockerfiles and README for Chapel Release 1.20.0: Release Branch Only
  util/dockerfiles/Dockerfile
  util/dockerfiles/README.md
  util/dockerfiles/gasnet/Dockerfile
Labels: stat: cla required

#14100 Elminate multi-locale leaks in DimensionalDist2D
  modules/dists/DimensionalDist2D.chpl
  modules/dists/dims/BlockCycDim.chpl
  modules/dists/dims/BlockDim.chpl
  modules/dists/dims/ReplicatedDim.chpl
  test/chplvis/benchmarks-hpcc/hpl-vdb.chpl
  test/distributions/dm/s7.chpl
  test/distributions/dm/s8.chpl
  test/distributions/dm/s9.chpl
  test/distributions/dm/t1.chpl
  test/distributions/dm/t1.comm-none.good
  test/distributions/dm/t1.good
  test/distributions/dm/t2.chpl
  test/distributions/dm/t3.chpl
  test/distributions/dm/t5a.chpl
  test/distributions/dm/t8.chpl
  test/distributions/dm/t9.chpl
  test/distributions/dm/t9.comm-none.good
  test/distributions/dm/t9.good
  test/io/vass/writeThis-on.chpl
  test/release/examples/benchmarks/hpcc/hpl.chpl
  test/release/examples/primers/distributions.chpl
  test/studies/hpcc/HPL/vass/bc.dim.chpl
  test/studies/hpcc/HPL/vass/bc.md.chpl
  test/studies/hpcc/HPL/vass/bl.dim.chpl
  test/studies/hpcc/HPL/vass/bl.md.chpl
  test/studies/hpcc/HPL/vass/bug.chpl
  test/studies/hpcc/HPL/vass/hpl.chpl
  test/studies/hpcc/HPL/vass/hpl.performance.chpl
  test/studies/hpcc/HPL/vass/schurComplement.chpl
Labels: post-release

#14125 Document multilocale performance and commcount testing
  doc/rst/developer/bestPractices/TestSystem.rst
Labels: post-release

#14088 Add debugging output to mli marshalling routines about sizes
  compiler/codegen/mli.cpp
Labels: area: Compiler, stat: Ready to Merge

#14119 Update future for using file level modules with hyphenated names after old discussion
  test/statements/lydia/use-hyphenated.future
  test/statements/lydia/use-hyphenated.good
Labels: area: Tests, post-release, stat: Ready to Merge

#14075 Make modules declared in functions be a user facing error
  compiler/AST/ModuleSymbol.cpp
  test/modules/lydia/inFunc.chpl
  test/modules/lydia/inFunc.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#14112 Improve assignment from a sparse domain to an empty one of same type
  modules/internal/DefaultSparse.chpl
  modules/layouts/LayoutCS.chpl
Labels: post-release

#14102 Delete workaround that caused memory leaks
  compiler/AST/build.cpp
Labels: post-release

#14101 Add User Error for unsupported type queries
  compiler/resolution/callInfo.cpp
  test/classes/generic/queryGenericField.chpl
  test/classes/generic/queryGenericField.good
  test/functions/diten/formalArrayWithQueriedEltSize.bad
  test/functions/diten/formalArrayWithQueriedEltSize.future
Labels: post-release

#13785 Modify sparse element-wise arithmetics to support all sparse formats
  modules/packages/LinearAlgebra.chpl
  test/library/packages/LinearAlgebra/correctness/testElementwise.chpl
  test/library/packages/LinearAlgebra/correctness/testElementwise.good
Labels: post-release, stat: cla signed

#14089 Close a leak with string varargs
  compiler/resolution/callDestructors.cpp
  test/functions/varargs/stringVarargLeak.chpl
  test/functions/varargs/stringVarargLeak.execopts
  test/functions/varargs/stringVarargLeak.good
Labels: post-release

#14123 Add simple fix for swapping record-wrapped owned pointers
  modules/internal/ChapelBase.chpl
  test/statements/swap/swapRecordWrappingOwned.chpl
  test/statements/swap/swapRecordWrappingOwned.good
Labels: post-release

#14122 Fix union memory management
  compiler/AST/AggregateType.cpp
  compiler/AST/symbol.cpp
  compiler/AST/type.cpp
  compiler/codegen/expr.cpp
  compiler/include/symbol.h
  compiler/include/type.h
  compiler/passes/initializerRules.cpp
  compiler/passes/normalize.cpp
  compiler/passes/resolveIntents.cpp
  compiler/resolution/AutoDestroyScope.cpp
  compiler/resolution/addAutoDestroyCalls.cpp
  compiler/resolution/callDestructors.cpp
  compiler/resolution/cullOverReferences.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/generics.cpp
  compiler/resolution/lowerIterators.cpp
  compiler/resolution/preFold.cpp
  compiler/resolution/resolveFunction.cpp
  compiler/resolution/tuples.cpp
  compiler/resolution/wrappers.cpp
  test/classes/unions/const-an-in-basic.chpl
  test/classes/unions/const-an-in-basic.good
  test/classes/unions/union-in-list.chpl
  test/classes/unions/union-in-list.good
  test/classes/unions/union-string.future
  test/classes/unions/union-string.skipif
Labels: post-release

#14046 Fix default hash combine statistics
  modules/internal/DefaultAssociative.chpl
  test/associative/diten/enumArrays.good
  test/associative/ferguson/check-hashing-statistics.chpl
  test/associative/ferguson/check-hashing-statistics.compopts
  test/associative/ferguson/check-hashing-statistics.good
  test/classes/bradc/arrayInClass/arrayOfArithInClass.good
  test/classes/bradc/arrayInClass/genericArrayInClass-arith.good
  test/classes/bradc/arrayInClass/genericArrayInClass-otharrs.good
  test/classes/bradc/arrayInClass/genericArrayInClass-real.good
  test/classes/bradc/arrayInClass/genericClassArray-named.good
  test/domains/deitz/test_enum_domain1.good
  test/domains/vass/assoc-domain-assign-1.good
  test/domains/vass/enumerated-domain-initializer-1.good
  test/types/enum/diten/enumDom.good
  test/users/shetag/assocarr.good
Labels: post-release
