Repository chapel-lang/chapel, pull requests merged in 2019-10, with the labels that each got.

#14118 Add array/domain creation perftest
  test/ML-GRAPHFILES
  test/performance/array/distCreate-domains-deinit.ml-perf.graph
  test/performance/array/distCreate-domains-init.ml-perf.graph
  test/performance/array/distCreate-large-deinit.ml-perf.graph
  test/performance/array/distCreate-large-init.ml-perf.graph
  test/performance/array/distCreate-small-deinit.ml-perf.graph
  test/performance/array/distCreate-small-init.ml-perf.graph
  test/performance/array/distCreate-tiny-deinit.ml-perf.graph
  test/performance/array/distCreate-tiny-init.ml-perf.graph
  test/performance/array/distCreate.chpl
  test/performance/array/distCreate.compopts
  test/performance/array/distCreate.good
  test/performance/array/distCreate.ml-execopts
  test/performance/array/distCreate.ml-keys
  test/performance/array/distCreate.ml-numlocales
Labels: post-release

#14180 Make user-defined overloads of class assignments illegal
  compiler/AST/type.cpp
  compiler/include/type.h
  compiler/passes/checkResolved.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/wrappers.cpp
  test/classes/assignments/noAssignClass.chpl
  test/classes/assignments/noAssignClass.good
  test/classes/hilde/freeAssignment.bad
  test/classes/hilde/freeAssignment.chpl
  test/classes/hilde/freeAssignment.future
  test/classes/hilde/freeAssignment.good
Labels: stat: Work in Progress

#14127 Add local sparse domain assignment perftest
  test/GRAPHFILES
  test/performance/sparse/domainAssignment-dissimilar.chpl
  test/performance/sparse/domainAssignment-dissimilar.good
  test/performance/sparse/domainAssignment-dissimilar.graph
  test/performance/sparse/domainAssignment-dissimilar.perfexecopts
  test/performance/sparse/domainAssignment-dissimilar.perfkeys
  test/performance/sparse/domainAssignment-similar.chpl
  test/performance/sparse/domainAssignment-similar.good
  test/performance/sparse/domainAssignment-similar.graph
  test/performance/sparse/domainAssignment-similar.perfexecopts
  test/performance/sparse/domainAssignment-similar.perfkeys
Labels: post-release

#14248 Refactor multilocale libraries to compile client library with host compiler
  runtime/etc/Makefile.mli-common
  runtime/etc/Makefile.mli-shared
  runtime/etc/Makefile.mli-static
  runtime/etc/Makefile.shared
Labels: post-release

#14257 Push Dockerfiles and README updates from Chapel Release 1.20.0 back to the master branch.
  util/dockerfiles/Dockerfile
  util/dockerfiles/README.md
  util/dockerfiles/gasnet/Dockerfile
Labels: stat: cla required

#13767 Improve bounds checking error
  modules/dists/BlockCycDist.chpl
  modules/dists/BlockDist.chpl
  modules/dists/CyclicDist.chpl
  modules/dists/DimensionalDist2D.chpl
  modules/dists/PrivateDist.chpl
  modules/dists/ReplicatedDist.chpl
  modules/dists/StencilDist.chpl
  modules/internal/ArrayViewRankChange.chpl
  modules/internal/ArrayViewReindex.chpl
  modules/internal/ArrayViewSlice.chpl
  modules/internal/ChapelArray.chpl
  modules/internal/DefaultRectangular.chpl
  test/arrays/bradc/localSlices/localsliceOOB.good
  test/arrays/bradc/localSlices/localsliceOOB2.good
  test/arrays/bradc/localSlices/nonlocalslice.comm-none.good
  test/arrays/bradc/slices/outOfBoundsSlice.good
  test/arrays/bradc/slices/sliceArray.good
  test/arrays/bradc/slices/sliceStridedArray.good
  test/arrays/deitz/part6/test_bounds1.good
  test/arrays/deitz/part6/test_bounds2.good
  test/arrays/slices/commCounts/sliceLocDist.good
  test/arrays/slices/commCounts/sliceLocDist.na-none.good
  test/arrays/waynew/init2.good
  test/distributions/bharshbarg/stencil/localReads.good
  test/distributions/bharshbarg/stencil/localReads.prediff
  test/distributions/bradc/blkCyc/blkCycSliceOOB.good
  test/distributions/bradc/idxToLocale.comm-none.good
  test/domains/figueroa/ReallocateSlice.bad
  test/domains/figueroa/ReallocateSlice.future
  test/domains/figueroa/ReallocateSlice.skipif
  test/execflags/bradc/gdbddash/declint2.good
  test/functions/iterators/bradc/badzip/arrayZipMismatch.future
  test/functions/iterators/bradc/badzip/arrayZipMismatch2.bad
  test/functions/iterators/bradc/badzip/arrayZipMismatch2.future
  test/functions/iterators/bradc/badzip/arrayZipMismatch2.skipif
  test/library/packages/UnitTest/launcher_Test.halt.good
  test/library/packages/UnitTest/launcher_Test.numLocales.comm-none.good
  test/multilocale/bradc/referToLocaleOne.comm-none.good
  test/optimizations/forall-unordered-opt/compilation-tests/COMPOPTS
  test/studies/bale/histogram/histo-atomics-forall-opt.compopts
Labels: post-release

#14260 Fix multiple start_test invocations to print correct summary
  util/start_test
Labels: stat: Ready to Merge

#14310 Support the Chapel bytes type in single locale Python interop
  compiler/codegen/library.cpp
  compiler/codegen/symbol.cpp
  compiler/include/fixupExports.h
  compiler/main/driver.cpp
  compiler/resolution/fixupExports.cpp
  modules/internal/ChapelStandard.chpl
  modules/internal/ExportWrappers.chpl
  modules/internal/ExternalString.chpl
  runtime/include/chpl-export-wrappers.h
  runtime/include/python/chplrt.pxd
  runtime/include/stdchpl.h
  runtime/src/Makefile.share
  runtime/src/chpl-export-wrappers.c
  test/interop/C/exportBytes/.gitignore
  test/interop/C/exportBytes/CLEANFILES
  test/interop/C/exportBytes/PRECOMP
  test/interop/C/exportBytes/SKIPIF
  test/interop/C/exportBytes/TestLibrary.chpl
  test/interop/C/exportBytes/TestLibrary.notest
  test/interop/C/exportBytes/noArgsRetBytes.good
  test/interop/C/exportBytes/noArgsRetBytes.lastcompopts
  test/interop/C/exportBytes/noArgsRetBytes.suppressif
  test/interop/C/exportBytes/noArgsRetBytes.test.c
  test/interop/python/chapelBytes/CLEANFILES
  test/interop/python/chapelBytes/COMPOPTS
  test/interop/python/chapelBytes/PREDIFF
  test/interop/python/chapelBytes/SKIPIF
  test/interop/python/chapelBytes/exportBytes.chpl
  test/interop/python/chapelBytes/exportBytes.good
  test/interop/python/chapelBytes/exportBytes.noexec
  test/interop/python/chapelBytes/exportBytes.prediff
  test/interop/python/chapelBytes/skipif_helper.py
  test/interop/python/chapelBytes/sub_test
  test/interop/python/chapelBytes/use_exportBytes.py
Labels: area: Compiler, stat: Needs Code Review, stat: Needs Testing, type: Feature Request

#13206 Add an array checkpointer that is parallel across locales
  test/io/diten/checkpoint.chpl
  test/io/diten/checkpoint.notest
  test/io/diten/testCheckpoint.chpl
  test/io/diten/testCheckpoint.good
Labels: post-release
