Repository chapel-lang/chapel, pull requests merged in 2020-10, with the labels that each got.

#16514 Verifying if the matrix is symmetric positive definite during Cholesky Decomposition
  modules/packages/LinearAlgebra.chpl
  test/library/packages/LinearAlgebra/correctness/testCholeskyComplexError.chpl
  test/library/packages/LinearAlgebra/correctness/testCholeskyComplexError.good
  test/library/packages/LinearAlgebra/correctness/testCholeskyRealError.chpl
  test/library/packages/LinearAlgebra/correctness/testCholeskyRealError.good
Labels: stat: cla required

#16518 Handle 'reduce' of a forall of an iterable
  compiler/AST/foralls.cpp
  modules/internal/ChapelIteratorSupport.chpl
  test/reductions/reduceLoopOfPromoted.future
  test/reductions/reduceLoopOfPromoted.good
  test/reductions/sungeun/count.bad
  test/reductions/sungeun/count.future
  test/reductions/vass/reduce-of-more-promoted.bad
  test/reductions/vass/reduce-of-more-promoted.chpl
  test/reductions/vass/reduce-of-more-promoted.future
  test/reductions/vass/reduce-of-more-promoted.good
  test/reductions/vass/reduceLoopOfPromoted-empty.chpl
  test/reductions/vass/reduceLoopOfPromoted-empty.good
  test/reductions/vass/reduceLoopOfPromoted-nondomain.chpl
  test/reductions/vass/reduceLoopOfPromoted-nondomain.good
Labels: stat: Ready to Merge

#16551 Move NUMA CHIP to inactive directory
  doc/rst/developer/chips/README.md
  doc/rst/developer/chips/inactive/18.rst
  doc/rst/developer/chips/inactive/README.md
Labels: post-release
