Repository chapel-lang/chapel, pull requests merged in 2020-05, with the labels that each got.

#14873 Demonstration for HDF5 Tables
  test/users/npadmana/htable/.gitignore
  test/users/npadmana/htable/HTable.chpl
  test/users/npadmana/htable/HTable.notest
  test/users/npadmana/htable/NOTEST
  test/users/npadmana/htable/testHTable.chpl
  test/users/npadmana/htable/testHTable.good
Labels: stat: cla signed

#15624 Don't generate entries for the index variables of loop expressions in chpldoc
  compiler/AST/LoopExpr.cpp
  test/chpldoc/globals/arrayLiteral.doc.bad
  test/chpldoc/globals/arrayLiteral.doc.future
Labels: area: Compiler, area: Tests, area: Tools, stat: Needs Code Review

#15317 Linked list first, last, and contains
  modules/standard/LinkedLists.chpl
  test/library/standard/LinkedLists/first-last-contains.chpl
  test/library/standard/LinkedLists/first-last-contains.good
Labels: stat: cla signed

#15637 Add spaces required by gcc 4.9
  compiler/resolution/visibleFunctions.cpp
Labels: area: Compiler, stat: Needs Testing

#15292 Add wrapper for qio_decode_char_buf
  modules/internal/BytesStringCommon.chpl
  modules/internal/String.chpl
Labels: stat: cla signed

#15597 Detect integer overflows in string/bytes implementation
  modules/internal/BytesStringCommon.chpl
  modules/internal/ChapelUtil.chpl
  test/modules/sungeun/test_safeMul.chpl
  test/modules/sungeun/test_safeMul.good
Labels: stat: cla signed

#15641 Improve mason external --setup
  doc/rst/tools/mason/mason.rst
  test/mason/mason-external/libtomlc99/mason-external.good
  tools/mason/MasonBuild.chpl
  tools/mason/MasonExternal.chpl
  tools/mason/MasonHelp.chpl
  tools/mason/MasonUpdate.chpl
  tools/mason/MasonUtils.chpl
Labels: stat: cla signed

#15678 replace ~/.mason with MASON_HOME
  tools/mason/MasonExternal.chpl
Labels: stat: cla signed

#15626 Eigensystems for symmetric/hermitian matrices
  modules/packages/LinearAlgebra.chpl
  test/library/packages/LinearAlgebra/correctness/testEigen.chpl
Labels: stat: cla signed

#15681 Update mason-external test to find compilers for portability
  test/mason/SKIPIF
  test/mason/mason-external/libtomlc99/SKIPIF
  test/mason/mason-external/libtomlc99/mason-external.chpl
  test/mason/mason-external/libtomlc99/mason-external.prediff
Labels: stat: Ready to Merge

#15516 added error message for missing version
  test/mason/mason-external/masonExternalRanges/CLEANFILES
  test/mason/mason-external/masonExternalRanges/COMPOPTS
  test/mason/mason-external/masonExternalRanges/EXECENV
  test/mason/mason-external/masonExternalRanges/SKIPIF
  test/mason/mason-external/masonExternalRanges/mason-external-range.chpl
  test/mason/mason-external/masonExternalRanges/mason-external-range.good
  test/mason/mason-external/masonExternalRanges/mason-external.prediff
  test/mason/mason-external/masonExternalRanges/src.notest
Labels: stat: cla signed
