Repository chapel-lang/chapel, pull requests merged in 2020-04, with the labels that each got.

#15392 Adds renaming a module when using it to the spec and modules primer
  doc/rst/language/spec/statements.rst
  test/release/examples/primers/modules.chpl
  test/release/examples/primers/modules.good
Labels: area: Docs, area: Tests, stat: Needs Code Review

#15416 Adjust the spec for import statements
  doc/rst/language/spec/modules.rst
  doc/rst/language/spec/statements.rst
Labels: area: Docs, stat: Needs Code Review

#15433 Added project-testSrc to CLEANFILES
  test/mason/CLEANFILES
  test/mason/masonInit/CLEANFILES
Labels: stat: cla signed

#15460 Add "import" to our syntax highlighters
  highlight/emacs/chpl-mode.el
  highlight/highlight/langDefs/chpl.lang
  highlight/source-highlight/chpl.lang
  highlight/vim/syntax/chpl.vim
Labels: area: Tools, stat: Needs Code Review

#15458 Add import statements to the modules primer
  test/release/examples/primers/modules.chpl
  test/release/examples/primers/modules.good
Labels: area: Docs, area: Tests, stat: Needs Code Review

#15469 Reshuffle information on import and use statements in the spec
  doc/rst/language/spec/modules.rst
  doc/rst/language/spec/statements.rst
  doc/rst/language/spec/types.rst
Labels: area: Docs, area: Tests, stat: Needs Code Review, stat: Needs Testing

#15482 Doc fixes for IO and DynamicIters
  modules/standard/DynamicIters.chpl
  modules/standard/IO.chpl
Labels: stat: cla signed

#15474 Update sub_test filtering for common system error modes
  util/test/sub_test
Labels: area: BTR, post-release, stat: Ready to Merge

#15221 Standardize string/bytes buffer allocations
  modules/internal/ByteBufferHelpers.chpl
Labels: post-release, stat: Ready to Merge, stat: cla signed

#15320 Refactor code that gets outer scope for visibleFunctions.cpp
  compiler/resolution/visibleFunctions.cpp
Labels: post-release

#15500 Remove the deprecation warnings for symbols in the IO module
  modules/internal/ChapelIO.chpl
  modules/internal/LastResortIO.chpl
  test/deprecated/io/checkopenmem.chpl
  test/deprecated/io/checkopenmem.good
  test/deprecated/io/checkopenreader.chpl
  test/deprecated/io/checkopenreader.good
  test/deprecated/io/checkopentmp.chpl
  test/deprecated/io/checkopentmp.good
  test/deprecated/io/checkreadfreg.chpl
  test/deprecated/io/checkreadfreg.good
  test/deprecated/io/checkreadfreg.skipif
  test/deprecated/io/foo.txt
  test/deprecated/io/helper.txt
  test/deprecated/io/warnings.chpl
  test/deprecated/io/warnings.good
  test/library/packages/TOML/specification/TomlTest.chpl
  test/modules/sungeun/init/printModuleInitOrder.good
  test/modules/sungeun/init/printModuleInitOrder.na-none.good
  test/studies/shootout/submitted/knucleotide2.bad
Labels: area: Libraries / Modules, area: Tests, stat: Needs Code Review

#15022 improve QUICKSTART.rst
  doc/rst/usingchapel/QUICKSTART.rst
  doc/rst/usingchapel/chplenv.rst
Labels: stat: cla signed

#15486 fixed mason example doc
  doc/rst/tools/mason/mason.rst
Labels: post-release, stat: Ready to Merge, stat: cla signed

#15396 Adding readWriteThis(ch: channel) in DistBag record
  modules/packages/DistributedBag.chpl
  test/library/packages/Collection/DistributedBagInChannel.chpl
  test/library/packages/Collection/DistributedBagInChannel.good
Labels: stat: cla signed

#15222 Add explicit types in ByteBufferHelpers
  modules/internal/ByteBufferHelpers.chpl
Labels: post-release, stat: cla signed

#15476 Avoid running tests that failed to compile and show them in results
  test/library/packages/UnitTest/Launcher_Test.execopts
  test/library/packages/UnitTest/launcher_Test.CompileFail.good
  test/library/packages/UnitTest/test_CompileFail.chpl
  test/library/packages/UnitTest/test_CompileFail.notest
  test/mason/mason-test/Mason.toml
  test/mason/mason-test/mason-test.good
  test/mason/mason-test/test/compileerror.chpl
  tools/mason/MasonTest.chpl
  tools/mason/MasonUtils.chpl
Labels: stat: cla signed

#15454 Only try to build compiler once with `make mason`
  Makefile
Labels: post-release

#15524 Extend ast traversals for Import statements to handle missing functionality
  compiler/AST/AstDump.cpp
  compiler/AST/AstDumpToHtml.cpp
  compiler/AST/AstDumpToNode.cpp
  compiler/AST/view.cpp
Labels: area: Compiler, stat: Needs Code Review

#15526 Add new tests to lock in import behavior
  test/visibility/import/enablesUnqualified/multipleUnqualified/badName.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/badName.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/repeats.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/repeats.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/unqualifiedPrivate.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/unqualifiedPrivate.good
  test/visibility/import/enablesUnqualified/unqualifiedPrivate.chpl
  test/visibility/import/enablesUnqualified/unqualifiedPrivate.good
  test/visibility/import/rename/badNewName.chpl
  test/visibility/import/rename/badNewName.good
  test/visibility/import/rename/badOldName.chpl
  test/visibility/import/rename/badOldName.good
  test/visibility/import/rename/ensureRightSymbolRenamed.chpl
  test/visibility/import/rename/ensureRightSymbolRenamed.good
  test/visibility/import/rename/noSuchOldName.chpl
  test/visibility/import/rename/noSuchOldName.good
  test/visibility/import/rename/renameAndUnrenamed.chpl
  test/visibility/import/rename/renameAndUnrenamed.good
  test/visibility/import/rename/renameChain.chpl
  test/visibility/import/rename/renameChain.good
  test/visibility/import/rename/renameNoLeak.chpl
  test/visibility/import/rename/renameNoLeak.good
  test/visibility/import/rename/renamePrivate.chpl
  test/visibility/import/rename/renamePrivate.good
  test/visibility/import/rename/renameToAlreadyImported.chpl
  test/visibility/import/rename/renameToAlreadyImported.good
  test/visibility/import/rename/renameTwice.chpl
  test/visibility/import/rename/renameTwice.good
Labels: area: Tests

#15503 Add a future test for spawn(..stderr=STDOUT)
  test/library/standard/Spawn/redirect-stderr-stdout.bad
  test/library/standard/Spawn/redirect-stderr-stdout.chpl
  test/library/standard/Spawn/redirect-stderr-stdout.future
  test/library/standard/Spawn/redirect-stderr-stdout.good
Labels: stat: cla signed

#15490 Adjust string and bytes records' field names
  modules/internal/Bytes.chpl
  modules/internal/BytesCasts.chpl
  modules/internal/BytesStringCommon.chpl
  modules/internal/ExportWrappers.chpl
  modules/internal/MemTracking.chpl
  modules/internal/String.chpl
  modules/internal/StringCasts.chpl
  modules/packages/ZMQ.chpl
  test/patterns/dynamic-programming/sequential/edit_distance.chpl
  test/patterns/dynamic-programming/sequential/longest_common_subsequence.chpl
  test/types/bytes/decode.chpl
  test/types/string/psahabu/perf/allocate.chpl
  test/types/string/psahabu/perf/arguments.chpl
Labels: stat: cla signed

#15529 Handle edge case for 1 char filename in MasonUtils
  test/mason/mason-test/Mason.toml
  test/mason/mason-test/mason-test.good
  test/mason/mason-test/test/x.chpl
  tools/mason/MasonUtils.chpl
Labels: stat: Ready to Merge, stat: cla signed

#15561 update flag for compiler global boundsChecking
  compiler/AST/type.cpp
Labels: stat: cla signed

#15538 added SPACK_ROOT env to MasonEnv
  test/mason/env/mason-env.good
  test/mason/env/mason-registry.good
  tools/mason/MasonEnv.chpl
Labels: stat: cla signed

#15559 mason init help message
  test/mason/mason-help-scope/masonHelpScope.chpl
  tools/mason/MasonInit.chpl
Labels: stat: cla signed

#15557 Remove BUG where return in serial block serializes all subsequent code
  compiler/AST/build.cpp
  test/statements/serial/serialReturn.chpl
  test/statements/serial/serialReturn.good
Labels: stat: cla signed

#15376 Overloaded INT_ASSERT
  compiler/include/misc.h
Labels: stat: cla signed

#15228 Toml Parser: Misleading "line number" on error
  modules/packages/TOML.chpl
  test/library/packages/TOML/test/commentTest.chpl
  test/library/packages/TOML/test/commentTest.good
  test/library/packages/TOML/test/testtime.chpl
Labels: post-release, stat: cla signed

#15569 [Feature] range.isBounded() function
  modules/internal/ChapelRange.chpl
  test/types/range/userAPI/byteRangeTest.good
  test/types/range/userAPI/codepointRangeTest.good
  test/types/range/userAPI/rangeAPItest.chpl
  test/types/range/userAPI/simpleRangeTest.good
Labels: stat: cla signed

#15412 update AstToText to remove AppendExpr conflicts
  compiler/AST/AstToText.cpp
  compiler/include/AstToText.h
  test/chpldoc/globals/arrayLiteral.doc.bad
  test/chpldoc/globals/arrayLiteral.doc.good
  test/chpldoc/globals/arrayTypeAlias.doc.bad
  test/chpldoc/globals/arrayTypeAlias.doc.future
  test/chpldoc/globals/arrayTypeAlias.doc.good
  test/chpldoc/globals/calls.doc.catfiles
  test/chpldoc/globals/calls.doc.chpl
  test/chpldoc/globals/calls.doc.good
  test/chpldoc/globals/domains.doc.catfiles
  test/chpldoc/globals/domains.doc.chpl
  test/chpldoc/globals/domains.doc.good
  test/chpldoc/globals/ifParamCondition.doc.catfiles
  test/chpldoc/globals/ifParamCondition.doc.chpl
  test/chpldoc/globals/ifParamCondition.doc.good
Labels: stat: cla signed

#15580 Chpldoc test updates
  test/chpldoc/globals/arrayLiteral.doc.future
  test/chpldoc/globals/atomics.doc.bad
  test/chpldoc/globals/atomics.doc.catfiles
  test/chpldoc/globals/atomics.doc.chpl
  test/chpldoc/globals/atomics.doc.future
  test/chpldoc/globals/atomics.doc.good
Labels: area: Tests

#15238 Add support for a compiler `--checks` flag
  compiler/main/driver.cpp
  man/chpl.rst
  test/compflags/bradc/help/userhelp.good
  test/compflags/checks/checks-off.good
  test/compflags/checks/checks.chpl
  test/compflags/checks/checks.compopts
  test/compflags/checks/checks.good
  util/chpl-completion.bash
Labels: stat: cla signed

#15552 extend param for loops to support the count operator
  compiler/AST/ParamForLoop.cpp
  modules/internal/ChapelRange.chpl
  test/param/loop/paramForLoopBoundSmall.chpl
  test/param/loop/paramForLoopBoundSmall.good
  test/param/loop/paramForLoopBounded.chpl
  test/param/loop/paramForLoopBounded.good
  test/param/loop/paramForLoopComplete.chpl
  test/param/loop/paramForLoopComplete.good
  test/param/loop/paramForLoopCount.chpl
  test/param/loop/paramForLoopCount.good
  test/param/loop/paramForLoopWrongCountHigh.chpl
  test/param/loop/paramForLoopWrongCountHigh.good
  test/param/loop/paramForLoopWrongCountLow.chpl
  test/param/loop/paramForLoopWrongCountLow.good
  test/param/loop/paramForLoopWrongCountType.chpl
  test/param/loop/paramForLoopWrongCountType.good
  test/param/loop/paramForLoopWrongTypeHigh.chpl
  test/param/loop/paramForLoopWrongTypeHigh.good
  test/param/loop/paramForLoopWrongTypeLow.chpl
  test/param/loop/paramForLoopWrongTypeLow.good
  test/param/loop/paramForLoopZeroCount.chpl
  test/param/loop/paramForLoopZeroCount.good
  test/trivial/bharshbarg/paramForOverIter.good
  test/trivial/deitz/type-param-mod-config/invalid_param_loop.good
  test/types/range/lydia/badRange-string-lower.good
  test/types/range/lydia/badRange-string-multi.good
  test/types/range/lydia/badRange-string-upper.good
  test/types/tuple/tupleParamLoop.bad
Labels: stat: cla signed

#15584 add space after atomics in chpldoc
  compiler/AST/AstToText.cpp
  test/chpldoc/globals/atomics.doc.bad
  test/chpldoc/globals/atomics.doc.future
Labels: area: Compiler, area: Docs, area: Tests, area: Tools, stat: Ready to Merge, stat: cla signed

#15585 Update three places to use ImportStmt's providesUnqualifiedAccess method
  compiler/AST/ImportStmt.cpp
  compiler/AST/UseStmt.cpp
  test/visibility/import/rename/last-before-list-not-mod.chpl
  test/visibility/import/rename/last-before-list-not-mod.good
Labels: area: Compiler, stat: Needs Code Review, type: Error Message, type: Refactor

#15567 adding docs for compiler defined global variables
  doc/rst/technotes/globalvars.rst
Labels: area: Docs, stat: Ready to Merge, stat: cla signed

#15594 using add_stylesheet with sphinx removing deprecation warning
  doc/rst/conf.py
  doc/rst/meta/templates/page.html
Labels: stat: cla signed

#15603 Add error message when a module is listed multiple times in a row in a use/import
  compiler/passes/ResolveScope.cpp
  test/visibility/duplicateMod.chpl
  test/visibility/duplicateMod.good
  test/visibility/import/duplicateMod.chpl
  test/visibility/import/duplicateMod.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#15601 Extend cases where `super` can be used in an `import` statement
  compiler/passes/ResolveScope.cpp
  test/modules/diten/usemodule/test_nested_use_outer-super.bad
  test/modules/diten/usemodule/test_nested_use_outer-super.future
  test/visibility/import/relative/import-relative-error6.chpl
  test/visibility/import/relative/import-relative-error6.good
  test/visibility/import/relative/import-super.chpl
  test/visibility/import/relative/import-super.good
  test/visibility/import/superDotModDotSuperDotModDotVar.chpl
  test/visibility/import/superDotModDotSuperDotModDotVar.good
  test/visibility/import/superDotSuperDotVar.bad
  test/visibility/import/superDotSuperDotVar.future
  test/visibility/import/superDotVar.bad
  test/visibility/import/superDotVar.future
  test/visibility/import/superDotVar2.chpl
  test/visibility/import/superDotVar2.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#15577 removed --list
  tools/mason/MasonHelp.chpl
  tools/mason/mason.chpl
Labels: stat: cla signed
