Repository chapel-lang/chapel, pull requests merged in 2020-03, with the labels that each got.

#15019 Change default privacy of import statements to private
  compiler/AST/ImportStmt.cpp
  compiler/AST/build.cpp
  compiler/include/ImportStmt.h
  compiler/include/UseStmt.h
  compiler/include/stmt.h
  compiler/passes/scopeResolve.cpp
  compiler/resolution/visibleFunctions.cpp
  test/visibility/import/importAndImport.good
  test/visibility/import/useWithImports.good
  test/visibility/import/useWithImports2.chpl
  test/visibility/import/useWithImports2.good
  test/visibility/private/uses/qualified.chpl
  test/visibility/private/uses/qualified.good
Labels: area: Compiler, area: Language, area: Tests, stat: Ready to Merge

#15007 enable deprecation warnings
  modules/internal/LastResortIO.chpl
  test/deprecated/io/checkreadfreg.chpl
  test/deprecated/io/checkreadfreg.good
  test/deprecated/io/checkreadfreg.skipif
  test/deprecated/io/warnings.chpl
  test/deprecated/io/warnings.good
Labels: area: Libraries / Modules, stat: Ready to Merge, stat: cla signed

#15046 Fix import func body
  compiler/passes/normalize.cpp
  test/visibility/import/inFuncBody.chpl
  test/visibility/import/inFuncBody.good
  test/visibility/import/inFuncBody2.chpl
  test/visibility/import/inFuncBody2.good
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#15052 Remove warning for string.format
  modules/internal/LastResortIO.chpl
  test/deprecated/io/warnings.chpl
  test/deprecated/io/warnings.good
Labels: area: Libraries / Modules, area: Tests, stat: Needs Testing

#14037 Allows to test one|some, not all, of the tests using `mason test` inside a mason package
  test/mason/masonTestSome/.gitignore
  test/mason/masonTestSome/COMPOPTS
  test/mason/masonTestSome/EXECENV
  test/mason/masonTestSome/Mason.toml
  test/mason/masonTestSome/SKIPIF
  test/mason/masonTestSome/mason-test-some.chpl
  test/mason/masonTestSome/mason-test-some.good
  test/mason/masonTestSome/mason-test-some.prediff
  test/mason/masonTestSome/src/NOTEST
  test/mason/masonTestSome/src/masonTestSome.chpl
  test/mason/masonTestSome/test/NOTEST
  test/mason/masonTestSome/test/test1.chpl
  test/mason/masonTestSome/test/test2.chpl
  test/mason/masonTestSome/test/testDir/NOTEST
  test/mason/masonTestSome/test/testDir/test3.chpl
  tools/mason/MasonTest.chpl
Labels: stat: Ready to Merge, stat: cla signed

#15053 Replace empty uses in the standard, internal, and package modules with imports
  modules/dists/dims/BlockCycDim.chpl
  modules/dists/dims/ReplicatedDim.chpl
  modules/internal/CPtr.chpl
  modules/internal/ChapelArray.chpl
  modules/internal/ChapelBase.chpl
  modules/internal/ChapelLocale.chpl
  modules/internal/DefaultRectangular.chpl
  modules/internal/DefaultSparse.chpl
  modules/internal/MemConsistency.chpl
  modules/internal/OwnedObject.chpl
  modules/internal/SharedObject.chpl
  modules/layouts/LayoutCS.chpl
  modules/packages/Curl.chpl
  modules/packages/HDF5.chpl
  modules/packages/HDFS.chpl
  modules/packages/LinearAlgebra.chpl
  modules/packages/Prefetch.chpl
  modules/standard/Barriers.chpl
  modules/standard/BitOps.chpl
  modules/standard/DateTime.chpl
  modules/standard/IO.chpl
  modules/standard/LinkedLists.chpl
  modules/standard/List.chpl
  modules/standard/Map.chpl
  modules/standard/Math.chpl
  modules/standard/Path.chpl
  modules/standard/Random.chpl
  modules/standard/Set.chpl
  modules/standard/Time.chpl
  modules/standard/Types.chpl
Labels: area: Libraries / Modules, stat: Needs Code Review

#14967 Add accumulate tool to Itertools
  test/library/packages/Itertools/Itertools.chpl
  test/library/packages/Itertools/accumulate/COMPOPTS
  test/library/packages/Itertools/accumulate/check_addition.chpl
  test/library/packages/Itertools/accumulate/check_addition.good
  test/library/packages/Itertools/accumulate/check_bitwise_and.chpl
  test/library/packages/Itertools/accumulate/check_bitwise_and.good
  test/library/packages/Itertools/accumulate/check_bitwise_or.chpl
  test/library/packages/Itertools/accumulate/check_bitwise_or.good
  test/library/packages/Itertools/accumulate/check_bitwise_xor.chpl
  test/library/packages/Itertools/accumulate/check_bitwise_xor.good
  test/library/packages/Itertools/accumulate/check_division.chpl
  test/library/packages/Itertools/accumulate/check_division.good
  test/library/packages/Itertools/accumulate/check_multiplication.chpl
  test/library/packages/Itertools/accumulate/check_multiplication.good
  test/library/packages/Itertools/accumulate/check_subtraction.chpl
  test/library/packages/Itertools/accumulate/check_subtraction.good
Labels: stat: cla signed

#15036 Update docs to reflect the changes made in #14789
  doc/rst/language/spec/records.rst
Labels: stat: cla signed

#15031 Add lldb flag to executables
  runtime/include/arg.h
  runtime/include/chpl-comm.h
  runtime/src/arg.c
  runtime/src/chpl-init.c
  runtime/src/comm/gasnet/comm-gasnet.c
  runtime/src/comm/none/comm-none.c
  runtime/src/comm/ofi/comm-ofi.c
  runtime/src/comm/ugni/comm-ugni.c
  test/execflags/lldbddash/COMPOPTS
  test/execflags/lldbddash/EXECOPTS
  test/execflags/lldbddash/SKIPIF
  test/execflags/lldbddash/declint.chpl
  test/execflags/lldbddash/declint.good
  test/execflags/lldbddash/declint.prediff
  test/execflags/lldbddash/declint.stdin
Labels: stat: cla signed

#14764 Added 'lifetime' keyword and missing types
  highlight/highlight/langDefs/chpl.lang
Labels: stat: cla signed

#15088 Dead-code eliminate unused runtime types
  compiler/optimizations/deadCodeElimination.cpp
  test/distributions/robust/arithmetic/performance/multilocale/alloc.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/alloc.replicated.na-none.good
  test/distributions/robust/arithmetic/performance/multilocale/alloc_all.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/alloc_all.replicated.na-none.good
  test/distributions/robust/arithmetic/performance/multilocale/assignReindex.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/assignReindex.replicated.na-none.good
  test/distributions/robust/arithmetic/performance/multilocale/assignSlice.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/assignSlice.replicated.na-none.good
  test/distributions/robust/arithmetic/performance/multilocale/reduceSlice.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/reduceSlice.replicated.na-none.good
  test/distributions/robust/arithmetic/performance/multilocale/rvfSlices/assignReindex.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/rvfSlices/assignReindex.replicated.na-none.good
  test/distributions/robust/arithmetic/performance/multilocale/rvfSlices/assignSlice.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/rvfSlices/assignSlice.replicated.na-none.good
  test/distributions/robust/arithmetic/performance/multilocale/rvfSlices/reduceSlice.replicated.good
  test/distributions/robust/arithmetic/performance/multilocale/rvfSlices/reduceSlice.replicated.na-none.good
Labels: stat: Ready to Merge

#15115 Make UnitTest index-independent
  modules/packages/UnitTest.chpl
  test/library/packages/UnitTest/AssertEqual/AssertEqualTest.chpl
  test/library/packages/UnitTest/AssertEqual/AssertEqualTest.good
  test/library/packages/UnitTest/AssertGreater/AssertGreaterTest.chpl
  test/library/packages/UnitTest/AssertLess/AssertLessTest.chpl
  test/library/packages/UnitTest/AssertNotEqual/AssertNotEqualTest.chpl
  test/library/packages/UnitTest/AssertNotEqual/AssertNotEqualTest.good
Labels: stat: Ready to Merge

#15092 add no doc to non-user io methods
  modules/standard/IO.chpl
Labels: area: Docs, area: Libraries / Modules, stat: Ready to Merge, stat: cla signed

#15131 Updates the example for testing in mason.rst and adds a test for it
  doc/rst/tools/mason/mason.rst
  test/mason/mason-test/Mason.toml
  test/mason/mason-test/mason-test.good
  test/mason/mason-test/test/docs/NOTEST
  test/mason/mason-test/test/docs/exampletest.chpl
Labels: stat: cla signed

#15135 Add throws tags to functions in Path module
  modules/standard/Path.chpl
  modules/standard/Spawn.chpl
Labels: stat: cla signed

#15165 Removed unnecessary return statements
  tools/mason/MasonTest.chpl
Labels: stat: cla signed

#15153 Fix grammar and capitals in docs
  doc/rst/developer/bestPractices/ContributorInfo.rst
  doc/rst/developer/bestPractices/TestSystem.rst
  test/release/examples/primers/learnChapelInYMinutes.chpl
Labels: area: Docs, area: Tests, stat: Ready to Merge, stat: cla signed

#15151 Fix copyright lines with no authors and add tests
  test/chpldoc/compflags/author/withoutAuthor/CLEANFILES
  test/chpldoc/compflags/author/withoutAuthor/withoutAuthor.doc.catfiles
  test/chpldoc/compflags/author/withoutAuthor/withoutAuthor.doc.chpl
  test/chpldoc/compflags/author/withoutAuthor/withoutAuthor.doc.good
  test/chpldoc/compflags/author/withoutAuthor/withoutAuthor.doc.prediff
  third-party/chpl-venv/chpldoc-sphinx-project/source/conf.py
Labels: area: Tests, area: Tools, stat: Ready to Merge, stat: cla signed

#15156 Grammar fixes in developer and user guide
  doc/rst/developer/Makefile.NOTES
  doc/rst/developer/adding-a-launcher.rst
  doc/rst/developer/bestPractices/CompilerIRTricks.rst
  doc/rst/developer/bestPractices/GASNetOnDesktops.rst
  doc/rst/users-guide/base/configs.rst
  doc/rst/users-guide/base/hello.rst
  doc/rst/users-guide/datapar/forall.rst
Labels: stat: cla signed

#15232 Add support for import statements that enable unqualified access to many syms
  compiler/AST/ImportStmt.cpp
  compiler/AST/build.cpp
  compiler/include/ImportStmt.h
  compiler/include/build.h
  compiler/parser/bison-chapel.cpp
  compiler/parser/chapel.ypp
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-error1.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-error1.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-error2.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-error2.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function-error1.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function-error1.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function-error2.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function-error2.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function-unordered.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function-unordered.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-function.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-unordered.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne-unordered.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/allButOne.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/last-before-list-not-mod.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/last-before-list-not-mod.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/multipleImports.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/multipleImports.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/multipleImports2.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/multipleImports2.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/multipleImports3.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/multipleImports3.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/no-call.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/no-call.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/no-literal.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/no-literal.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/public-import.bad
  test/visibility/import/enablesUnqualified/multipleUnqualified/public-import.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/public-import.future
  test/visibility/import/enablesUnqualified/multipleUnqualified/public-import.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/singleSym.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/singleSym.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerExcept.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerExcept.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerExcept2.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerExcept2.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerOnly.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerOnly.good
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerOnly2.chpl
  test/visibility/import/enablesUnqualified/multipleUnqualified/useAndImport-closerOnly2.good
  test/visibility/import/rename/renameInMultiImport.bad
  test/visibility/import/rename/renameInMultiImport.chpl
  test/visibility/import/rename/renameInMultiImport.future
  test/visibility/import/rename/renameInMultiImport.good
Labels: area: Compiler, area: Language, area: Tests, stat: Needs Code Review, stat: Needs Testing

#15248 Fix compatibility with old sed in the test script
  test/chpldoc/compflags/author/withoutAuthor/withoutAuthor.doc.prediff
Labels: stat: cla signed

#15137 Add chpldoc tests of --author
  test/chpldoc/compflags/author/basic/CLEANFILES
  test/chpldoc/compflags/author/basic/author.doc.catfiles
  test/chpldoc/compflags/author/basic/author.doc.chpl
  test/chpldoc/compflags/author/basic/author.doc.chpldocopts
  test/chpldoc/compflags/author/basic/author.doc.good
  test/chpldoc/compflags/author/basic/author.doc.prediff
  test/chpldoc/compflags/author/withSpace/CLEANFILES
  test/chpldoc/compflags/author/withSpace/withSpace.doc.catfiles
  test/chpldoc/compflags/author/withSpace/withSpace.doc.chpl
  test/chpldoc/compflags/author/withSpace/withSpace.doc.chpldocopts
  test/chpldoc/compflags/author/withSpace/withSpace.doc.good
  test/chpldoc/compflags/author/withSpace/withSpace.doc.prediff
  test/chpldoc/compflags/author/withSpecialChar/CLEANFILES
  test/chpldoc/compflags/author/withSpecialChar/withSpecialChar.doc.catfiles
  test/chpldoc/compflags/author/withSpecialChar/withSpecialChar.doc.chpl
  test/chpldoc/compflags/author/withSpecialChar/withSpecialChar.doc.chpldocopts
  test/chpldoc/compflags/author/withSpecialChar/withSpecialChar.doc.good
  test/chpldoc/compflags/author/withSpecialChar/withSpecialChar.doc.prediff
Labels: stat: cla signed

#14997 mason new --moduleName
  doc/rst/tools/mason/mason.rst
  test/mason/chplVersion/mason-chpl-version-new.chpl
  test/mason/masonInit/MasonInitTest5.chpl
  test/mason/masonInit/masonInitModifyToml.chpl
  test/mason/masonInit/masonInitModule.chpl
  test/mason/masonInit/masonInitModule.compopts
  test/mason/masonInit/masonInitModule.good
  test/mason/masonInit/masonInitPathTest.chpl
  test/mason/masonInit/masonInitTest.chpl
  test/mason/masonInit/masonInitTest2.chpl
  test/mason/masonInit/masonInitTest3.chpl
  test/mason/masonInit/masonInitTest4.chpl
  test/mason/masonNewBadName.0bad.good
  test/mason/masonNewBadName.bad-name.good
  test/mason/masonNewBadName.bad.name.good
  test/mason/masonNewBadName.chpl
  test/mason/masonNewModule.chpl
  test/mason/masonNewModule.compopts
  test/mason/masonNewModule.good
  test/mason/masonNewTest.chpl
  tools/mason/MasonHelp.chpl
  tools/mason/MasonInit.chpl
  tools/mason/MasonNew.chpl
Labels: stat: cla signed

#15281 fix for mason docs
  doc/rst/tools/mason/mason.rst
Labels: stat: cla signed

#15276 Update Mason Run error message
  tools/mason/MasonExample.chpl
Labels: stat: cla signed

#15305 Allow imports to rename symbols brought in for unqualified access
  compiler/AST/ImportStmt.cpp
  compiler/AST/UseStmt.cpp
  compiler/AST/build.cpp
  compiler/AST/stmt.cpp
  compiler/include/ImportStmt.h
  compiler/include/UseStmt.h
  compiler/include/stmt.h
  compiler/passes/ResolveScope.cpp
  compiler/passes/scopeResolve.cpp
  compiler/resolution/visibleFunctions.cpp
  test/visibility/import/enablesUnqualified/multipleUnqualified/public-import.bad
  test/visibility/import/enablesUnqualified/multipleUnqualified/public-import.future
  test/visibility/import/rename/renameAllNoQualified.chpl
  test/visibility/import/rename/renameAllNoQualified.good
  test/visibility/import/rename/renameAllNoQualified2.chpl
  test/visibility/import/rename/renameAllNoQualified2.good
  test/visibility/import/rename/renameFirst.chpl
  test/visibility/import/rename/renameFirst.good
  test/visibility/import/rename/renameInMultiImport-function.chpl
  test/visibility/import/rename/renameInMultiImport-function.good
  test/visibility/import/rename/renameInMultiImport.bad
  test/visibility/import/rename/renameInMultiImport.future
  test/visibility/import/rename/renameLast.chpl
  test/visibility/import/rename/renameLast.good
  test/visibility/import/rename/renameMiddle.chpl
  test/visibility/import/rename/renameMiddle.good
  test/visibility/import/rename/renameMultiple.chpl
  test/visibility/import/rename/renameMultiple.good
  test/visibility/import/rename/unqualified-access-function.chpl
  test/visibility/import/rename/unqualified-access-function.good
  test/visibility/import/rename/unqualified-access.bad
  test/visibility/import/rename/unqualified-access.future
Labels: area: Compiler, area: Tests, stat: Needs Code Review

#15322 Added error for Matrix() when given invalid array input
  modules/packages/LinearAlgebra.chpl
  test/library/packages/LinearAlgebra/correctness/no-dependencies/testMatrix-error.chpl
  test/library/packages/LinearAlgebra/correctness/no-dependencies/testMatrix-error.good
Labels: stat: cla signed

#15344 displays description of file reader and writer in docs
  modules/standard/IO.chpl
Labels: stat: cla signed

#15348 Add a test of an internal module calling a nested module only
  test/modules/paths/checkNestedModule.bad
  test/modules/paths/checkNestedModule.chpl
  test/modules/paths/checkNestedModule.compopts
  test/modules/paths/checkNestedModule.future
  test/modules/paths/checkNestedModule.good
  test/modules/paths/useNestedDir.notest
  test/modules/paths/useNestedDir/ChapelNumLocales.chpl
Labels: area: Tests

#15341 Language evolution updates for 1.21
  doc/rst/language/evolution.rst
Labels: stat: Ready to Merge
