Repository chapel-lang/chapel, pull requests merged in 2020-01, with the labels that each got.

#14632 Expiring value analysis
  compiler/include/driver.h
  compiler/include/flags_list.h
  compiler/main/driver.cpp
  compiler/passes/flattenFunctions.cpp
  compiler/resolution/callDestructors.cpp
  compiler/resolution/lifetime.cpp
  test/classes/delete-free/lifetimes/set-global-with-clause.chpl
  test/classes/delete-free/lifetimes/set-global-with-clause.good
  test/types/records/expiring/ex.chpl
  test/types/records/expiring/ex.compopts
  test/types/records/expiring/ex.good
  test/users/engin/retInnerFunction.bad
  util/chpl-completion.bash
Labels: stat: Ready to Merge

#14649 Require private configs to be fully qualified when set on command-line
  compiler/AST/build.cpp
  compiler/codegen/codegen.cpp
  compiler/include/bison-chapel.h
  compiler/parser/bison-chapel.cpp
  compiler/parser/chapel.ypp
  doc/rst/language/spec/variables.rst
  doc/rst/usingchapel/executing.rst
  runtime/include/config.h
  runtime/src/config.c
  test/compflags/configs/privateConfigParam-ambig.good
  test/compflags/configs/privateConfigParam-ft.good
  test/compflags/configs/privateConfigParam-tf.good
  test/compflags/configs/privateConfigParam-tt.good
  test/compflags/configs/privateConfigParam.chpl
  test/compflags/configs/privateConfigParam.compopts
  test/compflags/configs/privateConfigParam.good
  test/execflags/configs/privateconfigs-eee.good
  test/execflags/configs/privateconfigs-fff.good
  test/execflags/configs/privateconfigs-ggg.good
  test/execflags/configs/privateconfigs-help-set.comm-none.good
  test/execflags/configs/privateconfigs-help-set.good
  test/execflags/configs/privateconfigs-help.comm-none.good
  test/execflags/configs/privateconfigs-help.good
  test/execflags/configs/privateconfigs.chpl
  test/execflags/configs/privateconfigs.execopts
  test/execflags/configs/privateconfigs.good
  test/visibility/private/config/constants/accessesOther.compopts
  test/visibility/private/config/constants/definesPrivate.execopts
  test/visibility/private/config/constants/ensureStillVisible.compopts
  test/visibility/private/config/constants/multipleDecl.compopts
  test/visibility/private/config/params/accessesOther.compopts
  test/visibility/private/config/params/definesPrivate.compopts
  test/visibility/private/config/params/ensureStillVisible.compopts
  test/visibility/private/config/params/multipleDecl.compopts
  test/visibility/private/config/variables/accessesOther.compopts
  test/visibility/private/config/variables/definesPrivate.execopts
  test/visibility/private/config/variables/ensureStillVisible.compopts
  test/visibility/private/config/variables/multipleDecl.compopts
Labels: stat: Needs Design Review

#14707 Fix flag suggestion for e.g. `chpl -`
  compiler/main/arg.cpp
  test/compflags/ferguson/suggestions.6.good
  test/compflags/ferguson/suggestions.7.good
  test/compflags/ferguson/suggestions.compopts
Labels: stat: Ready to Merge

#14611 Switch FFTW package to private SysCTypes
  modules/packages/FFTW.chpl
Labels: stat: cla signed

#14249 Add approximate equality function
  modules/standard/Math.chpl
  test/library/standard/Math/isclose.chpl
  test/library/standard/Math/isclose.good
Labels: stat: cla signed

#14760 Improve error messages related to renaming a module upon its use
  compiler/include/scopeResolve.h
  compiler/passes/scopeResolve.cpp
  test/visibility/rename/renameUsedMod/renameModRenameSymBadAccess2.bad
  test/visibility/rename/renameUsedMod/renameModRenameSymBadAccess2.future
  test/visibility/rename/renameUsedMod/renameSameNameConflict.bad
  test/visibility/rename/renameUsedMod/renameSameNameConflict.future
  test/visibility/rename/renameUsedMod/renameSameNameConflict2.bad
  test/visibility/rename/renameUsedMod/renameSameNameConflict2.future
  test/visibility/rename/renameUsedMod/renameSameNameConflict3.bad
  test/visibility/rename/renameUsedMod/renameSameNameConflict3.future
Labels: area: Compiler, area: Tests, stat: Ready to Merge

#14784 Add #include to use NULL as the default value in a function declaration
  compiler/include/scopeResolve.h
Labels: area: Compiler
