Repository chapel-lang/chapel, pull requests merged in 2020-02, with the labels that each got.

#14857 Grammar fixes
  doc/rst/developer/README.partialInstantiation
Labels: stat: cla signed

#14859 Extend python interoperability skipif for when CHPL_LIB_PIC not set
  test/interop/python/SKIPIF
  test/interop/python/chapelBytes/SKIPIF
  test/interop/python/chapelStrings/SKIPIF
  test/interop/python/multilocale/SKIPIF
  test/interop/python/multilocale/chapelBytes/SKIPIF
  test/interop/python/multilocale/chapelStrings/SKIPIF
  test/interop/python/noLibFlag/SKIPIF
Labels: area: Tests

#14869 Add pragma to DistributedDeque and DistributedBag
  modules/packages/DistributedBag.chpl
  modules/packages/DistributedDeque.chpl
Labels: stat: Ready to Merge, stat: cla signed

#14828 Extend LinearAlgebra.eig() to support complex types
  modules/packages/LinearAlgebra.chpl
  test/library/packages/LinearAlgebra/correctness/testEigen.chpl
Labels: stat: cla signed

#14872 Add throws tags to functions in Random module
  modules/standard/Random.chpl
Labels: stat: cla signed

#14900 blocks documentation if interrupt by single line comment
  compiler/parser/parser.cpp
  test/chpldoc/basics/interruptingSingleComment.doc.bad
  test/chpldoc/basics/interruptingSingleComment.doc.future
Labels: stat: cla signed

#14903 Add 1st draft of copy elision
  compiler/include/driver.h
  compiler/main/driver.cpp
  compiler/resolution/AutoDestroyScope.cpp
  test/classes/initializers/compilerGenerated/uses-in-intent.good
  test/classes/initializers/initequals/generics.chpl
  test/classes/initializers/initequals/vector.chpl
  test/classes/initializers/memory/explicit-const-in.good
  test/classes/initializers/promotion/noPromoteCopyInit.chpl
  test/expressions/if-expr/nested-mem-management.chpl
  test/expressions/if-expr/nested-mem-management.good
  test/extern/ferguson/c-array/c-array-record.chpl
  test/extern/ferguson/c-array/c-array-record.good
  test/functions/ferguson/in-default-record.good
  test/functions/ferguson/in-intent.good
  test/functions/iterators/ferguson/no-leak-yield-record.chpl
  test/statements/ferguson/var-init-records.chpl
  test/types/records/copy-elision/copy-elision-behavior.chpl
  test/types/records/copy-elision/copy-elision-behavior.compopts
  test/types/records/copy-elision/copy-elision-behavior.no.good
  test/types/records/copy-elision/copy-elision-behavior.yes.good
  test/types/records/copy-elision/copy-elision-default-behavior.chpl
  test/types/records/copy-elision/copy-elision-default-behavior.compopts
  test/types/records/copy-elision/copy-elision-default-behavior.good
  test/types/records/copy-elision/copy-elision-default.chpl
  test/types/records/copy-elision/copy-elision-default.good
  test/types/records/copy-elision/copy-elision.chpl
  test/types/records/copy-elision/copy-elision.good
  test/types/records/expiring/challenges.chpl
  test/types/records/expiring/challenges.good
  test/types/records/expiring/deinit-points.good
  test/types/records/ferguson/copy-report.chpl
  test/types/records/ferguson/copy-report.good
  test/types/records/ferguson/expiring-value-alias.chpl
  test/types/records/ferguson/expiring-value-alias.good
  test/users/ferguson/refcnt.good
  util/chpl-completion.bash
Labels: stat: Ready to Merge

#14916 Add basic support for renaming a module when importing it
  compiler/AST/ImportStmt.cpp
  compiler/AST/UseStmt.cpp
  compiler/AST/build.cpp
  compiler/AST/stmt.cpp
  compiler/include/ImportStmt.h
  compiler/include/UseStmt.h
  compiler/include/build.h
  compiler/include/stmt.h
  compiler/parser/bison-chapel.cpp
  compiler/parser/chapel.ypp
  compiler/passes/ResolveScope.cpp
  compiler/passes/scopeResolve.cpp
  compiler/resolution/visibleFunctions.cpp
  test/visibility/import/rename/new_name.chpl
  test/visibility/import/rename/new_name.good
  test/visibility/import/rename/new_name_errors.chpl
  test/visibility/import/rename/new_name_errors.good
  test/visibility/import/rename/new_name_errors2.chpl
  test/visibility/import/rename/new_name_errors2.good
  test/visibility/import/rename/new_name_errors3.chpl
  test/visibility/import/rename/new_name_errors3.good
  test/visibility/import/rename/new_name_errors4.chpl
  test/visibility/import/rename/new_name_errors4.good
  test/visibility/import/rename/same_name.chpl
  test/visibility/import/rename/same_name.good
  test/visibility/import/rename/same_name_conflict.chpl
  test/visibility/import/rename/same_name_conflict.good
  test/visibility/import/rename/same_name_in_mod.chpl
  test/visibility/import/rename/same_name_in_mod.good
  test/visibility/import/rename/same_name_in_mod2.chpl
  test/visibility/import/rename/same_name_in_mod2.good
Labels: area: Compiler, area: Language, area: Tests, stat: Needs Code Review

#14881 Improve mason update output
  test/mason/env/mason-registry.good
  test/mason/mason-example-with-opts/mason-example.good
  test/mason/mason-example/mason-example.good
  test/mason/mason-test/mason-test.good
  test/mason/run/mason-run.good
  test/mason/subdir-commands/mason-run.good
  tools/mason/MasonUpdate.chpl
Labels: stat: Ready to Merge, stat: cla signed

#14892 add --project-version flag for chpldoc
  compiler/include/docsDriver.h
  compiler/main/docsDriver.cpp
  compiler/passes/docs.cpp
  man/chpldoc.rst
  test/chpldoc/compflags/version/PREDIFF
  test/chpldoc/compflags/version/projectVersion.doc.catfiles
  test/chpldoc/compflags/version/projectVersion.doc.chpl
  test/chpldoc/compflags/version/projectVersion.doc.chpldocopts
  test/chpldoc/compflags/version/projectVersion.doc.cleanfiles
  test/chpldoc/compflags/version/projectVersion.dotEnd.doc.good
  test/chpldoc/compflags/version/projectVersion.invalidCharacter.doc.good
  test/chpldoc/compflags/version/projectVersion.invalidTag.doc.good
  test/chpldoc/compflags/version/projectVersion.lessDots.doc.good
  test/chpldoc/compflags/version/projectVersion.missingNumbers.doc.good
  test/chpldoc/compflags/version/projectVersion.no-tag.doc.good
  test/chpldoc/compflags/version/projectVersion.no-tag.multi.doc.good
  test/chpldoc/compflags/version/projectVersion.no-tag.single.doc.good
  test/chpldoc/compflags/version/projectVersion.tag.alpha.doc.good
  test/chpldoc/compflags/version/projectVersion.tag.beta.doc.good
  test/chpldoc/compflags/version/projectVersion.tag.rc.doc.good
  test/compflags/thomasvandoren/chpldoc.doc.good
  third-party/chpl-venv/chpldoc-sphinx-project/source/conf.py
Labels: stat: cla signed

#14820 mason init
  doc/rst/tools/mason/mason.rst
  test/mason/masonInit/.gitignore
  test/mason/masonInit/MasonInitTest5.chpl
  test/mason/masonInit/MasonInitTest5.compopts
  test/mason/masonInit/MasonInitTest5.good
  test/mason/masonInit/masonInitModifyToml.chpl
  test/mason/masonInit/masonInitModifyToml.compopts
  test/mason/masonInit/masonInitModifyToml.good
  test/mason/masonInit/masonInitPathTest.chpl
  test/mason/masonInit/masonInitPathTest.compopts
  test/mason/masonInit/masonInitPathTest.good
  test/mason/masonInit/masonInitTest.chpl
  test/mason/masonInit/masonInitTest.compopts
  test/mason/masonInit/masonInitTest.good
  test/mason/masonInit/masonInitTest2.chpl
  test/mason/masonInit/masonInitTest2.compopts
  test/mason/masonInit/masonInitTest2.good
  test/mason/masonInit/masonInitTest3.chpl
  test/mason/masonInit/masonInitTest3.compopts
  test/mason/masonInit/masonInitTest3.good
  test/mason/masonInit/masonInitTest4.chpl
  test/mason/masonInit/masonInitTest4.compopts
  test/mason/masonInit/masonInitTest4.good
  tools/mason/MasonHelp.chpl
  tools/mason/MasonInit.chpl
  tools/mason/MasonModify.chpl
  tools/mason/MasonNew.chpl
  tools/mason/mason.chpl
Labels: stat: cla signed

#14994 fix project version test files
  test/chpldoc/compflags/version/PREDIFF
  test/chpldoc/compflags/version/SKIPIF
  test/chpldoc/compflags/version/projectVersion.no-tag.doc.good
  test/chpldoc/compflags/version/projectVersion.no-tag.multi.doc.good
  test/chpldoc/compflags/version/projectVersion.no-tag.single.doc.good
  test/chpldoc/compflags/version/projectVersion.tag.alpha.doc.good
  test/chpldoc/compflags/version/projectVersion.tag.beta.doc.good
  test/chpldoc/compflags/version/projectVersion.tag.rc.doc.good
Labels: stat: cla signed

#15004 Fix oversight where import statements were not handled in isMoreVisible
  compiler/resolution/functionResolution.cpp
Labels: area: Compiler
