Repository chapel-lang/chapel, pull requests merged in 2021-12, with the labels that each got.

#18795 compiler/next: implement more conversions
  compiler/next/include/chpl/resolution/can-pass.h
  compiler/next/include/chpl/resolution/resolution-types.h
  compiler/next/include/chpl/types/BasicClassType.h
  compiler/next/include/chpl/types/ClassTypeDecorator.h
  compiler/next/include/chpl/types/CompositeType.h
  compiler/next/include/chpl/types/QualifiedType.h
  compiler/next/include/chpl/types/Type.h
  compiler/next/include/chpl/uast/Formal.h
  compiler/next/include/chpl/uast/Function.h
  compiler/next/include/chpl/uast/IntentList.h
  compiler/next/include/chpl/uast/TaskVar.h
  compiler/next/include/chpl/uast/TupleDecl.h
  compiler/next/include/chpl/uast/Variable.h
  compiler/next/lib/resolution/can-pass.cpp
  compiler/next/lib/resolution/resolution-queries.cpp
  compiler/next/lib/types/BasicClassType.cpp
  compiler/next/lib/types/CMakeLists.txt
  compiler/next/lib/types/ClassTypeDecorator.cpp
  compiler/next/lib/types/CompositeType.cpp
  compiler/next/lib/types/Param.cpp
  compiler/next/lib/types/QualifiedType.cpp
  compiler/next/lib/types/Type.cpp
  compiler/next/test/parsing/testParseTupleVar.cpp
  compiler/next/test/resolution/testCanPass.cpp
  compiler/next/test/resolution/testParams.cpp
  compiler/next/test/resolution/testTypeConstruction.cpp
  compiler/next/test/uast/testConsistentEnums.cpp
Labels: post-release

#18815 update libtoml version for mason-external test
  test/mason/mason-external/libtomlc99/Mason.toml
  test/mason/mason-external/libtomlc99/mason-external.chpl
Labels: area: Tools, area: Tests, post-release

#18783 Add stringify template to query framework
  compiler/include/misc.h
  compiler/next/include/chpl/parsing/FileContents.h
  compiler/next/include/chpl/queries/Context-detail.h
  compiler/next/include/chpl/queries/Context.h
  compiler/next/include/chpl/queries/ID.h
  compiler/next/include/chpl/queries/Location.h
  compiler/next/include/chpl/queries/UniqueString.h
  compiler/next/include/chpl/queries/query-impl.h
  compiler/next/include/chpl/queries/stringify-functions.h
  compiler/next/include/chpl/resolution/resolution-types.h
  compiler/next/include/chpl/resolution/scope-types.h
  compiler/next/include/chpl/types/BasicClassType.h
  compiler/next/include/chpl/types/ClassTypeDecorator.h
  compiler/next/include/chpl/types/CompositeType.h
  compiler/next/include/chpl/types/Param.h
  compiler/next/include/chpl/types/QualifiedType.h
  compiler/next/include/chpl/types/Type.h
  compiler/next/include/chpl/uast/ASTNode.h
  compiler/next/include/chpl/uast/ASTTag.h
  compiler/next/include/chpl/uast/BuilderResult.h
  compiler/next/include/chpl/uast/Expression.h
  compiler/next/include/chpl/uast/Function.h
  compiler/next/include/chpl/util/break.h
  compiler/next/lib/queries/Context.cpp
  compiler/next/lib/types/QualifiedType.cpp
  compiler/next/lib/util/CMakeLists.txt
  compiler/next/lib/util/Makefile.include
  compiler/next/lib/util/break.cpp
  compiler/next/test/resolution/testPoi.cpp
  compiler/util/misc.cpp
Labels: area: Compiler, post-release

#18798 Allow non-nil to nil in type arguments
  compiler/resolution/ResolutionCandidate.cpp
  compiler/resolution/functionResolution.cpp
  test/classes/nilability/non-nil-subtype2.chpl
  test/classes/nilability/non-nil-subtype2.good
  test/functions/typeMethods/anymanaged.good
Labels: post-release

#18800 Adjust chpl-cache initialization logic
  runtime/src/chpl-cache.c
Labels: post-release

#18765 Implement completion counters
  runtime/src/comm/ofi/comm-ofi.c
Labels: area: Runtime

#18784 Argument names changed/optimised
  modules/standard/BigInteger.chpl
  test/deprecated/BigInteger/deprecateCongruent2expP.chpl
  test/deprecated/BigInteger/deprecateCongruent2expP.good
  test/deprecated/BigInteger/deprecateCongruentP.chpl
  test/deprecated/BigInteger/deprecateCongruentP.good
  test/deprecated/BigInteger/deprecateDivexact.chpl
  test/deprecated/BigInteger/deprecateDivexact.good
  test/deprecated/BigInteger/deprecateDivisible2expP.chpl
  test/deprecated/BigInteger/deprecateDivisible2expP.good
  test/deprecated/BigInteger/deprecateDivisibleP.chpl
  test/deprecated/BigInteger/deprecateDivisibleP.good
  test/library/standard/GMP/congruence.chpl
  test/library/standard/GMP/ldelaney/gmp_Bigint_division.chpl
  test/library/standard/GMP/ldelaney/gmp_Bigint_division.good
Labels: area: Libraries / Modules, stat: Ready to Merge, post-release

#18902 Fix deprecation failure with `--baseline`
  test/deprecated/BigInteger/deprecateDivisible2expP.chpl
Labels: area: Tests
