Repository chapel-lang/chapel, pull requests merged in 2021-01, with the labels that each got.

#16961 Implement Parallel TimSort Algorithm
  modules/packages/Sort.chpl
  test/library/packages/Sort/correctness/correctness.chpl
  test/library/packages/Sort/performance/performance.chpl
  test/library/packages/Sort/performance/performance.good
  test/library/packages/Sort/performance/performance.perfexecopts
  test/library/packages/Sort/performance/sort-performance-explorer.chpl
  test/library/packages/Sort/performance/sorts-linearithmic.graph
Labels: stat: Ready to Merge

#17038 Add three tests locking in that type methods behave the same as regular methods
  test/visibility/except/blockSecondaryTypeMethod.chpl
  test/visibility/except/blockSecondaryTypeMethod.good
  test/visibility/import/enablesUnqualified/canSeeSecondaryTypeMethod.chpl
  test/visibility/import/enablesUnqualified/canSeeSecondaryTypeMethod.good
  test/visibility/only/canSeeSecondaryTypeMethod.chpl
  test/visibility/only/canSeeSecondaryTypeMethod.good
Labels: area: Tests, stat: Ready to Merge

#16996 Improve sys_getenv documentation
  modules/standard/Sys.chpl
Labels: area: Docs, area: Libraries / Modules, stat: Needs Code Review, stat: Needs Testing
