Repository chapel-lang/chapel, pull requests merged in 2021-11, with the labels that each got.

#18679 Deprecate bigint.numLimbs() and bigint.get_limbn()
  modules/standard/BigInteger.chpl
  test/deprecated/BigInteger/bigint_getlimbs.chpl
  test/deprecated/BigInteger/bigint_getlimbs.good
  test/library/standard/GMP/ferguson/bigint_getlimbs.good
Labels: area: Libraries / Modules, area: Docs, area: Tests, stat: Needs Testing

#18684 stop having 'notcompiler' make 'chpldoc'
  Makefile
Labels: post-release

#18426 Respect CHPL_LAUNCHER_ACCOUNT without sbatch
  runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h
Labels: post-release

#18705 Add `lambda` keyword in highlight files
  highlight/emacs/chpl-mode.el
  highlight/vim/syntax/chpl.vim
Labels: area: Tools, stat: Needs Testing

#16704 Shared Memory Concurrent Map
  modules/Makefile
  modules/packages/ConcurrentMap.chpl
  test/library/packages/ConcurrentMap/testAddSet.chpl
  test/library/packages/ConcurrentMap/testAddSet.good
  test/library/packages/ConcurrentMap/testClear.chpl
  test/library/packages/ConcurrentMap/testClear.good
  test/library/packages/ConcurrentMap/testContains.chpl
  test/library/packages/ConcurrentMap/testContains.good
  test/library/packages/ConcurrentMap/testEquality.chpl
  test/library/packages/ConcurrentMap/testEquality.good
  test/library/packages/ConcurrentMap/testExtend.chpl
  test/library/packages/ConcurrentMap/testExtend.good
  test/library/packages/ConcurrentMap/testGetRemove.chpl
  test/library/packages/ConcurrentMap/testGetRemove.good
  test/library/packages/ConcurrentMap/utilFunctions.chpl
  test/library/packages/ConcurrentMap/utilFunctions.notest
Labels: post-release, stat: cla signed
