Repository chapel-lang/chapel, pull requests merged in 2021-09, with the labels that each got.

#18411 Adjust this test to use operator methods
  test/library/standard/Set/setCommTest.chpl
Labels: area: Tests, stat: Needs Code Review

#18418 Add technote for manage and add 'manage' to keyword list in spec
  doc/rst/language/spec/lexical-structure.rst
  doc/rst/technotes/index.rst
  doc/rst/technotes/manage.rst
Labels: area: Docs

#18456 Fix an issue where this test wasn't completely looking in the right place
  test/chpldoc/nodoc/noDocPlease.doc.catfiles
  test/chpldoc/nodoc/noDocPlease.doc.good
Labels: area: Tests, stat: Ready to Merge

#18439 Remove deprecated text about arrays from the set tech note
  doc/rst/technotes/sets.rst
Labels: post-release

#18355 Change c2chapel record generation idiom
  tools/c2chapel/c2chapel.py
  tools/c2chapel/test/arrayDecl.chpl
  tools/c2chapel/test/chapelKeywords.chpl
  tools/c2chapel/test/enum.chpl
  tools/c2chapel/test/fileGlobals.chpl
  tools/c2chapel/test/fnPointers.chpl
  tools/c2chapel/test/gnuTest.chpl
  tools/c2chapel/test/miscTypedef.chpl
  tools/c2chapel/test/nestedStruct.chpl
  tools/c2chapel/test/opaqueStruct.chpl
  tools/c2chapel/test/simpleRecords.chpl
Labels: post-release

#18412 Fix bug with implementation of `bigint.pow()` when the exponent is negative
  modules/standard/BigInteger.chpl
  test/library/standard/GMP/powCheck.chpl
  test/library/standard/GMP/powCheck.good
Labels: area: Libraries / Modules, area: Tests, stat: Needs Code Review, post-release

#18424 remove debugging writeln statements from argument parser
  modules/packages/ArgumentParser.chpl
Labels: post-release

#18481 Add documentation of `bigint.pow` method in BigInteger module and fix typo
  modules/standard/BigInteger.chpl
Labels: area: Libraries / Modules, area: Docs, stat: Needs Code Review

#18409 Incorporate ArgumentParser in mason run and mason build subcommands
  doc/rst/tools/mason/mason.rst
  test/library/packages/ArgumentParser/ArgumentParserTests.chpl
  test/library/packages/ArgumentParser/ArgumentParserTests.good
  test/mason/build/noDeps.chpl
  test/mason/mason-example-with-opts/mason-example.chpl
  test/mason/mason-example/mason-example.chpl
  test/mason/mason-external/libtomlc99/mason-external.chpl
  test/mason/run/mason-run.chpl
  test/mason/subdir-commands/mason-run.chpl
  tools/mason/MasonBuild.chpl
  tools/mason/MasonRun.chpl
  tools/mason/mason.chpl
Labels: post-release

#18437 update spack version to 0.16.3
  test/mason/mason-external/COMPOPTS
  test/mason/mason-external/libtomlc99/mason-external.good
  test/mason/mason-external/spackVersionCompare.chpl
  test/mason/mason-external/spackVersionCompare.good
  tools/mason/MasonExternal.chpl
  tools/mason/MasonUpdate.chpl
  tools/mason/MasonUtils.chpl
Labels: post-release
