Repository chapel-lang/chapel, pull requests merged in 2022-01, with the labels that each got.

#18918 Add documentation for renamed bigint methods
  modules/standard/BigInteger.chpl
Labels: area: Libraries / Modules, area: Docs, stat: Needs Code Review, stat: Needs Testing

#18884 Minor improvements to `greptests`
  util/devel/greptests
Labels: stat: Ready to Merge

#17960 [GSoC 2021] Socket Library
  modules/Makefile
  modules/packages/Socket.chpl
  modules/standard/Sys.chpl
  test/library/packages/Socket.skipif
  test/library/packages/Socket/connectblocking.chpl
  test/library/packages/Socket/connectblocking.good
  test/library/packages/Socket/connecttimeout.chpl
  test/library/packages/Socket/connecttimeout.good
  test/library/packages/Socket/ipaddr.chpl
  test/library/packages/Socket/ipaddr.good
  test/library/packages/Socket/ipfamily.chpl
  test/library/packages/Socket/ipfamily.good
  test/library/packages/Socket/ipv6/SKIPIF
  test/library/packages/Socket/ipv6/connect_blocking_ipv6.chpl
  test/library/packages/Socket/ipv6/connect_blocking_ipv6.good
  test/library/packages/Socket/ipv6/connect_timeout_ipv6.chpl
  test/library/packages/Socket/ipv6/connect_timeout_ipv6.good
  test/library/packages/Socket/ipv6/listen_ipv6.chpl
  test/library/packages/Socket/ipv6/listen_ipv6.good
  test/library/packages/Socket/ipv6/udpio_ipv6.chpl
  test/library/packages/Socket/ipv6/udpio_ipv6.good
  test/library/packages/Socket/listen.chpl
  test/library/packages/Socket/listen.good
  test/library/packages/Socket/networkoptimization.chpl
  test/library/packages/Socket/networkoptimization.good
  test/library/packages/Socket/tcpio.chpl
  test/library/packages/Socket/tcpio.good
  test/library/packages/Socket/udpio_ipv4.chpl
  test/library/packages/Socket/udpio_ipv4.good
Labels: post-release

#18168 [GSoC] Go-Style Channels
  modules/packages/Channel.chpl
  test/library/packages/Channel/correctness/bufferedSendRecv.chpl
  test/library/packages/Channel/correctness/bufferedSendRecv.good
  test/library/packages/Channel/correctness/channelIterator.chpl
  test/library/packages/Channel/correctness/channelIterator.good
  test/library/packages/Channel/correctness/classChannel.chpl
  test/library/packages/Channel/correctness/classChannel.good
  test/library/packages/Channel/correctness/closeClosedChannel.chpl
  test/library/packages/Channel/correctness/closeClosedChannel.good
  test/library/packages/Channel/correctness/closedRecv.chpl
  test/library/packages/Channel/correctness/closedRecv.good
  test/library/packages/Channel/correctness/closedSend.chpl
  test/library/packages/Channel/correctness/closedSend.good
  test/library/packages/Channel/correctness/coforallSelectRecv.chpl
  test/library/packages/Channel/correctness/coforallSelectRecv.good
  test/library/packages/Channel/correctness/coforallSelectSendRecv.chpl
  test/library/packages/Channel/correctness/coforallSelectSendRecv.good
  test/library/packages/Channel/correctness/coforallSendRecv.chpl
  test/library/packages/Channel/correctness/coforallSendRecv.good
  test/library/packages/Channel/correctness/recordChannel.chpl
  test/library/packages/Channel/correctness/recordChannel.good
  test/library/packages/Channel/correctness/select.chpl
  test/library/packages/Channel/correctness/select.good
  test/library/packages/Channel/correctness/sharedClassChannel.chpl
  test/library/packages/Channel/correctness/sharedClassChannel.good
  test/library/packages/Channel/correctness/unbufferedSendRecv.chpl
  test/library/packages/Channel/correctness/unbufferedSendRecv.good
  test/library/packages/Channel/performance/chanContended.chpl
  test/library/packages/Channel/performance/chanContended.good
  test/library/packages/Channel/performance/chanUncontended.chpl
  test/library/packages/Channel/performance/chanUncontended.good
  test/library/packages/Channel/performance/selectSyncContended.chpl
  test/library/packages/Channel/performance/selectSyncContended.good
  test/library/packages/Channel/performance/selectUncontended.chpl
  test/library/packages/Channel/performance/selectUncontended.good
Labels: post-release

#19085 Add a future for #18992 (chpldoc truncating longer reals)
  test/chpldoc/globals/realLength.doc.bad
  test/chpldoc/globals/realLength.doc.catfiles
  test/chpldoc/globals/realLength.doc.chpl
  test/chpldoc/globals/realLength.doc.future
  test/chpldoc/globals/realLength.doc.good
Labels: area: Tests

#19097 Update references to SSCA2 in the GRAPHFILES
  test/GRAPHFILES
  test/ML-GRAPHFILES
Labels: area: Tests, stat: Needs Code Review

#19099 Change line number searched for spectral-norm verification
  test/studies/shootout/spectral-norm/lydia/spectral-norm-barrier.perfkeys
  test/studies/shootout/spectral-norm/lydia/spectral-norm-double-time.perfkeys
  test/studies/shootout/spectral-norm/lydia/spectral-norm-no-reduct.perfkeys
  test/studies/shootout/spectral-norm/lydia/spectral-norm-specify-step.perfkeys
  test/studies/shootout/spectral-norm/lydia/spectral-norm.perfkeys
  test/studies/shootout/spectral-norm/sidelnik/spectralnorm.perfkeys
  test/studies/shootout/spectral-norm/sidelnik/spectralnorm_2.perfkeys
Labels: area: Tests, stat: Needs Code Review
