Repository chapel-lang/chapel, pull requests merged in 2022-12, with the labels that each got.

#21131 Suppress the open* test failures when run as a windows service
  test/library/standard/IO/open/checkPermissions.suppressif
  test/library/standard/IO/openreader/checkPermissions.suppressif
  test/library/standard/IO/openwriter/checkPermissions.suppressif
Labels: area: Tests / Benchmarks

#21153 Update the tmbundle update instructions for testing highlight changes.
  highlight/tmbundle/README.md
Labels: area: Docs, area: Tools, stat: Ready to Merge

#21116 Add explicit return types for the majority of operators in the BigInteger module
  modules/standard/BigInteger.chpl
Labels: area: Libraries / Modules, area: Docs, stat: Needs Code Review

#21182 dyno: fill in details to call init, deinit, etc
  frontend/include/chpl/framework/UniqueString-detail.h
  frontend/include/chpl/framework/UniqueString.h
  frontend/include/chpl/parsing/parsing-queries.h
  frontend/include/chpl/resolution/can-pass.h
  frontend/include/chpl/resolution/copy-elision.h
  frontend/include/chpl/resolution/resolution-queries.h
  frontend/include/chpl/resolution/resolution-types.h
  frontend/include/chpl/types/QualifiedType.h
  frontend/lib/parsing/parsing-queries.cpp
  frontend/lib/resolution/InitResolver.cpp
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/Resolver.h
  frontend/lib/resolution/VarScopeVisitor.cpp
  frontend/lib/resolution/VarScopeVisitor.h
  frontend/lib/resolution/call-init-deinit.cpp
  frontend/lib/resolution/copy-elision.cpp
  frontend/lib/resolution/default-functions.cpp
  frontend/lib/resolution/resolution-queries.cpp
  frontend/lib/resolution/resolution-types.cpp
  frontend/lib/resolution/split-init.cpp
  frontend/test/framework/testUniqueString.cpp
  frontend/test/resolution/CMakeLists.txt
  frontend/test/resolution/testCallInitDeinit.cpp
  frontend/test/resolution/testInteractive.cpp
  frontend/test/resolution/testLoopIndexVars.cpp
  frontend/test/resolution/testResolveNew.cpp
  frontend/test/resolution/testSplitInit.cpp
  frontend/test/resolution/testTuples.cpp
  frontend/test/resolution/testTypeConstruction.cpp
  frontend/test/resolution/testTypeQueries.cpp
Labels: post-release

#21204 alternate `distributedMap` prototype
  test/library/draft/DistributedMap/v3/ChainTable.chpl
  test/library/draft/DistributedMap/v3/ChainTable.notest
  test/library/draft/DistributedMap/v3/DistributedMap.chpl
  test/library/draft/DistributedMap/v3/DistributedMap.notest
  test/library/draft/DistributedMap/v3/collisions.chpl
  test/library/draft/DistributedMap/v3/collisions.good
  test/library/draft/DistributedMap/v3/distMapFill.chpl
  test/library/draft/DistributedMap/v3/distMapFill.comm-none.good
  test/library/draft/DistributedMap/v3/distMapFill.good
  test/library/draft/DistributedMap/v3/distMapFill.numlocales
  test/library/draft/DistributedMap/v3/distMapInit.chpl
  test/library/draft/DistributedMap/v3/distMapInit.good
  test/library/draft/DistributedMap/v3/rehash.chpl
  test/library/draft/DistributedMap/v3/rehash.good
  test/library/draft/DistributedMap/v3/staticMemManager.chpl
  test/library/draft/DistributedMap/v3/staticMemManager.good
  test/library/draft/DistributedMap/v3/staticMemManager.notest
Labels: post-release
