Repository chapel-lang/chapel, pull requests merged in 2022-09, with the labels that each got.

#20574 Deprecate the version of openwriter that takes start and/or end arguments
  modules/standard/IO.chpl
  test/deprecated/IO/.gitignore
  test/deprecated/IO/openwriterStartEnd.chpl
  test/deprecated/IO/openwriterStartEnd.cleanfiles
  test/deprecated/IO/openwriterStartEnd.good
  test/library/standard/IO/openwriterEndBug.bad
  test/library/standard/IO/openwriterStartBug.bad
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Ready to Merge

#20612 Add documentation for the unstable keyword
  doc/rst/developer/bestPractices/Unstable.rst
  doc/rst/developer/bestPractices/index.rst
Labels: area: Docs, stat: Ready to Merge

#20618 Update Potpourri.rst for changes to the util/devel/grep scripts
  doc/rst/developer/bestPractices/Potpourri.rst
Labels: area: Docs, stat: Ready to Merge

#20684 Remove (dyno-based) chpldoc sources from `chpl`'s tags/ebrowse output
  compiler/dyno/tools/chpldoc/Makefile.include
Labels: post-release

#20697 Deprecated file.localesForRegion in I/O module
  modules/standard/IO.chpl
  test/deprecated/IO/localesForRegion.chpl
  test/deprecated/IO/localesForRegion.good
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Needs Testing

#20690 Add flag to testInteractive to time queries
  compiler/dyno/test/resolution/testInteractive.cpp
Labels: post-release, area: Dyno

#20669 Fix "git" formatting in mason docs
  doc/rst/mason-packages/guide/gitdependencies.rst
Labels: post-release

#20677 dyno: Improve scope resolution of internal/standard modules
  compiler/AST/AggregateType.cpp
  compiler/AST/wellknown.cpp
  compiler/dyno/include/chpl/resolution/resolution-queries.h
  compiler/dyno/lib/resolution/Resolver.cpp
  compiler/dyno/lib/resolution/Resolver.h
  compiler/dyno/lib/resolution/resolution-queries.cpp
  compiler/dyno/lib/resolution/scope-queries.cpp
  compiler/dyno/test/resolution/testFieldAccess.cpp
  compiler/dyno/test/resolution/testFindDecl.cpp
  compiler/include/driver.h
  compiler/main/driver.cpp
  compiler/parser/parser.cpp
  compiler/passes/convert-uast.cpp
  compiler/passes/scopeResolve.cpp
  util/chpl-completion.bash
Labels: post-release

#20670 Replace explicit ends of the region in the fileIO primer with the count operator
  test/release/examples/primers/fileIO.chpl
Labels: area: Tests / Benchmarks, stat: Needs Testing, post-release

#20563 Richer array literal element type inference
  compiler/dyno/include/chpl/uast/PragmaList.h
  compiler/resolution/resolveFunction.cpp
  doc/rst/language/spec/arrays.rst
  modules/internal/ChapelArray.chpl
  modules/internal/ChapelDomain.chpl
  test/arrays/bradc/inferArrayOfDerivedType.bad
  test/arrays/johnk/literals_bad_types.good
  test/arrays/literals/cStringLiteral.chpl
  test/arrays/literals/cStringLiteral.good
  test/arrays/literals/hetLiteralsNotUnifiable-local.chpl
  test/arrays/literals/hetLiteralsNotUnifiable-local.good
  test/arrays/literals/hetLiteralsNotUnifiable.chpl
  test/arrays/literals/hetLiteralsNotUnifiable.good
  test/arrays/literals/hetLiteralsUnifiable.chpl
  test/arrays/literals/hetLiteralsUnifiable.good
  test/arrays/literals/homogLiterals.chpl
  test/arrays/literals/homogLiterals.good
  test/release/examples/primers/arrays.chpl
Labels: post-release

#20715 Add tests I wrote as part of our experimenting last month with owned/shared
  test/classes/delete-free/shared/linkedListExample.chpl
  test/classes/delete-free/shared/linkedListExample.good
  test/classes/delete-free/undecorated-generic/generic-management-field-multiple.chpl
  test/classes/delete-free/undecorated-generic/generic-management-field-multiple.good
  test/classes/delete-free/undecorated-generic/generic-management-field.chpl
  test/classes/delete-free/undecorated-generic/generic-management-field.good
  test/classes/delete-free/undecorated-generic/generic-management-field2-borrow.chpl
  test/classes/delete-free/undecorated-generic/generic-management-field2-borrow.good
  test/classes/delete-free/undecorated-generic/generic-management-field2-unmanaged.chpl
  test/classes/delete-free/undecorated-generic/generic-management-field2-unmanaged.good
  test/classes/delete-free/undecorated-generic/generic-management-field2.chpl
  test/classes/delete-free/undecorated-generic/generic-management-field2.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#20667 chplspell dictionary updates
  util/devel/chplspell-dictionary
  util/devel/chplspell-dictionary.fileids.json
Labels: area: Tools, stat: Needs Code Review

#20699 list `numPUs` as an exeption to capitalization rule
  doc/rst/developer/bestPractices/StandardModuleStyle.rst
Labels: area: Docs, type: Chapel 2.0

#20713 Make 'use's transitively private by default in dyno
  compiler/dyno/include/chpl/resolution/scope-types.h
  compiler/dyno/lib/resolution/scope-queries.cpp
  compiler/dyno/test/resolution/testScopeResolve.cpp
Labels: area: Dyno

#20666 Fix typos
  compiler/dyno/include/chpl/framework/Context.h
  compiler/dyno/include/chpl/resolution/can-pass.h
  compiler/resolution/cleanups.cpp
  compiler/resolution/functionResolution.cpp
  doc/rst/mason-packages/guide/buildingandrunning.rst
  doc/rst/usingchapel/QUICKSTART.rst
  modules/standard/OS.chpl
  modules/standard/Types.chpl
  runtime/src/chpl-init.c
  runtime/src/gpu/cuda/gpu-cuda.c
  test/deprecated/deprecated-errors.good
  test/unstable/typeQueryFuncs.good
Labels: post-release
