Repository chapel-lang/chapel, pull requests merged in 2022-10, with the labels that each got.

#20762 Fixes to the documentation of `AutoMath.round` at Damian's suggestion
  modules/standard/AutoMath.chpl
Labels: area: Docs

#20752 Fix scope resolution of except lists in dyno
  compiler/dyno/lib/resolution/scope-queries.cpp
  compiler/dyno/test/resolution/testScopeResolve.cpp
  compiler/passes/ResolveScope.cpp
Labels: area: Dyno

#20609 Remove deprecated map operators
  modules/standard/Map.chpl
  test/deprecated/testMapAssignOps.chpl
  test/deprecated/testMapAssignOps.good
  test/deprecated/testMapOps.chpl
  test/deprecated/testMapOps.good
Labels: post-release

#20796 Add a tests tracking the behavior with forwarding
  test/classes/forwarding/constMethod.chpl
  test/classes/forwarding/constMethod.good
  test/classes/forwarding/forwardIterator.chpl
  test/classes/forwarding/forwardIterator.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#20806 Check conflicting imported symbol names in Dyno scope-resolver
  compiler/dyno/lib/resolution/scope-queries.cpp
  compiler/dyno/test/resolution/testScopeResolve.cpp
Labels: area: Dyno
