Repository chapel-lang/chapel, pull requests merged in 2022-07, with the labels that each got.

#19998 dyno: resolve param for loops
  compiler/dyno/include/chpl/resolution/resolution-types.h
  compiler/dyno/lib/resolution/Resolver.cpp
  compiler/dyno/lib/resolution/Resolver.h
  compiler/dyno/lib/resolution/resolution-types.cpp
  compiler/dyno/test/resolution/ResolvedVisitor.h
  compiler/dyno/test/resolution/testLoopIndexVars.cpp
Labels: post-release

#20080 Creating SHOC Tests for Triad
  test/gpu/native/studies/shoc/COMPOPTS
  test/gpu/native/studies/shoc/EXECOPTS
  test/gpu/native/studies/shoc/result.chpl
  test/gpu/native/studies/shoc/result.notest
  test/gpu/native/studies/shoc/triad.chpl
  test/gpu/native/studies/shoc/triad.good
  test/gpu/native/studies/shoc/triadalt1.chpl
  test/gpu/native/studies/shoc/triadalt1.good
  test/gpu/native/studies/shoc/triadalt2.chpl
  test/gpu/native/studies/shoc/triadalt2.good
  test/gpu/native/studies/shoc/triadchpl.chpl
  test/gpu/native/studies/shoc/triadchpl.good
Labels: post-release

#20176 Add two tests of fcfs as fields
  test/functions/firstClassFns/saveInField-nothing.bad
  test/functions/firstClassFns/saveInField-nothing.chpl
  test/functions/firstClassFns/saveInField-nothing.future
  test/functions/firstClassFns/saveInField-nothing.good
  test/functions/firstClassFns/saveInField.chpl
  test/functions/firstClassFns/saveInField.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#20180 Update future to reflect correction from Brad and Michael and add another test
  test/functions/firstClassFns/saveInField-nothing.future
  test/functions/firstClassFns/saveInField-nothing.good
  test/functions/firstClassFns/saveInField-properNothing.chpl
  test/functions/firstClassFns/saveInField-properNothing.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#20285 Fix bug where public/private use and import statements impacted documentation
  compiler/dyno/lib/parsing/bison-chpl-lib.cpp
  compiler/dyno/lib/parsing/bison-chpl-lib.h
  compiler/dyno/lib/parsing/chpl.ypp
  test/chpldoc/functions/importBeforeFunc.doc.catfiles
  test/chpldoc/functions/importBeforeFunc.doc.chpl
  test/chpldoc/functions/importBeforeFunc.doc.good
  test/chpldoc/functions/privateUseBug.doc.future
  test/chpldoc/functions/publicUseBeforeFunc.doc.catfiles
  test/chpldoc/functions/publicUseBeforeFunc.doc.chpl
  test/chpldoc/functions/publicUseBeforeFunc.doc.good
  test/chpldoc/functions/useExceptBeforeFunc.doc.catfiles
  test/chpldoc/functions/useExceptBeforeFunc.doc.chpl
  test/chpldoc/functions/useExceptBeforeFunc.doc.good
  test/chpldoc/functions/useExceptRenameBeforeFunc.doc.catfiles
  test/chpldoc/functions/useExceptRenameBeforeFunc.doc.chpl
  test/chpldoc/functions/useExceptRenameBeforeFunc.doc.good
  test/chpldoc/functions/useOnlyBeforeFunc.doc.catfiles
  test/chpldoc/functions/useOnlyBeforeFunc.doc.chpl
  test/chpldoc/functions/useOnlyBeforeFunc.doc.good
  test/chpldoc/functions/useOnlyRenameBeforeFunc.doc.catfiles
  test/chpldoc/functions/useOnlyRenameBeforeFunc.doc.chpl
  test/chpldoc/functions/useOnlyRenameBeforeFunc.doc.good
Labels: area: Compiler, area: Tests / Benchmarks

#20313 Update 3rd party packages relied upon by start_test and chpldoc
  third-party/chpl-venv/chpldoc-requirements2.txt
  third-party/chpl-venv/test-requirements.txt
Labels: area: Third-Party, area: BTR, area: Docs, area: Tools, area: Tests / Benchmarks, stat: Needs Code Review
