Repository chapel-lang/chapel, pull requests merged in 2023-06, with the labels that each got.

#22541 Add documentation categories to AutoMath and Math
  modules/standard/AutoMath.chpl
  modules/standard/Math.chpl
Labels: area: Libraries / Modules, area: Docs, stat: Needs Code Review

#22527 dyno: Change compiler global impl to match the compiler flags impl
  compiler/AST/type.cpp
  compiler/main/driver.cpp
  frontend/include/chpl/framework/Context.h
  frontend/include/chpl/framework/compiler-configuration.h
  frontend/lib/framework/Context.cpp
  frontend/lib/framework/compiler-configuration.cpp
  frontend/lib/resolution/resolution-queries.cpp
  frontend/test/resolution/testCompilationGlobals.cpp
Labels: post-release

#22501 dyno: improve support for the `class` typeclass.
  compiler/passes/convert-uast.cpp
  frontend/include/chpl/framework/all-global-strings.h
  frontend/include/chpl/types/AnyClassType.h
  frontend/include/chpl/types/BasicClassType.h
  frontend/include/chpl/types/ClassType.h
  frontend/include/chpl/types/ManageableType.h
  frontend/include/chpl/types/type-classes-list.h
  frontend/lib/resolution/InitResolver.cpp
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/call-init-deinit.cpp
  frontend/lib/resolution/can-pass.cpp
  frontend/lib/resolution/resolution-error-classes-list.cpp
  frontend/lib/resolution/resolution-queries.cpp
  frontend/lib/resolution/return-type-inference.cpp
  frontend/lib/resolution/try-catch-analysis.cpp
  frontend/lib/types/AnyClassType.cpp
  frontend/lib/types/CMakeLists.txt
  frontend/lib/types/ClassType.cpp
  frontend/lib/types/CompositeType.cpp
  frontend/lib/types/Type.cpp
  frontend/test/resolution/CMakeLists.txt
  frontend/test/resolution/testClassTypeclass.cpp
Labels: post-release

#22569 Fix error reporting for idxTypes upon range assignments and initializations
  modules/internal/ChapelRange.chpl
  test/domains/vass/params-and-assigns.chpl
  test/domains/vass/params-and-assigns.good
  test/types/range/cast-assign-init/casts-1.chpl
  test/types/range/cast-assign-init/casts-1.good
  test/types/range/cast-assign-init/casts-2.chpl
  test/types/range/cast-assign-init/casts-2.good
  test/types/range/cast-assign-init/illegal-assigns.0-1.good
  test/types/range/cast-assign-init/illegal-assigns.0-2.good
  test/types/range/cast-assign-init/illegal-assigns.0-3.good
  test/types/range/cast-assign-init/illegal-assigns.0-4.good
  test/types/range/cast-assign-init/illegal-assigns.0-5.good
  test/types/range/cast-assign-init/illegal-assigns.1-0.good
  test/types/range/cast-assign-init/illegal-assigns.1-2.good
  test/types/range/cast-assign-init/illegal-assigns.1-3.good
  test/types/range/cast-assign-init/illegal-assigns.1-4.good
  test/types/range/cast-assign-init/illegal-assigns.1-5.good
  test/types/range/cast-assign-init/illegal-assigns.2-1.good
  test/types/range/cast-assign-init/illegal-assigns.2-3.good
  test/types/range/cast-assign-init/illegal-assigns.2-4.good
  test/types/range/cast-assign-init/illegal-assigns.2-5.good
  test/types/range/cast-assign-init/illegal-assigns.3-1.good
  test/types/range/cast-assign-init/illegal-assigns.3-4.good
  test/types/range/cast-assign-init/illegal-assigns.3-5.good
  test/types/range/cast-assign-init/illegal-assigns.4-1.good
  test/types/range/cast-assign-init/illegal-assigns.4-5.good
  test/types/range/cast-assign-init/illegal-assigns.5-1.good
  test/types/range/cast-assign-init/illegal-assigns.chpl
  test/types/range/cast-assign-init/illegal-assigns.compopts
  test/types/range/cast-assign-init/illegal-assigns.ok.good
  test/types/range/cast-assign-init/illegal-inits.0-1.good
  test/types/range/cast-assign-init/illegal-inits.0-2.good
  test/types/range/cast-assign-init/illegal-inits.0-3.good
  test/types/range/cast-assign-init/illegal-inits.0-4.good
  test/types/range/cast-assign-init/illegal-inits.0-5.good
  test/types/range/cast-assign-init/illegal-inits.1-0.good
  test/types/range/cast-assign-init/illegal-inits.1-2.good
  test/types/range/cast-assign-init/illegal-inits.1-3.good
  test/types/range/cast-assign-init/illegal-inits.1-4.good
  test/types/range/cast-assign-init/illegal-inits.1-5.good
  test/types/range/cast-assign-init/illegal-inits.2-1.good
  test/types/range/cast-assign-init/illegal-inits.2-3.good
  test/types/range/cast-assign-init/illegal-inits.2-4.good
  test/types/range/cast-assign-init/illegal-inits.2-5.good
  test/types/range/cast-assign-init/illegal-inits.3-1.good
  test/types/range/cast-assign-init/illegal-inits.3-4.good
  test/types/range/cast-assign-init/illegal-inits.3-5.good
  test/types/range/cast-assign-init/illegal-inits.4-1.good
  test/types/range/cast-assign-init/illegal-inits.4-5.good
  test/types/range/cast-assign-init/illegal-inits.5-1.good
  test/types/range/cast-assign-init/illegal-inits.chpl
  test/types/range/cast-assign-init/illegal-inits.compopts
  test/types/range/cast-assign-init/illegal-inits.ok.good
  test/types/range/cast-assign-init/safeCasts.chpl
  test/types/range/cast-assign-init/safeCasts.good
Labels: stat: Ready to Merge

#22570 Minor map improvements
  modules/standard/Map.chpl
  test/classes/weakPointers/passiveCache.good
  test/library/standard/Map/types/MapTest.chpl
  test/library/standard/Map/types/testBorrowed.good
  test/library/standard/Map/types/testNilableOwned.good
  test/library/standard/Map/types/testNilableShared.good
  test/library/standard/Map/types/testNilableTuple.good
  test/library/standard/Map/types/testNilableUnmanaged.good
  test/library/standard/Map/types/testNonNilableUnmanagedIndexingError.good
  test/library/standard/Map/types/testOwned.good
  test/library/standard/Map/types/testRecord.good
  test/library/standard/Map/types/testShared.good
  test/library/standard/Map/types/testTuple.good
  test/library/standard/Map/types/testTupleIndexingError.chpl
  test/library/standard/Map/types/testTupleIndexingError.good
  test/library/standard/Map/types/testUnmanaged.good
  test/unstable/Map/parSafe.good
Labels: stat: Ready to Merge

#22586 Add deprecation tests for range.stridable
  modules/internal/ChapelRange.chpl
  test/deprecated/CyclicStridable.chpl
  test/deprecated/CyclicStridable.notest
  test/deprecated/CyclicTest.chpl
  test/deprecated/CyclicTest.comm-none.good
  test/deprecated/CyclicTest.good
  test/deprecated/CyclicTest.numlocales
  test/deprecated/CyclicTest.prediff
  test/deprecated/CyclicTest.skipif
  test/deprecated/boundedRangeType.chpl
  test/deprecated/boundedRangeType.good
  test/deprecated/rangeStridable.chpl
  test/deprecated/rangeStridable.good
  test/deprecated/rangeStridable.prediff
Labels: stat: Ready to Merge

#22553 Chpldoc Recognize Where Clauses
  test/chpldoc/functions/WhereClause.doc.catfiles
  test/chpldoc/functions/WhereClause.doc.chpl
  test/chpldoc/functions/WhereClause.doc.good
  third-party/chpl-venv/chpldoc-requirements3.txt
  tools/chpldoc/chpldoc.cpp
Labels: post-release

#22520 dyno: Fix control flow handling with yield statements in return type inference
  frontend/lib/parsing/parser-error-classes-list.cpp
  frontend/lib/resolution/resolution-error-classes-list.cpp
  frontend/lib/resolution/return-type-inference.cpp
  frontend/lib/uast/post-parse-checks.cpp
  frontend/test/resolution/testReturnTypes.cpp
  frontend/test/test-minimal-modules.h
  test/functions/vass/proc-iter/error-return-expr-in-iter-1.good
  test/functions/vass/proc-iter/error-return-expr-in-iter-2.good
  test/functions/vass/proc-iter/error-yield-in-proc-1.good
  test/functions/vass/proc-iter/error-yield-in-proc-2.good
Labels: post-release
