Repository chapel-lang/chapel, pull requests merged in 2023-11, with the labels that each got.

#23765 Gpu radix sort
  modules/standard/GPU.chpl
  modules/standard/GpuSort.chpl
  modules/standard/Math.chpl
  test/gpu/native/studies/sort/multiDimScanArray.good
  test/gpu/native/studies/sort/nonGpuScanTest.good
  test/gpu/native/studies/sort/radixSortGpu.chpl
  test/gpu/native/studies/sort/radixSortGpu.execopts
  test/gpu/native/studies/sort/radixSortGpu.gpu-execopts
  test/gpu/native/studies/sort/scanTest.chpl
  test/gpu/native/studies/sort/scanTest.compopts
  test/gpu/native/studies/sort/scanTest.execopts
  test/gpu/native/studies/sort/scanTest.good
  test/gpu/native/studies/sort/scanTest.prediff
  test/gpu/native/studies/sort/scanTestMultiDim.chpl
  test/gpu/native/studies/sort/scanTestMultiDim.good
  test/gpu/native/studies/sort/sortTest.chpl
  test/gpu/native/studies/sort/sortTest.compopts
  test/gpu/native/studies/sort/sortTest.execopts
  test/gpu/native/studies/sort/sortTest.good
Labels: stat: Needs Code Review

#23885 Check that `const` arguments are not indirectly modified
  compiler/AST/primitive.cpp
  compiler/codegen/cg-expr.cpp
  compiler/include/driver.h
  compiler/main/driver.cpp
  compiler/optimizations/optimizeOnClauses.cpp
  compiler/passes/resolveIntents.cpp
  frontend/include/chpl/uast/prim-ops-list.h
  frontend/lib/resolution/prims.cpp
  man/chpl.rst
  runtime/include/chpl-const-arg-check.h
  runtime/include/stdchpl.h
  runtime/src/Makefile.share
  runtime/src/chpl-const-arg-check.c
  test/compflags/bradc/help/userhelp.good
  test/unstable/const-intent/COMPOPTS
  test/unstable/const-intent/SKIPIF
  test/unstable/const-intent/constButWouldBeInIntent.chpl
  test/unstable/const-intent/constButWouldBeInIntent.good
  test/unstable/const-intent/constIntent-longer.chpl
  test/unstable/const-intent/constIntent-longer.good
  test/unstable/const-intent/constIntentImplicitMod-class.chpl
  test/unstable/const-intent/constIntentImplicitMod-class.good
  test/unstable/const-intent/constIntentImplicitMod-remote.chpl
  test/unstable/const-intent/constIntentImplicitMod-remote.good
  test/unstable/const-intent/constIntentImplicitMod-remote.numlocales
  test/unstable/const-intent/constIntentImplicitMod-remote.skipif
  test/unstable/const-intent/constIntentImplicitMod.chpl
  test/unstable/const-intent/constIntentImplicitMod.good
  test/unstable/const-intent/constRefIntentImplicitMod.chpl
  test/unstable/const-intent/constRefIntentImplicitMod.good
  test/unstable/const-intent/defaultIntentMod.chpl
  test/unstable/const-intent/defaultIntentMod.good
  test/unstable/const-intent/flags/checkFlags.chpl
  test/unstable/const-intent/flags/checkFlags.compopts
  test/unstable/const-intent/flags/checkFlags.no-warn.good
  test/unstable/const-intent/flags/checkFlags.skipif
  test/unstable/const-intent/flags/checkFlags.warn.good
  test/unstableAnonScript/specialCases/constArgs.chpl
  test/unstableAnonScript/specialCases/constArgs.good
  tools/unstableWarningAnonymizer/unstableAnonScript.chpl
  util/chpl-completion.bash
Labels: area: Compiler, area: Runtime, area: Tools, area: Tests / Benchmarks, stat: Needs Code Review

#23966 Skip this test with --fast
  test/unstableAnonScript/specialCases/constArgs.skipif
Labels: area: Tests / Benchmarks

#23955 Add some more tests of the const intent warning
  test/unstable/const-intent/constIntent-longerClass.chpl
  test/unstable/const-intent/constIntent-longerClass.good
  test/unstable/const-intent/constIntent-longerRemote.chpl
  test/unstable/const-intent/constIntent-longerRemote.good
  test/unstable/const-intent/constIntent-longerRemote.numlocales
  test/unstable/const-intent/constIntent-longerRemote.skipif
  test/unstable/const-intent/constIntentImplicitMod-instantiated.chpl
  test/unstable/const-intent/constIntentImplicitMod-instantiated.good
Labels: area: Tests / Benchmarks

#23968 Fix memory leak with const check warning message
  runtime/src/chpl-const-arg-check.c
Labels: area: Runtime
