Repository chapel-lang/chapel, pull requests merged in 2024-06, with the labels that each got.

#25157 Fix a sporadic output problem in the python interoperability begin test
  test/interop/python/beginInExportedFunction.chpl
  test/interop/python/beginInExportedFunction.good
  test/interop/python/beginInExportedFunction2.chpl
  test/interop/python/beginInExportedFunction2.good
  test/interop/python/beginInExportedFunction2.noexec
  test/interop/python/beginInExportedFunction2.prediff
  test/interop/python/beginInExportedFunction3.chpl
  test/interop/python/beginInExportedFunction3.good
  test/interop/python/beginInExportedFunction3.noexec
  test/interop/python/beginInExportedFunction3.prediff
  test/interop/python/use_beginInExportedFunction.py
  test/interop/python/use_beginInExportedFunction2.py
  test/interop/python/use_beginInExportedFunction3.py
Labels: area: Tests / Benchmarks, stat: Needs Code Review

#25196 Add documentation on how to install the language server and linter in emacs
  doc/rst/tools/chpl-language-server/chpl-language-server.rst
  doc/rst/tools/chplcheck/chplcheck.rst
Labels: area: Docs, area: Tools, stat: Ready to Merge

#25186 Make CHPL_LOCALE_MODEL more prominent in documentation
  doc/rst/technotes/gpu.rst
  doc/rst/usingchapel/chplenv.rst
Labels: stat: Ready to Merge

#25235 Turn off this test due to it occasionally encountering a sporadic failure
  test/library/draft/DistributedMap/v3/staticMemManager.chpl
  test/library/draft/DistributedMap/v3/staticMemManager.notest
Labels: area: Tests / Benchmarks, stat: Needs Code Review

#25263 Clarify how to call the module initialization function in interop scenarios
  doc/rst/technotes/libraries.rst
Labels: area: Docs, stat: Needs Code Review

#25315 Require `setupModuleSearchPaths` be called before any other queries
  frontend/lib/parsing/parsing-queries.cpp
  frontend/test/resolution/testInteractive.cpp
  tools/chapel-py/src/chapel/__init__.py
  tools/chplcheck/src/chplcheck.py
Labels: post-release

#25312 Fix codegen with LLVM opaque pointers and ROCm LLVM
  compiler/codegen/codegen.cpp
  compiler/main/driver.cpp
  test/gpu/native/compilerDriver.chpl
  test/gpu/native/compilerDriver.compopts
  test/gpu/native/compilerDriver.good
  test/gpu/native/rocmOnly.skipif
  test/gpu/native/rocmOnly/compilerDriver/compilerDriver.chpl
  test/gpu/native/rocmOnly/compilerDriver/compilerDriver.compopts
  test/gpu/native/rocmOnly/compilerDriver/compilerDriver.good
Labels: post-release

#25335 Add assert for non-null pointer inside loop
  runtime/include/tasks/qthreads/chpl-tasks-impl-fns.h
Labels: post-release

#25267 Add missing id check for `--break-on-codegen-id`
  compiler/codegen/cg-CForLoop.cpp
Labels: post-release

#25354 Fix rpaths for homebrew packaging deps hwloc and jemalloc
  make/Makefile.base
  third-party/jemalloc/Makefile.target.include-bundled
  third-party/jemalloc/Makefile.target.include-none
  third-party/jemalloc/Makefile.target.include-system
  util/chplenv/chpl_hwloc.py
  util/chplenv/chpl_jemalloc.py
Labels: area: BTR, area: Makefiles / Scripts, post-release

#25300 Improve chplenv errors for CHPL_TARGET_COMPILER=llvm
  util/chplenv/chpl_llvm.py
Labels: post-release

#25349 Extend Standard Module Style Guide
  doc/rst/developer/bestPractices/StandardModuleStyle.rst
  doc/rst/tools/chpldoc/chpldoc.rst
Labels: area: Docs, stat: Needs Code Review, post-release

#25150 Remove deprecated VectorizingIterator module
  doc/rst/meta/modules/standard.rst
  modules/Makefile
  modules/standard/VectorizingIterator.chpl
  test/deprecated/vectorizingModule.chpl
  test/deprecated/vectorizingModule.good
Labels: post-release
