Repository chapel-lang/chapel, pull requests merged in 2024-04, with the labels that each got.

#24705 Add support for syncWarp
  modules/standard/GPU.chpl
  runtime/include/gpu/amd/chpl-gpu-gen-includes.h
  runtime/include/gpu/chpl-gpu-gen-common.h
  runtime/include/gpu/cpu/chpl-gpu-gen-includes.h
  runtime/include/gpu/nvidia/chpl-gpu-gen-includes.h
  test/gpu/native/syncWarp.chpl
  test/gpu/native/syncWarp.good
Labels: stat: Ready to Merge

#24799 docs: Change to reflect rename Timer -> stopwatch
  doc/rst/developer/bestPractices/GeneratedCode.rst
Labels: area: Docs

#24856 Rename a function to make it clearer that it returns non-module IDs
  frontend/include/chpl/resolution/scope-queries.h
  frontend/lib/resolution/scope-queries.cpp
  tools/chapel-py/src/method-tables/core-methods.h
  tools/chpldoc/chpldoc.cpp
Labels: area: Dyno

#24896 Add tests and futures motivated by HPO's use of these features
  test/hash/throwingHash.chpl
  test/hash/throwingHash.good
  test/hash/throwingHashCallsRef.bad
  test/hash/throwingHashCallsRef.chpl
  test/hash/throwingHashCallsRef.future
  test/hash/throwingHashCallsRef.good
  test/hash/throwingHashInModule.bad
  test/hash/throwingHashInModule.chpl
  test/hash/throwingHashInModule.future
  test/hash/throwingHashInModule.good
  test/hash/throwingHashIndirect.chpl
  test/hash/throwingHashIndirect.good
  test/hash/throwingHashRef.bad
  test/hash/throwingHashRef.chpl
  test/hash/throwingHashRef.future
  test/hash/throwingHashRef.good
  test/interop/python/cptrConstCharArrays.bad
  test/interop/python/cptrConstCharArrays.chpl
  test/interop/python/cptrConstCharArrays.future
  test/interop/python/cptrConstCharArrays.good
  test/interop/python/cptrConstCharArrays.noexec
  test/interop/python/cptrConstCharArrays.prediff
  test/interop/python/stringArrayArg.chpl
  test/interop/python/stringArrayArg.future
  test/interop/python/stringArrayArg.good
  test/interop/python/stringArrayArg.noexec
  test/interop/python/stringArrayArg.prediff
  test/interop/python/use_cptrConstCharArrays.py
  test/interop/python/use_stringArrayArg.py
Labels: area: Tests / Benchmarks

#24930 Add a warning when list initialization involves mismatched parSafe settings
  modules/standard/List.chpl
  test/functions/iterators/Issue21265.2.good
  test/functions/iterators/Issue21265.prediff
  test/library/standard/List/initEquals/list-init-eq-many.chpl
  test/library/standard/List/initEquals/list-init-eq-many.compopts
  test/library/standard/List/initEquals/list-init-eq-many.false.good
  test/library/standard/List/initEquals/list-init-eq-many.true.good
  test/library/standard/List/parsafeMismatch.chpl
  test/library/standard/List/parsafeMismatch.compopts
  test/library/standard/List/parsafeMismatch.false.good
  test/library/standard/List/parsafeMismatch.noexec
  test/library/standard/List/parsafeMismatch.true.good
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Ready to Merge
