Repository chapel-lang/chapel, pull requests merged in 2024-09, with the labels that each got.

#25855 @gpu.itersPerThread attribute
  compiler/AST/CForLoop.cpp
  compiler/AST/primitive.cpp
  compiler/main/checks.cpp
  compiler/optimizations/gpuTransforms.cpp
  compiler/optimizations/optimizeOnClauses.cpp
  compiler/passes/convert-uast.cpp
  doc/rst/technotes/gpu.rst
  frontend/include/chpl/framework/all-global-strings.h
  frontend/include/chpl/parsing/parser-error-classes-list.h
  frontend/include/chpl/uast/prim-ops-list.h
  frontend/lib/parsing/parser-error-classes-list.cpp
  frontend/lib/resolution/prims.cpp
  frontend/lib/uast/post-parse-checks.cpp
  frontend/test/resolution/testRuntimePrimitives.cpp
  modules/standard/AutoGpu.chpl
  runtime/src/chpl-gpu.c
  test/errors/parsing/assertOnGpu.2.good
  test/errors/parsing/blockSize.2.good
Labels: area: GPU Support

#25864 Fix a bug with varargs and const checking
  compiler/resolution/expandVarArgs.cpp
  modules/standard/IO.chpl
  test/functions/constVarargs.chpl
  test/functions/constVarargs.good
  test/functions/constVarargsQuery.chpl
  test/functions/constVarargsQuery.good
Labels: area: Compiler, area: Tests / Benchmarks, stat: Needs Code Review

#25883 Update the expected output for these tests after fixing const varargs checking
  test/arrays/sparse/copyRemoteSparse-cs.good
  test/arrays/sparse/copyRemoteSparse.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#25887 Extend the fix for const varargs to also apply to `const in` and the default intent
  compiler/resolution/expandVarArgs.cpp
  test/functions/varargs/constInVarargs.chpl
  test/functions/varargs/constInVarargs.good
  test/functions/varargs/constInVarargsQuery.chpl
  test/functions/varargs/constInVarargsQuery.good
  test/functions/varargs/constVarargs.chpl
  test/functions/varargs/constVarargs.good
  test/functions/varargs/constVarargsQuery.chpl
  test/functions/varargs/constVarargsQuery.good
  test/functions/varargs/varargsBadAccess.chpl
  test/functions/varargs/varargsBadAccess.good
Labels: area: Compiler, area: Tests / Benchmarks, stat: Needs Code Review

#25968 Add CHPL_TARBALL_LOCATION to nightly test script
  util/cron/create_release_aptrpm.bash
Labels: post-release

#25970 Add gitignore and cleanfiles for a handful tests
  test/compflags/.gitignore
  test/gpu/native/studies/chop/.gitignore
  test/gpu/native/studies/chop/main.cleanfiles
  test/gpu/native/studies/minibude/.gitignore
  test/gpu/native/studies/minibude/Bude.cleanfiles
  test/studies/1brc/.gitignore
  test/unstable/.gitignore
Labels: post-release

#25971 Update AWS docs to suggest binary distributions
  doc/rst/platforms/aws.rst
Labels: post-release

#25927 Improve location reporting for ControlFlowParentheses
  tools/chplcheck/src/rule_types.py
  tools/chplcheck/src/rules.py
Labels: post-release

#25962 Fix printing of Chapel enviroment variables with `--print-chpl-settings`
  compiler/main/driver.cpp
  test/chplenv/printchplenv/print-chpl-settings.chpl
  test/chplenv/printchplenv/print-chpl-settings.cleanfiles
  test/chplenv/printchplenv/print-chpl-settings.compopts
  test/chplenv/printchplenv/print-chpl-settings.noexec
  test/chplenv/printchplenv/print-chpl-settings.precomp
  test/chplenv/printchplenv/print-chpl-settings.prediff
Labels: post-release

#25923 Remove the unused and deprecated config `fileOffsetWithoutLocking`
  modules/standard/IO.chpl
  test/deprecated/IO/offsetWithLocking.chpl
  test/deprecated/IO/offsetWithLocking.compopts
  test/deprecated/IO/offsetWithLocking.good
Labels: post-release

#25978 Improve Image module docs
  modules/packages/Image.chpl
  test/library/packages/Image/.gitignore
  test/library/packages/Image/example2.catfiles
  test/library/packages/Image/example2.chpl
  test/library/packages/Image/example2.cleanfiles
  test/library/packages/Image/example2.good
Labels: post-release

#25928 Resolve memory leaks in ConcurrentMap, EpochManager, LockFreeStack, and LockFreeQueue
  modules/packages/ConcurrentMap.chpl
  modules/packages/EpochManager.chpl
  modules/packages/LockFreeQueue.chpl
  modules/packages/LockFreeStack.chpl
  test/functions/iterators/bugs/iter-memory-leak-unpack.bad
  test/functions/iterators/bugs/iter-memory-leak-unpack.chpl
  test/functions/iterators/bugs/iter-memory-leak-unpack.execopts
  test/functions/iterators/bugs/iter-memory-leak-unpack.future
  test/functions/iterators/bugs/iter-memory-leak-unpack.good
  test/functions/iterators/bugs/iter-memory-leak-unpack.prediff
  test/library/packages/ConcurrentMap.skipif
  test/library/packages/ConcurrentMap/memLeakTests/PREDIFF
  test/library/packages/ConcurrentMap/memLeakTests/README
  test/library/packages/ConcurrentMap/memLeakTests/testAddSet.chpl
  test/library/packages/ConcurrentMap/memLeakTests/testAddSet.good
  test/library/packages/ConcurrentMap/memLeakTests/testClear.chpl
  test/library/packages/ConcurrentMap/memLeakTests/testClear.good
  test/library/packages/ConcurrentMap/memLeakTests/testEquality.chpl
  test/library/packages/ConcurrentMap/memLeakTests/testEquality.good
  test/library/packages/ConcurrentMap/memLeakTests/testGetRemove.chpl
  test/library/packages/ConcurrentMap/memLeakTests/testGetRemove.good
  test/library/packages/ConcurrentMap/memLeakTests/utilFunctions.chpl
  test/library/packages/ConcurrentMap/memLeakTests/utilFunctions.good
  test/library/packages/EpochManager.skipif
  test/library/packages/EpochManager/atomicObjects/atomicObjectsTest.skipif
  test/library/packages/EpochManager/distributedMemory/distributedMemory.chpl
  test/library/packages/EpochManager/distributedMemory/distributedMemory.execopts
  test/library/packages/EpochManager/distributedMemory/distributedMemory.future
  test/library/packages/EpochManager/sharedMemory/sharedMemory.execopts
  test/library/packages/EpochManager/sharedMemory/sharedMemory.future
  test/library/packages/LockFreeQueue/interleavedTest.chpl
  test/library/packages/LockFreeQueue/memLeaks/EXECOPTS
  test/library/packages/LockFreeQueue/memLeaks/PREDIFF
  test/library/packages/LockFreeQueue/memLeaks/README
  test/library/packages/LockFreeQueue/memLeaks/consistencyCheck.chpl
  test/library/packages/LockFreeQueue/memLeaks/consistencyCheck.good
  test/library/packages/LockFreeStack/interleavedTest.chpl
  test/library/packages/LockFreeStack/memLeaks/EXECOPTS
  test/library/packages/LockFreeStack/memLeaks/PREDIFF
  test/library/packages/LockFreeStack/memLeaks/README
  test/library/packages/LockFreeStack/memLeaks/consistencyCheck.chpl
  test/library/packages/LockFreeStack/memLeaks/consistencyCheck.good
  test/studies/1brc/concurrentMapVer.skipif
Labels: post-release

#25946 Simplify convert-uast's handling of SymExprs and similar
  compiler/AST/baseAST.cpp
  compiler/AST/type.cpp
  compiler/AST/wellknown.cpp
  compiler/include/baseAST.h
  compiler/include/convert-uast.h
  compiler/include/symbol.h
  compiler/include/type.h
  compiler/include/wellknown.h
  compiler/passes/convert-uast.cpp
  compiler/passes/parseAndConvert.cpp
  frontend/lib/framework/Context.cpp
Labels: post-release

#25982 lang spec: clarify precedence of binary bitwise ops
  doc/rst/language/spec/expressions.rst
Labels: area: Docs, stat: Needs Code Review

#25967 Fix disambiguation bug in dyno resolver
  frontend/lib/resolution/disambiguation.cpp
Labels: post-release, area: Dyno

#25965 Dyno: Improve initializers on classes that inherit
  frontend/lib/resolution/InitResolver.cpp
  frontend/lib/resolution/InitResolver.h
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/resolution-queries.cpp
  frontend/lib/resolution/resolution-types.cpp
  frontend/test/resolution/testInitSemantics.cpp
Labels: post-release

#25951 Dyno: fix decls with tuple type expressions and initialization expressions
  frontend/lib/resolution/Resolver.cpp
  frontend/test/resolution/testTuples.cpp
Labels: post-release
