Repository chapel-lang/chapel, pull requests merged in 2024-03, with the labels that each got.

#24513 Don't perform const checks on type arguments, even if they're runtime types
  compiler/passes/resolveIntents.cpp
Labels: area: Compiler, stat: Needs Code Review

#24569 Recategorize the hyperbolic Math functions in the documentation
  modules/standard/Math.chpl
Labels: area: Libraries / Modules, area: Docs, stat: Ready to Merge

#24606 Improve the IO module documentation
  modules/standard/IO.chpl
  test/deprecated/IO/ioendian/ioendianUse.good
  test/deprecated/IO/ioendian/readWriteBinary.good
Labels: area: Libraries / Modules, area: Docs, stat: Needs Code Review

#24641 Add future to lock in the bug I found with chpldoc linking behavior
  test/chpldoc/links/linkToPrev.doc.bad
  test/chpldoc/links/linkToPrev.doc.chpl
  test/chpldoc/links/linkToPrev.doc.chpldocopts
  test/chpldoc/links/linkToPrev.doc.cleanfiles
  test/chpldoc/links/linkToPrev.doc.future
  test/chpldoc/links/linkToPrev.doc.good
  test/chpldoc/links/linkToPrev.doc.prediff
Labels: area: Tests / Benchmarks, stat: Ready to Merge, post-release

#24638 Avoid PIP timeouts in nightly testing
  test/studies/arkouda/sub_test
Labels: post-release

#24645 Dyno: Improve resolution of where-clauses on generic methods
  frontend/lib/resolution/can-pass.cpp
  frontend/lib/resolution/resolution-queries.cpp
  frontend/lib/resolution/resolution-types.cpp
  frontend/test/resolution/testMethodCalls.cpp
Labels: post-release

#24500 Dyno resolve `if var` decl type with nilable classes
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/call-init-deinit.cpp
  frontend/lib/resolution/default-functions.cpp
  frontend/test/resolution/testCallInitDeinit.cpp
  frontend/test/resolution/testIf.cpp
Labels: post-release

#24632 Add spec index entries based on .tex index entries
  doc/rst/language/spec/arrays.rst
  doc/rst/language/spec/bytes.rst
  doc/rst/language/spec/classes.rst
  doc/rst/language/spec/conversions.rst
  doc/rst/language/spec/data-parallelism.rst
  doc/rst/language/spec/domain-maps.rst
  doc/rst/language/spec/domains.rst
  doc/rst/language/spec/error-handling.rst
  doc/rst/language/spec/expressions.rst
  doc/rst/language/spec/generics.rst
  doc/rst/language/spec/interoperability.rst
  doc/rst/language/spec/iterators.rst
  doc/rst/language/spec/language-overview.rst
  doc/rst/language/spec/lexical-structure.rst
  doc/rst/language/spec/locales.rst
  doc/rst/language/spec/memory-consistency-model.rst
  doc/rst/language/spec/methods.rst
  doc/rst/language/spec/modules.rst
  doc/rst/language/spec/procedures.rst
  doc/rst/language/spec/ranges.rst
  doc/rst/language/spec/records.rst
  doc/rst/language/spec/statements.rst
  doc/rst/language/spec/strings.rst
  doc/rst/language/spec/task-parallelism-and-synchronization.rst
  doc/rst/language/spec/tuples.rst
  doc/rst/language/spec/types.rst
  doc/rst/language/spec/unions.rst
  doc/rst/language/spec/variables.rst
  doc/rst/technotes/noinit.rst
Labels: post-release

#22935 Provide multiple github issue templates, with priority levels
  .github/ISSUE_TEMPLATE/00-bug.md
  .github/ISSUE_TEMPLATE/01-feature_request.md
  .github/ISSUE_TEMPLATE/02-performance.md
  .github/ISSUE_TEMPLATE/03-documentation.md
  .github/ISSUE_TEMPLATE/99-blank.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: stat: Ready to Merge

#24642 Reorder documentation for "Tools"
  doc/rst/tools/index.rst
Labels: post-release

#24613 Allow users to turn off "Show instantiation" code lens
  tools/chpl-language-server/src/chpl-language-server.py
Labels: post-release

#24692 Fix an error handling bug with reductions inside foralls that could throw
  compiler/passes/errorHandling.cpp
  test/errhandling/lydia/reductionInForall.chpl
  test/errhandling/lydia/reductionInForall.good
Labels: area: Compiler, area: Tests / Benchmarks, stat: Needs Code Review

#24685 Stabilize tuple scalar operators
  modules/internal/ChapelTuple.chpl
  test/types/tuple/homog/tuple-scalar.chpl
  test/types/tuple/homog/tuple-scalar.good
  test/unstable/tuple-scalar.good
Labels: stat: Needs Code Review

#24615 Make chpl-shim available in PATH
  tools/chpl-language-server/Makefile
  tools/chpl-language-server/chpl-shim
  util/buildRelease/install.sh
Labels: post-release
