Repository chapel-lang/chapel, pull requests merged in 2024-12, with the labels that each got.

#26335 Update the Mason environment variable documentation for MASON_LICENSE_CACHE_PATH
  doc/rst/tools/mason/guide/environmentvariables.rst
Labels: area: Docs, area: Tools, stat: Needs Code Review

#26311 Fix split init internal compiler error
  compiler/AST/primitive.cpp
  compiler/AST/type.cpp
  compiler/passes/normalize.cpp
  compiler/resolution/ResolutionCandidate.cpp
  compiler/resolution/functionResolution.cpp
  compiler/resolution/preFold.cpp
  compiler/resolution/resolveFunction.cpp
  compiler/resolution/wrappers.cpp
  frontend/include/chpl/uast/prim-ops-list.h
  frontend/lib/resolution/prims.cpp
  test/types/tuple/split-init/initFromAnotherTuple.bad
  test/types/tuple/split-init/initFromAnotherTuple.chpl
  test/types/tuple/split-init/initFromAnotherTuple.future
  test/types/tuple/split-init/initFromAnotherTuple.good
  test/types/tuple/split-init/initFromAnotherTupleTyped.chpl
  test/types/tuple/split-init/initFromAnotherTupleTyped.good
  test/types/tuple/split-init/initFromFunction.bad
  test/types/tuple/split-init/initFromFunction.chpl
  test/types/tuple/split-init/initFromFunction.future
  test/types/tuple/split-init/initFromFunction.good
  test/types/tuple/split-init/multipleInit.bad
Labels: area: Compiler, area: Tests / Benchmarks, stat: Needs Code Review

#26367 Add tests for `./util/chplenv/printchplbuilds.py`
  test/chplenv/printchplbuilds/.gitignore
  test/chplenv/printchplbuilds/COMPOPTS
  test/chplenv/printchplbuilds/NOEXEC
  test/chplenv/printchplbuilds/printchplbuilds-check.chpl
  test/chplenv/printchplbuilds/printchplbuilds-check.good
  test/chplenv/printchplbuilds/printchplbuilds-check.prediff
  test/chplenv/printchplbuilds/printchplbuilds-print1.chpl
  test/chplenv/printchplbuilds/printchplbuilds-print1.cleanfiles
  test/chplenv/printchplbuilds/printchplbuilds-print1.prediff
  test/chplenv/printchplbuilds/printchplbuilds.chpl
  test/chplenv/printchplbuilds/printchplbuilds.good
  test/chplenv/printchplbuilds/printchplbuilds.prediff
Labels: stat: Ready to Merge, post-release

#26360 Fix `make docs` in a dirty source tree with chapel-py
  doc/rst/conf.py
Labels: stat: Ready to Merge, post-release

#26341 Add support for CHPL_LLVM_TARGETS_TO_BUILD
  third-party/llvm/Makefile
Labels: stat: Ready to Merge, post-release

#26318 Add variant of CPU-as-device test config
  util/cron/test-gpu-cpu.bash
Labels: stat: Ready to Merge, post-release

#26317 Fix 'make check' with the GPU locale model
  test/release/examples/gpu/hello-gpu.chpl
  util/test/checkChplInstall
Labels: stat: Ready to Merge, post-release

#26190 Expand chplcheck with rule settings
  doc/rst/tools/chplcheck/chplcheck.rst
  test/chplcheck/rule-settings/.gitignore
  test/chplcheck/rule-settings/CLEANFILES
  test/chplcheck/rule-settings/COMPOPTS
  test/chplcheck/rule-settings/NOEXEC
  test/chplcheck/rule-settings/RuleSettings.1.good
  test/chplcheck/rule-settings/RuleSettings.2.good
  test/chplcheck/rule-settings/RuleSettings.3.good
  test/chplcheck/rule-settings/RuleSettings.4.good
  test/chplcheck/rule-settings/RuleSettings.5.good
  test/chplcheck/rule-settings/RuleSettings.6.good
  test/chplcheck/rule-settings/RuleSettings.7.good
  test/chplcheck/rule-settings/RuleSettings.8.good
  test/chplcheck/rule-settings/RuleSettings.chpl
  test/chplcheck/rule-settings/RuleSettings.cleanfiles
  test/chplcheck/rule-settings/RuleSettings.good
  test/chplcheck/rule-settings/RuleSettings.prediff
  test/chplcheck/rule-settings/SKIPIF
  test/chplcheck/rule-settings/rules.py
  tools/chplcheck/src/chplcheck.py
  tools/chplcheck/src/config.py
  tools/chplcheck/src/driver.py
  tools/chplcheck/src/rule_types.py
Labels: stat: Ready to Merge, post-release

#26364 Always use a smaller number of trials for a memory benchmark
  test/performance/memory/microMemoryAllocation.execopts
Labels: post-release

#26322 Dyno: Generate function bodies for init=, deinit, and (de)serializers
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/default-functions.cpp
  frontend/lib/resolution/default-functions.h
  frontend/lib/resolution/resolution-queries.cpp
  frontend/lib/types/Type.cpp
Labels: post-release

#26272 Print `printchplenv` warnings at the end of the output
  util/chplenv/printchplenv.py
  util/chplenv/utils.py
Labels: stat: Ready to Merge, post-release

#26328 Backport More Qthreads Performance Fixes
  third-party/qthread/README
  third-party/qthread/qthread-src/include/qthread/qthread.h
  third-party/qthread/qthread-src/src/io.c
Labels: stat: Ready to Merge, post-release

#26380 annotations added after 2.3 release-over-release triage
  test/ANNOTATIONS.yaml
Labels: post-release

#26402 Fix CHPL_LLVM=bundled build when a system LLVM is installed
  util/chplenv/chpl_llvm.py
Labels: stat: Ready to Merge

#26378 Fix linter checking for a tuple unpack in a formal
  test/chplcheck/.gitignore
  test/chplcheck/CLEANFILES
  test/chplcheck/Unused.chpl
  test/chplcheck/Unused.good
  test/chplcheck/UnusedTupleUnpack.chpl
  test/chplcheck/UnusedTupleUnpack.good
  test/chplcheck/UnusedTupleUnpack.good-fixit
  tools/chplcheck/src/rules.py
Labels: stat: Ready to Merge, post-release

#26374 Add prototype support for compiling user programs with CMake
  frontend/include/chpl/config/config.h.cmake
  test/cmake/.gitignore
  test/cmake/CLEANFILES
  test/cmake/helloWorld.notest
  test/cmake/helloWorld/CMakeLists.txt
  test/cmake/helloWorld/hello.chpl
  test/cmake/minimalHello.notest
  test/cmake/minimalHello/CMakeLists.txt
  test/cmake/minimalHello/NOINSTALL
  test/cmake/minimalHello/hello.chpl
  test/cmake/sub_test
  util/buildRelease/add_license_to_sources.py
  util/buildRelease/gen_release
  util/cmake/CMakeChplCompiler.cmake.in
  util/cmake/CMakeChplInformation.cmake
  util/cmake/CMakeDetermineChplCompiler.cmake
  util/cmake/CMakeTestChplCompiler.cmake
  util/cmake/README.md
  util/cmake/chpl-config.cmake
  util/test/checkCopyrights.bash
Labels: stat: Ready to Merge, post-release

#26345 Make Python module respect PYTHONPATH
  modules/packages/Python.chpl
Labels: stat: Ready to Merge, post-release

#26191 Add new lint rule flavor, `@location_rule`
  Makefile
  doc/rst/tools/chplcheck/chplcheck.rst
  test/chplcheck/ControlFlowParentheses.chpl
  test/chplcheck/ControlFlowParentheses.good-fixit
  test/chplcheck/IncorrectIndentation.chpl
  test/chplcheck/IncorrectIndentation.good
  test/chplcheck/IncorrectIndentation.good-fixit
  test/chplcheck/InternalPrefix.chpl
  test/chplcheck/InternalPrefix.chplcheckopts
  test/chplcheck/InternalPrefix.good
  test/chplcheck/LineLength.chpl
  test/chplcheck/LineLength.good
  test/chplcheck/LineLength20.chpl
  test/chplcheck/LineLength20.chplcheckopts
  test/chplcheck/LineLength20.good
  test/chplcheck/PREDIFF
  test/chplcheck/Unused.chpl
  test/chplcheck/Unused.good
  test/chplcheck/UnusedTupleUnpack.chpl
  test/chplcheck/UnusedTupleUnpack.good
  test/chplcheck/UnusedTupleUnpack.good-fixit
  test/chplcheck/activerules.chplcheckopts
  test/chplcheck/activerules.good
  test/chplcheck/activerules.prediff
  test/chplcheck/allrules.chplcheckopts
  test/chplcheck/allrules.good
  test/chplcheck/allrules.prediff
  tools/chplcheck/src/chplcheck.py
  tools/chplcheck/src/config.py
  tools/chplcheck/src/driver.py
  tools/chplcheck/src/lsp.py
  tools/chplcheck/src/rule_types.py
  tools/chplcheck/src/rules.py
Labels: stat: Ready to Merge

#26320 Deprecate `CHPL_MEM` and `CHPL_JEMALLOC` in favor of `CHPL_TARGET_MEM` and `CHPL_TARGET_JEMALLOC`
  LICENSE
  compiler/include/driver.h
  compiler/main/driver.cpp
  doc/rst/developer/bestPractices/Sanitizers.rst
  doc/rst/developer/bestPractices/Valgrind.rst
  doc/rst/developer/chips/inactive/18.rst
  doc/rst/technotes/allocators.rst
  doc/rst/usingchapel/chplenv.rst
  make/compiler/Makefile.sanitizers
  modules/standard/ChplConfig.chpl
  runtime/include/chplcgfns.h
  runtime/src/comm/ugni/comm-ugni-heap-pages.c
  runtime/src/comm/ugni/comm-ugni.c
  runtime/src/mem/cstdlib/mem-cstdlib.c
  test/chplenv/chplconfig/correctness/chplconfig
  test/chplenv/chplconfig/correctness/correctness.chpl
  test/chplenv/printchplenv/printchplenv.chpl
  test/chplenv/printchplenv/printchplenvAll.chpl
  test/compflags/albrecht/chplenv/chplenv.chpl
  test/compflags/albrecht/chplenv/chplenv.compenv
  test/compflags/albrecht/chplenv/generateChplEnvFiles
  test/deprecated/chplenv/chplMemConfig.chpl
  test/deprecated/chplenv/chplMemConfig.good
  test/deprecated/chplenv/chplMemPrintChplEnv.chpl
  test/deprecated/chplenv/chplMemPrintChplEnv.good
  test/deprecated/chplenv/chplMemPrintChplEnv.prediff
  test/modules/OS.skipif
  test/runtime/configMatters/comm/ugni/SIGBUS-heap-extend.skipif
  test/runtime/configMatters/comm/ugni/overflow-mem-region-table.skipif
  test/runtime/configMatters/mem/fragmentation/SKIPIF
  test/setchplenv/verify_setchplenv_scripts.py
  test/types/records/ferguson/parallel/coforall-mod/coforall-mod.skipif
  util/build_configs/build_configs.py
  util/chplenv/chpl_jemalloc.py
  util/chplenv/chpl_mem.py
  util/chplenv/overrides.py
  util/chplenv/printchplbuilds.py
  util/chplenv/printchplenv.py
  util/cron/common-asan.bash
  util/cron/common-jemalloc.bash
  util/cron/common-valgrind.bash
  util/devel/test/run-tests-gnu-parallel.sh
  util/packaging/homebrew/chapel-main.rb
  util/quickstart/setchplenv.bash
  util/quickstart/setchplenv.csh
  util/quickstart/setchplenv.fish
  util/quickstart/setchplenv.sh
Labels: post-release
