Repository chapel-lang/chapel, pull requests merged in 2024-01, with the labels that each got.

#23971 Add a future tracking a compiler bug with yielding and const arguments
  test/functions/iterators/errors/const-violation.bad
  test/functions/iterators/errors/const-violation.chpl
  test/functions/iterators/errors/const-violation.future
  test/functions/iterators/errors/const-violation.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#24180 Remove emailer code from `testRelease`
  util/buildRelease/testRelease
  util/cron/test-release.bash
Labels: area: BTR

#23926 Add developer oriented flags to help LLVM debug
  compiler/codegen/cg-symbol.cpp
  compiler/include/codegen.h
  compiler/include/driver.h
  compiler/include/llvmDumpIR.h
  compiler/include/symbol.h
  compiler/llvm/clangUtil.cpp
  compiler/llvm/llvmDumpIR.cpp
  compiler/main/driver.cpp
  doc/rst/technotes/llvm.rst
  util/chpl-completion.bash
Labels: post-release

#23935 Miscellaneous doc improvements
  doc/rst/language/spec/statements.rst
  modules/packages/AllLocalesBarriers.chpl
  modules/packages/ArgumentParser.chpl
  modules/packages/BLAS.chpl
  modules/packages/Channel.chpl
  modules/packages/ConcurrentMap.chpl
  modules/packages/Futures.chpl
  modules/packages/LinearAlgebra.chpl
  modules/packages/RangeChunk.chpl
  modules/packages/Socket.chpl
  modules/packages/SortedSet.chpl
  modules/packages/TOML.chpl
  modules/packages/URL.chpl
  modules/packages/UnrolledLinkedList.chpl
  modules/packages/YAML.chpl
  modules/packages/ZMQ.chpl
  modules/standard/Collectives.chpl
  modules/standard/Heap.chpl
  modules/standard/IO.chpl
  modules/standard/Map.chpl
  modules/standard/MemMove.chpl
  modules/standard/Random.chpl
  modules/standard/Regex.chpl
  modules/standard/Set.chpl
  modules/standard/Time.chpl
  test/library/packages/SortedSet/general/kth/noDefaultValue.good
Labels: area: Docs, area: Tests / Benchmarks, stat: Needs Code Review, stat: Needs Testing

#24219 Downgrade filelock depended on by start_test to a slightly older version
  third-party/chpl-venv/test-requirements.txt
Labels: area: Third-Party, area: BTR, area: Tests / Benchmarks, stat: Ready to Merge

#24126 Add script for updating copyright year
  doc/rst/conf.py
  util/test/checkCopyrights.bash
  util/test/updateCopyrights.bash
Labels: area: BTR

#24249 Downgrade setuptools for Python 3.7 compatability.
  third-party/chpl-venv/test-requirements.txt
Labels: area: Third-Party, area: BTR, area: Tests / Benchmarks, stat: Needs Testing

#24091 Switch out Docker README for a link to Dockerhub
  util/packaging/docker/README.md
Labels: area: BTR, area: Docs

#23898 Switch driver nightly test config to monolithic
  util/cron/test-driver.bash
  util/cron/test-monolithic.bash
Labels: area: BTR

#24264 Remove old flag from SSCA2 multilocale performance testing compiler options
  test/studies/ssca2/main/SSCA2_main.ml-compopts
Labels: area: Tests / Benchmarks

#24269 Add a missing semi-colon to the external-procedure-declaration-statement
  doc/rst/language/spec/interoperability.rst
Labels: area: Docs
