Repository chapel-lang/chapel, pull requests merged in 2025-01, with the labels that each got.

#26465 Add a clear method to the Heap type, similar to the other collection types
  modules/standard/Heap.chpl
  test/library/standard/Heap/clear/alreadyEmpty.chpl
  test/library/standard/Heap/clear/alreadyEmpty.good
  test/library/standard/Heap/clear/calledTwiceWithInterPush.chpl
  test/library/standard/Heap/clear/calledTwiceWithInterPush.good
  test/library/standard/Heap/clear/calledTwiceWithoutInterPush.chpl
  test/library/standard/Heap/clear/calledTwiceWithoutInterPush.good
  test/library/standard/Heap/clear/hasMany.chpl
  test/library/standard/Heap/clear/hasMany.good
  test/library/standard/Heap/clear/hasOne.chpl
  test/library/standard/Heap/clear/hasOne.good
  test/library/standard/Heap/clear/hasTwo.chpl
  test/library/standard/Heap/clear/hasTwo.good
  test/library/standard/Heap/clear/isEmptyAndSizeAccurate.chpl
  test/library/standard/Heap/clear/isEmptyAndSizeAccurate.good
  test/library/standard/Heap/clear/remoteWorks.chpl
  test/library/standard/Heap/clear/remoteWorks.good
  test/library/standard/Heap/clear/remoteWorks.numlocales
  test/library/standard/Heap/clear/remoteWorks.skipif
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Needs Code Review

#26422 Adding missing documentation for some slurm launcher specifc flags and environment variables
  doc/rst/usingchapel/launcher.rst
Labels: stat: Ready to Merge

#26417 Make sure that module scope variables of extern types are default initalized
  compiler/passes/parallel.cpp
  test/extern/ferguson/NUMLOCALES
Labels: stat: Ready to Merge

#26481 Add futures for a couple of open issues
  test/classes/fields/looselyConstrainedParamField.bad
  test/classes/fields/looselyConstrainedParamField.chpl
  test/classes/fields/looselyConstrainedParamField.future
  test/classes/fields/looselyConstrainedParamField.good
  test/types/complex/realPartOfExpr.bad
  test/types/complex/realPartOfExpr.chpl
  test/types/complex/realPartOfExpr.future
  test/types/complex/realPartOfExpr.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#26353 Improve Python module testing and cleanup memory leaks
  modules/packages/Python.chpl
  modules/packages/PythonHelper/ChapelPythonHelper.h
  test/library/packages/Python/.gitignore
  test/library/packages/Python/CLEANFILES
  test/library/packages/Python/EXECENV
  test/library/packages/Python/correctness/CLEANFILES
  test/library/packages/Python/correctness/COMPOPTS
  test/library/packages/Python/correctness/EXECENV
  test/library/packages/Python/correctness/argPassingTest.chpl
  test/library/packages/Python/correctness/argPassingTest.comm-none.good
  test/library/packages/Python/correctness/argPassingTest.good
  test/library/packages/Python/correctness/argPassingTest.py
  test/library/packages/Python/correctness/basicTypes.chpl
  test/library/packages/Python/correctness/basicTypes.good
  test/library/packages/Python/correctness/basicTypes.prediff
  test/library/packages/Python/correctness/basicTypes.py
  test/library/packages/Python/correctness/compareIterationPatterns.chpl
  test/library/packages/Python/correctness/compareIterationPatterns.good
  test/library/packages/Python/correctness/customType.chpl
  test/library/packages/Python/correctness/customType.comm-none.good
  test/library/packages/Python/correctness/customType.good
  test/library/packages/Python/correctness/customType.py
  test/library/packages/Python/correctness/iteratorTest.chpl
  test/library/packages/Python/correctness/iteratorTest.execopts
  test/library/packages/Python/correctness/iteratorTest.good
  test/library/packages/Python/correctness/iteratorTest.prediff
  test/library/packages/Python/correctness/iteratorTest.py
  test/library/packages/Python/examples/EXECENV
  test/library/packages/Python/examples/bs4/.gitignore
  test/library/packages/Python/examples/bs4/CLEANFILES
  test/library/packages/Python/examples/bs4/EXECENV
  test/library/packages/Python/examples/bs4/findLinks.skipif
  test/library/packages/Python/examples/numba/.gitignore
  test/library/packages/Python/examples/numba/CLEANFILES
  test/library/packages/Python/examples/numba/EXECENV
  test/library/packages/Python/examples/numba/apply.skipif
  test/library/packages/Python/examples/torch/.gitignore
  test/library/packages/Python/examples/torch/CLEANFILES
  test/library/packages/Python/examples/torch/EXECENV
  test/library/packages/Python/examples/torch/libs.notest
  test/library/packages/Python/examples/torch/myModel.skipif
  test/library/packages/Python/memleaks/CLEANFILES
  test/library/packages/Python/memleaks/COMPOPTS
  test/library/packages/Python/memleaks/EXECENV
  test/library/packages/Python/memleaks/EXECOPTS
  test/library/packages/Python/memleaks/PRETEST
  test/library/packages/Python/memleaks/README
  test/library/packages/Python/memleaks/SUPPRESSIF
  test/library/packages/Python/memleaks/basicTypes.chpl
  test/library/packages/Python/memleaks/basicTypes.good
  test/library/packages/Python/memleaks/lambdas.chpl
  test/library/packages/Python/memleaks/lambdas.good
  test/library/packages/Python/skipIfAndInstallPackage.sh
  util/test/sub_test.py
Labels: post-release

#26391 Adjust test-docker release branch check for Jenkins quirk
  util/cron/test-docker.bash
Labels: post-release

#26410 Add unstable `extractMatches` overload that returns a value
  modules/standard/IO.chpl
  test/regex/ferguson/extractMatches.chpl
  test/regex/ferguson/extractMatches.compopts
  test/regex/ferguson/extractMatches.good
Labels: stat: Ready to Merge

#26526 Remove deprecated code from Version
  modules/standard/Version.chpl
  test/library/standard/Version/compareVersionTypes.chpl
  test/library/standard/Version/compareVersionTypes.good
  test/library/standard/Version/versionCastIsParam.chpl
  test/library/standard/Version/versionCastIsParam.good
Labels: stat: Needs Code Review

#26540 Remove deprecated code from MemMove module
  modules/standard/MemMove.chpl
  test/deprecated/memMoveModule.chpl
  test/deprecated/memMoveModule.good
Labels: stat: Needs Code Review

#26591 Add a future to lock in the behavior when an iterator is unstable
  test/unstable-keyword/iterator/COMPOPTS
  test/unstable-keyword/iterator/onlySerial.bad
  test/unstable-keyword/iterator/onlySerial.chpl
  test/unstable-keyword/iterator/onlySerial.future
  test/unstable-keyword/iterator/onlySerial.good
Labels: area: Tests / Benchmarks, stat: Needs Code Review

#26598 Change naming linting for extern symbols
  test/chplcheck/CaseRules.chpl
  test/chplcheck/CaseRules.good
  tools/chplcheck/src/rules.py
Labels: stat: Ready to Merge

#26606 Add a prediff to this test to avoid module line number adjustments
  test/unstable-keyword/iterator/onlySerial.bad
  test/unstable-keyword/iterator/onlySerial.good
  test/unstable-keyword/iterator/onlySerial.prediff
Labels: area: Tests / Benchmarks

#26565 Refactor chapel-py to use the C Python Stable API
  doc/rst/conf.py
  doc/rst/usingchapel/prereqs.rst
  third-party/chpl-venv/Makefile.include
  third-party/chpl-venv/chapel-py-requirements.txt
  tools/chapel-py/setup.py
  tools/chapel-py/src/PythonWrapper.h
  tools/chapel-py/src/chapel.cpp
  tools/chapel-py/src/core-types-gen.cpp
  tools/chapel-py/src/core-types-gen.h
  tools/chapel-py/src/core-types.cpp
  tools/chapel-py/src/core-types.h
  tools/chapel-py/src/error-tracker.h
  tools/chapel-py/src/iterator-support.cpp
  tools/chapel-py/src/iterator-support.h
  tools/chapel-py/src/python-class.h
  tools/chapel-py/src/python-type-helper.h
  tools/chapel-py/src/python-types.h
  tools/chpl-language-server/src/chpl-language-server.py
  util/chplenv/chpl_home_utils.py
  util/config/run-in-venv-with-python-bindings.bash
Labels: stat: Ready to Merge

#26619 Add two futures for issues I encountered with arrays of ranges
  test/library/standard/Sort/correctness/arrayOfRanges.bad
  test/library/standard/Sort/correctness/arrayOfRanges.chpl
  test/library/standard/Sort/correctness/arrayOfRanges.future
  test/library/standard/Sort/correctness/arrayOfRanges.good
  test/library/standard/Sort/correctness/arrayOfRanges.prediff
  test/types/range/arrayOfRanges.bad
  test/types/range/arrayOfRanges.chpl
  test/types/range/arrayOfRanges.future
  test/types/range/arrayOfRanges.good
Labels: area: Tests / Benchmarks

#26620 Restore missing keyword and resolve the future
  test/types/range/arrayOfRanges.bad
  test/types/range/arrayOfRanges.chpl
  test/types/range/arrayOfRanges.future
Labels: area: Tests / Benchmarks
