Repository chapel-lang/chapel, pull requests merged in 2025-06, with the labels that each got.

#27319 Hide another function that was accidentally getting included in the docs
  modules/packages/Python.chpl
Labels: area: Libraries / Modules, area: Docs, stat: Ready to Merge

#27328 Add editions documentation
  doc/rst/developer/bestPractices/EditionsDev.rst
  doc/rst/developer/bestPractices/index.rst
  doc/rst/technotes/editions.rst
  doc/rst/technotes/index.rst
  man/chpl.rst
  test/edition/basics/attributeCheck.chpl
Labels: area: Docs, area: Tests / Benchmarks, stat: Needs Code Review

#27359 Remove an extra newline in the `New Package Module Features` CHANGES section
  CHANGES.md
Labels: area: BTR, area: Docs

#27368 Fix el10 package builds due to rpmlint error
  util/packaging/rpm/amzn2023-gasnet-udp/rpmlintrc
  util/packaging/rpm/amzn2023-ofi-slurm/rpmlintrc
  util/packaging/rpm/amzn2023/rpmlintrc
  util/packaging/rpm/common/fill_docker_template.py
  util/packaging/rpm/el10-gasnet-udp/rpmlintrc
  util/packaging/rpm/el10-ofi-slurm/rpmlintrc
  util/packaging/rpm/el10/rpmlintrc
  util/packaging/rpm/el9-gasnet-udp/rpmlintrc
  util/packaging/rpm/el9-ofi-slurm/rpmlintrc
  util/packaging/rpm/el9/rpmlintrc
  util/packaging/rpm/fc41-gasnet-udp/rpmlintrc
  util/packaging/rpm/fc41/rpmlintrc
  util/packaging/rpm/fc42-gasnet-udp/rpmlintrc
  util/packaging/rpm/fc42/rpmlintrc
Labels: post-release

#27374 Updates Twitter link
  README.rst
Labels: area: Docs, post-release

#27367 Prediff Python error message output
  test/library/packages/Python/correctness/arrays/arrayTypes.good
  test/library/packages/Python/correctness/arrays/arrayTypes.prediff
Labels: post-release

#27320 Convert `testReleaseHelp` script to bash
  util/buildRelease/testReleaseHelp
Labels: stat: Ready to Merge, post-release

#27394 Fix a bug with casting inf to imag
  runtime/src/chplcast.c
  test/types/imag/inf-conversion.chpl
  test/types/imag/inf-conversion.good
  test/types/imag/nan-conversion.chpl
  test/types/imag/nan-conversion.good
Labels: area: Runtime, area: Tests / Benchmarks, stat: Needs Code Review

#27401 Fix bug pointed out by Brad allowing casting `infisomething` to imag
  runtime/src/chplcast.c
  test/types/imag/badStringInfiCast.chpl
  test/types/imag/badStringInfiCast.good
Labels: area: Runtime, area: Tests / Benchmarks

#27409 Remove a write of a variable after it's been deleted
  test/library/standard/Allocators/doc-examples/example_mallocWrapper.chpl
  test/library/standard/Allocators/doc-examples/example_mallocWrapper.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#27365 Fix errors about missing runtime if user sets CHPL_HOME in a prefix install with a "view"
  frontend/lib/util/chplenv.cpp
Labels: post-release

#27348 Make chapel-py build not rely on CHPL_HOME
  tools/chapel-py/setup.py
Labels: post-release

#27298 Resolve issue with Chapel's nvidia GPU support with LLVM 20+
  compiler/llvm/clangUtil.cpp
  doc/rst/technotes/gpu.rst
  runtime/src/gpu/nvidia/Makefile.share
  util/chplenv/chpl_gpu.py
  util/cron/common-gpu-nvidia-hpe-cray-ex.bash
Labels: post-release

#27325 Fix function expressions not allowing single statement functions
  frontend/lib/parsing/bison-chpl-lib.cpp
  frontend/lib/parsing/chpl.ypp
  test/functions/fcf/fcfSingleDoStatement.chpl
  test/functions/fcf/fcfSingleDoStatement.good
Labels: post-release

#27425 Remove the `init=` technote
  doc/rst/technotes/index.rst
  doc/rst/technotes/initequals.rst
Labels: area: Docs

#27350 Move the errors from `make/compiler/Makefile.sanitizers` to `chpl_sanitizers.py`
  util/chplenv/chpl_sanitizers.py
Labels: post-release

#27344 Improve errors when the user requests a runtime that is not built yet
  compiler/main/driver.cpp
  test/chplenv/errors/NOEXEC
  test/chplenv/errors/chplconfig
  test/chplenv/errors/missingRuntime.chpl
  test/chplenv/errors/missingRuntime.good
  test/chplenv/errors/missingRuntime.prediff
  test/chplenv/errors/missingRuntime.skipif
  test/runtime/thomasvandoren/rtLibDirWarnings.good
  test/runtime/thomasvandoren/rtLibDirWarningsWithDeveloper.good
  util/chplenv/overrides.py
  util/chplenv/printchplenv.py
Labels: post-release

#27352 Remove `sorted` in the pre-edition
  doc/rst/technotes/editions.rst
  modules/internal/ChapelDomain.chpl
  test/library/standard/Sort/errors/sortDomainArray.assoc7-removed.good
  test/library/standard/Sort/errors/sortDomainArray.compopts
Labels: post-release
