Repository chapel-lang/chapel, pull requests merged in 2025-07, with the labels that each got.

#27361 Add support for goto-def on `include module ...`
  frontend/include/chpl/uast/Include.h
  frontend/include/chpl/uast/all-location-maps.h
  frontend/lib/parsing/bison-chpl-lib.cpp
  frontend/lib/parsing/chpl.ypp
  frontend/lib/uast/Include.cpp
  tools/chapel-py/src/method-tables/uast-methods.h
  tools/chapel-py/src/resolution.cpp
  tools/chpl-language-server/src/chpl-language-server.py
Labels: post-release

#27531 Avoid inlining functions that just do checks
  modules/internal/ChapelArray.chpl
  modules/internal/ChapelBase.chpl
  modules/internal/ChapelRange.chpl
  modules/internal/MemConsistency.chpl
  modules/standard/CTypes.chpl
  modules/standard/MemMove.chpl
Labels: stat: Ready to Merge

#27557 Improve cycle detection for forwarding resolution
  compiler/resolution/functionResolution.cpp
  test/classes/forwarding/forwarding-cycle.good
  test/classes/forwarding/forwarding-cycle2.chpl
  test/classes/forwarding/forwarding-cycle2.good
  test/classes/forwarding/forwarding-method-call2.chpl
  test/classes/forwarding/forwarding-method-call2.good
  test/classes/forwarding/forwarding-method-call3.chpl
  test/classes/forwarding/forwarding-method-call3.good
  test/classes/forwarding/forwarding-self.good
  test/classes/forwarding/not-a-cycle.chpl
  test/classes/forwarding/not-a-cycle.compopts
  test/classes/forwarding/not-a-cycle.good
  test/classes/forwarding/not-a-cycle2.chpl
  test/classes/forwarding/not-a-cycle2.good
Labels: stat: Ready to Merge

#27568 Make a version of the floatcomplexexceptions test for aarch64
  test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.chpl
  test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.compopts
  test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.good
  test/types/file/bradc/scalar/floatcomplexexceptions-aarch64.skipif
  test/types/file/bradc/scalar/floatcomplexexceptions.skipif
Labels: area: Tests / Benchmarks
