Repository chapel-lang/chapel, pull requests merged in 2025-03, with the labels that each got.

#26792 Dyno: resolution fixes variety pack 3
  frontend/include/chpl/resolution/can-pass.h
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/Resolver.h
  frontend/lib/resolution/call-init-deinit.cpp
  frontend/lib/resolution/call-init-deinit.h
  frontend/lib/resolution/can-pass.cpp
  frontend/lib/resolution/resolution-queries.cpp
  frontend/lib/types/TupleType.cpp
  frontend/test/resolution/CMakeLists.txt
  frontend/test/resolution/testClasses.cpp
  frontend/test/resolution/testIteratorsToArrays.cpp
  frontend/test/resolution/testIteratorsToArraysCoerce.cpp
  frontend/test/resolution/testIteratorsToArraysWithPromotion.cpp
  frontend/test/resolution/testResolve.cpp
  frontend/test/test-resolution.cpp
  frontend/test/test-resolution.h
Labels: area: Compiler, area: Dyno

#26799 Dyno: initial implementation of sparse subdomains
  frontend/include/chpl/resolution/resolution-error-classes-list.h
  frontend/include/chpl/types/DomainType.h
  frontend/lib/resolution/InitResolver.cpp
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/prims.cpp
  frontend/lib/resolution/resolution-error-classes-list.cpp
  frontend/lib/resolution/resolution-types.cpp
  frontend/lib/types/DomainType.cpp
  frontend/lib/uast/post-parse-checks.cpp
  frontend/test/resolution/CMakeLists.txt
  frontend/test/resolution/testDomainsRectangular.cpp
  frontend/test/resolution/testDomainsSparse.cpp
Labels: area: Compiler, area: Dyno

#26798 Add support for timeDelta.totalMicroseconds and totalMilliseconds
  modules/packages/NPBRandom.chpl
  modules/standard/Time.chpl
  test/library/standard/Time/dateTime/checkTotalMicro.chpl
  test/library/standard/Time/dateTime/checkTotalMicro.good
  test/library/standard/Time/dateTime/checkTotalMilli.chpl
  test/library/standard/Time/dateTime/checkTotalMilli.good
  test/studies/ssca2/main/SSCA2_Modules/SSCA2_RMAT_graph_generator.chpl
  test/users/franzf/v0/chpl/main.chpl
  test/users/franzf/v1/chpl/main.chpl
  test/users/franzf/v2/chpl/main.chpl
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Needs Code Review

#26846 Add tests for the unstable warnings on totalMicroseconds and totalMilliseconds
  test/unstable/Time/checkTotalMicro.chpl
  test/unstable/Time/checkTotalMicro.good
  test/unstable/Time/checkTotalMilli.chpl
  test/unstable/Time/checkTotalMilli.good
Labels: area: Tests / Benchmarks

#26859 Remove Hadoop stuff from the networking-packages test job
  util/cron/test-networking-packages.bash
Labels: area: Tools, area: Tests / Benchmarks, stat: Needs Code Review

#26868 Move the Python dict, set and list tests out of the arrays directory
  test/library/packages/Python/correctness/myDict.chpl
  test/library/packages/Python/correctness/myDict.good
  test/library/packages/Python/correctness/myList.chpl
  test/library/packages/Python/correctness/myList.good
  test/library/packages/Python/correctness/mySet.chpl
  test/library/packages/Python/correctness/mySet.good
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#26866 Fix version check for Python to match docs
  third-party/chpl-venv/Makefile
Labels: stat: Ready to Merge

#26880 Avoid a GMP potential ABI incompatibility with LLVM
  modules/standard/GMP.chpl
  modules/standard/GMPHelper/chplgmp.h
Labels: area: Runtime, area: Libraries / Modules, stat: Needs Code Review

#26920 Dyno: Fix test-frontend segfaults
  frontend/test/test-common.cpp
Labels: post-release

#26922 Add `--temp-directory` for arkouda testing
  test/studies/arkouda/sub_test
  util/cron/common-arkouda-hpe-apollo-hdr.bash
  util/cron/test-hpe-apollo-hdr.arkouda.bash
  util/cron/test-hpe-apollo-hdr.arkouda.release.bash
  util/cron/test-perf.hpe-apollo-hdr.arkouda.bash
  util/cron/test-perf.hpe-apollo-hdr.arkouda.release.bash
Labels: stat: Ready to Merge

#26924 Warn when using a non-prgenv compiler when it is available
  util/chplenv/chpl_compiler.py
Labels: stat: Ready to Merge, post-release

#26932 Exclude generated chplcheck rules from the docs
  doc/rst/conf.py
Labels: stat: Ready to Merge, post-release

#26884 Skip ChplPrefixReserved for extern functions
  test/chplcheck/ChplPrefixReserved.chpl
  tools/chplcheck/src/rules.py
Labels: stat: Ready to Merge, post-release

#26928 Add `repr` method to Python.Value base class
  modules/packages/Python.chpl
  test/library/packages/Python/correctness/objToString.chpl
  test/library/packages/Python/correctness/objToString.good
Labels: post-release

#26915 Add `embed-python.sh` script to make building Chapel+Python code easier
  modules/packages/Python.chpl
  test/library/packages/Python/COMPOPTS
  util/config/embed-python.sh
Labels: post-release

#26930 Add Python module functions to get, set, and delete globals
  modules/packages/Python.chpl
  modules/packages/PythonHelper/ChapelPythonHelper.h
  test/library/packages/Python/correctness/lambdaWithGlobals.chpl
  test/library/packages/Python/correctness/lambdaWithGlobals.good
  test/library/packages/Python/correctness/myGlobal.chpl
  test/library/packages/Python/correctness/myGlobal.good
  test/library/packages/Python/correctness/mySet.chpl
  test/library/packages/Python/correctness/mySet.good
  test/library/packages/Python/correctness/runTest.chpl
  test/library/packages/Python/correctness/runTest.good
Labels: post-release

#26736 Test to ensure that the Python module infers sys.path the same way as `python`
  test/library/packages/Python/correctness/paths/CLEANFILES
  test/library/packages/Python/correctness/paths/COMPOPTS
  test/library/packages/Python/correctness/paths/checkPaths.chpl
  test/library/packages/Python/correctness/paths/checkPaths.execopts
  test/library/packages/Python/correctness/paths/checkPaths.good
Labels: post-release

#26883 Dyno: Resolve initializers for nested types
  frontend/lib/resolution/default-functions.cpp
  frontend/lib/resolution/default-functions.h
  frontend/lib/resolution/resolution-queries.cpp
  frontend/test/resolution/testNestedFunctions.cpp
Labels: post-release

#26921 Add CHPL_TARGET=hpe-cray-xd and Improve OFI_OOB detection
  doc/rst/platforms/cray.rst
  doc/rst/platforms/infiniband.rst
  doc/rst/usingchapel/chplenv.rst
  util/chplenv/chpl_comm.py
  util/chplenv/chpl_comm_ofi_oob.py
  util/chplenv/chpl_comm_segment.py
  util/chplenv/chpl_comm_substrate.py
  util/chplenv/chpl_compiler.py
  util/chplenv/chpl_cpu.py
  util/chplenv/chpl_libfabric.py
  util/chplenv/chpl_llvm.py
  util/chplenv/chpl_platform.py
  util/chplenv/compile_link_args_utils.py
  util/chplenv/third_party_utils.py
Labels: post-release

#26914 Clean generated pytest files for chpl-language-server
  tools/chpl-language-server/Makefile
Labels: post-release

#26931 Dyno: resolve domain and element type queries on arrays
  frontend/lib/resolution/Resolver.cpp
  frontend/test/resolution/testTypeQueries.cpp
Labels: post-release

#26946 Add support for Python tuples to the Python module
  modules/packages/Python.chpl
  test/library/packages/Python/correctness/basicTypes.chpl
  test/library/packages/Python/correctness/myTuple.chpl
  test/library/packages/Python/correctness/myTuple.good
  test/library/packages/Python/correctness/myTupleBadRange.chpl
  test/library/packages/Python/correctness/myTupleBadRange.good
  test/library/packages/Python/correctness/myTupleBadRange2.chpl
  test/library/packages/Python/correctness/myTupleBadRange2.good
  test/library/packages/Python/correctness/myTupleTypeTooSmall.chpl
  test/library/packages/Python/correctness/myTupleTypeTooSmall.good
  test/library/packages/Python/memleaks/basicTypes.chpl
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Ready to Merge

#26980 Add two tests of using SciPy via the Python module
  test/library/packages/Python/examples/scipy/CLEANFILES
  test/library/packages/Python/examples/scipy/COMPOPTS
  test/library/packages/Python/examples/scipy/EXECENV
  test/library/packages/Python/examples/scipy/checkScipyLinAlg.chpl
  test/library/packages/Python/examples/scipy/checkScipyLinAlg.good
  test/library/packages/Python/examples/scipy/checkScipyLinAlg.skipif
  test/library/packages/Python/examples/scipy/checkScipyLinAlg_CompileOnly.chpl
  test/library/packages/Python/examples/scipy/checkScipyLinAlg_CompileOnly.good
  test/library/packages/Python/examples/scipy/checkScipyLinAlg_CompileOnly.noexec
  test/library/packages/Python/examples/scipy/python_libs.notest
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#26895 limit email workflow to chapel-lang/chapel repo
  .github/workflows/email.yml
Labels: post-release

#26988 Add casts from several Python types to Chapel types
  modules/packages/Python.chpl
  modules/packages/PythonHelper/ChapelPythonHelper.h
  test/library/packages/Python/correctness/arrays/arrayCast.chpl
  test/library/packages/Python/correctness/arrays/arrayCast.good
  test/library/packages/Python/correctness/basicCasts.chpl
  test/library/packages/Python/correctness/basicCasts.good
  test/library/packages/Python/correctness/listCast.chpl
  test/library/packages/Python/correctness/listCast.good
  test/library/packages/Python/correctness/mapCast.chpl
  test/library/packages/Python/correctness/mapCast.good
  test/library/packages/Python/correctness/objToString.chpl
  test/library/packages/Python/correctness/objToString.good
  test/library/packages/Python/correctness/setCast.chpl
  test/library/packages/Python/correctness/setCast.good
  test/library/packages/Python/correctness/tupleCast.chpl
  test/library/packages/Python/correctness/tupleCast.good
Labels: area: Libraries / Modules, area: Tests / Benchmarks

#27018 Remove old sort-related deprecations
  modules/layouts/LayoutCS.chpl
  modules/packages/Search.chpl
  modules/packages/SortedMap.chpl
  modules/packages/SortedSet.chpl
  modules/standard/Heap.chpl
  modules/standard/List.chpl
  modules/standard/Sort.chpl
  test/compflags/ferguson/print-module-resolution.good
  test/deprecated/Heap/depComparatorNames.chpl
  test/deprecated/Heap/depComparatorNames.good
  test/deprecated/Search/depComparatorNames.chpl
  test/deprecated/Search/depComparatorNames.good
  test/deprecated/Sort/comparatorArgs.chpl
  test/deprecated/Sort/comparatorArgs.good
  test/deprecated/Sort/depComparatorNames.chpl
  test/deprecated/Sort/depComparatorNames.good
  test/deprecated/Sort/listSort.chpl
  test/deprecated/Sort/listSort.good
  test/deprecated/SortedMap/depComparatorNames.chpl
  test/deprecated/SortedMap/depComparatorNames.good
  test/deprecated/SortedSet/depComparatorNames.chpl
  test/deprecated/SortedSet/depComparatorNames.good
  test/modules/sungeun/init/printModuleInitOrder.good
  test/optimizations/deadCodeElimination/elliot/countDeadModules.good
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Needs Code Review

#26850 Adjust chpl_launchcmd to be able to handle colocales with PBS
  util/test/chpl_launchcmd.py
Labels: post-release
