Repository chapel-lang/chapel, pull requests merged in 2025-02, with the labels that each got.

#26636 Test chpl-language-server with quickstart
  util/cron/test-quickstart.bash
Labels: stat: Ready to Merge

#26625 Python Array interoperability improvements
  modules/packages/Python.chpl
  modules/packages/PythonHelper/ArrayTypes.c
  modules/packages/PythonHelper/ArrayTypes.h
  test/library/packages/Python/correctness/arrays/CLEANFILES
  test/library/packages/Python/correctness/arrays/COMPOPTS
  test/library/packages/Python/correctness/arrays/EXECENV
  test/library/packages/Python/correctness/arrays/myArray.chpl
  test/library/packages/Python/correctness/arrays/myArray.good
  test/library/packages/Python/correctness/arrays/myArrayReturnArray.chpl
  test/library/packages/Python/correctness/arrays/myArrayReturnArray.good
  test/library/packages/Python/correctness/arrays/myArrayReturnArray.prediff
  test/library/packages/Python/correctness/arrays/myList.chpl
  test/library/packages/Python/correctness/arrays/myList.good
  test/library/packages/Python/correctness/arrays/nestedArrays.chpl
  test/library/packages/Python/correctness/arrays/nestedArrays.good
  test/library/packages/Python/correctness/arrays/nestedArrays.py
  test/library/packages/Python/correctness/arrays/numpyInterop.chpl
  test/library/packages/Python/correctness/arrays/numpyInterop.good
  test/library/packages/Python/correctness/arrays/numpyInterop.skipif
  test/library/packages/Python/correctness/arrays/python_libs.notest
  test/library/packages/Python/correctness/loadingCode/CLEANFILES
  test/library/packages/Python/correctness/loadingCode/COMPOPTS
  test/library/packages/Python/correctness/loadingCode/EXECENV
  test/library/packages/Python/correctness/loadingCode/fromCloudPickle.chpl
  test/library/packages/Python/correctness/loadingCode/fromCloudPickle.good
  test/library/packages/Python/correctness/loadingCode/fromCloudPickle.preexec
  test/library/packages/Python/correctness/loadingCode/fromCloudPickle.py
  test/library/packages/Python/correctness/loadingCode/fromCloudPickle.skipif
  test/library/packages/Python/correctness/loadingCode/fromPickle.chpl
  test/library/packages/Python/correctness/loadingCode/fromPickle.good
  test/library/packages/Python/correctness/loadingCode/fromPickle.preexec
  test/library/packages/Python/correctness/loadingCode/fromPickle.py
  test/library/packages/Python/correctness/loadingCode/moduleFromBytes.chpl
  test/library/packages/Python/correctness/loadingCode/moduleFromBytes.execopts
  test/library/packages/Python/correctness/loadingCode/moduleFromBytes.good
  test/library/packages/Python/correctness/loadingCode/moduleFromBytes.py
  test/library/packages/Python/correctness/loadingCode/moduleFromString.chpl
  test/library/packages/Python/correctness/loadingCode/moduleFromString.good
  test/library/packages/Python/correctness/loadingCode/moduleFromString.py
  test/library/packages/Python/correctness/loadingCode/python_libs.notest
  test/library/packages/Python/correctness/python_libs.notest
Labels: stat: Ready to Merge

#26648 Add a skipif for this test with `--fast`, it relies on bounds checking
  test/library/standard/Set/zippering/arrayShorter2.skipif
Labels: area: Tests / Benchmarks, stat: Ready to Merge

#26665 Skip this test with valgrind
  test/sparse/vass/sparse-mismatch-dom-err-dom1dom2dom2.skipif
Labels: area: Tests / Benchmarks

#26657 Fix issues in `distBag.addBulk`
  modules/packages/DistributedBag.chpl
  test/library/packages/DistributedBag/addBulk.chpl
  test/library/packages/DistributedBag/addBulk.good
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Ready to Merge

#26519 Add parallel iterators for map.keys and map.values
  modules/internal/ChapelHashtable.chpl
  modules/standard/Map.chpl
  modules/standard/Set.chpl
  test/library/standard/Map/reduceOverKeysAndValues.chpl
  test/library/standard/Map/reduceOverKeysAndValues.good
  test/library/standard/Map/testIterators.chpl
  test/library/standard/Map/testIterators.good
  test/library/standard/Map/zipWithMapAndSet.chpl
  test/library/standard/Map/zipWithMapAndSet.execopts
  test/library/standard/Map/zipWithMapAndSet.good
Labels: stat: Ready to Merge

#26703 Add a `sep` argument to `writeln`
  modules/standard/ChapelIO.chpl
  modules/standard/IO.chpl
  test/functions/deitz/test_write_type_error.good
  test/functions/resolution/errors/badWrite.good
  test/functions/varargs/typeToVarArgs.good
  test/io/serializers/optionalArg.bad
  test/io/serializers/unstableWriting.good
  test/io/sungeun/funcPtr3.good
  test/library/standard/IO/writelnWithSep.chpl
  test/library/standard/IO/writelnWithSep.good
  test/unstable/binaryFormat.good
  test/unstable/writelnSep.chpl
  test/unstable/writelnSep.good
Labels: stat: Ready to Merge

#26706 Add support for sets to the Python library
  modules/packages/Python.chpl
  test/library/packages/Python/correctness/arrays/mySet.chpl
  test/library/packages/Python/correctness/arrays/mySet.good
  test/library/packages/Python/correctness/basicTypes.chpl
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Ready to Merge

#26745 Suppress the failures for these HDFS tests for now
  test/library/packages/HDFS/hdfsNumbers.suppressif
  test/library/packages/HDFS/hello-hadoop.suppressif
Labels: area: Tests / Benchmarks

#26731 Improve error message when trying to sort an unsupported record
  modules/internal/ChapelBase.chpl
  modules/standard/Sort.chpl
  test/library/standard/Sort/errors/sortArrayField.chpl
  test/library/standard/Sort/errors/sortArrayField.good
Labels: stat: Ready to Merge

#26738 Add support for Python dictionaries to the Python module
  modules/packages/Python.chpl
  test/library/packages/Python/correctness/arrays/myDict.chpl
  test/library/packages/Python/correctness/arrays/myDict.good
  test/library/packages/Python/correctness/basicTypes.chpl
  test/library/packages/Python/memleaks/basicTypes.chpl
  test/library/packages/Python/memleaks/maps.chpl
  test/library/packages/Python/memleaks/maps.good
Labels: area: Libraries / Modules, area: Tests / Benchmarks, stat: Ready to Merge

#26771 Improve what goes into JUnit XML for reporting with Jenkins
  Makefile.devel
  third-party/chpl-venv/test-requirements.txt
  tools/chpl-language-server/Makefile
  util/cron/nightly
  util/cron/nightly_email_file.pm
  util/cron/nightlysubs.pm
  util/test/convert_nightly_system_command_log_to_junit_xml.py
  util/test/convert_start_test_log_to_junit_xml.py
  util/test/merge_junit_xmls
  util/test/merge_junit_xmls.py
  util/test/start_test.py
  util/test/sub_test.py
Labels: area: BTR

#26778 Dyno: include methods from imported types
  frontend/include/chpl/resolution/resolution-queries.h
  frontend/include/chpl/resolution/resolution-types.h
  frontend/include/chpl/resolution/scope-types.h
  frontend/lib/resolution/Resolver.cpp
  frontend/lib/resolution/Resolver.h
  frontend/lib/resolution/resolution-queries.cpp
  frontend/lib/resolution/resolution-types.cpp
  frontend/lib/resolution/scope-queries.cpp
  frontend/test/resolution/CMakeLists.txt
  frontend/test/resolution/testTertiaryImport.cpp
Labels: area: Compiler, area: Dyno
